//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace WE_Tool.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile DetailPanelToggleIcon.json
//       
//       Input file:
//           DetailPanelToggleIcon.json (5053 bytes created 22:23+08:00 Sep 18 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    24 |
// |--------------------------+-------|
// | Expression animators     |     1 |
// | KeyFrame animators       |     1 |
// | Reference parameters     |     1 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     - |
// | CompositionSpriteShapes  |     2 |
// |--------------------------+-------|
// | Brushes                  |     1 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace WE_Tool.AnimatedVisuals
{
    // Name:        RightToggleFilterButton
    // Frame rate:  60 fps
    // Frame count: 20
    // Duration:    333.3 mS
    // ____________________________________________________________________________________________
    // |           Marker           |           Constant           | Frame |  mS   |   Progress   |
    // |____________________________|______________________________|_______|_______|______________|
    // | NormalToPointerOver_Start  | M_NormalToPointerOver_Start  |     0 |   0.0 | 0F           |
    // | NormalToPointerOver_End    | M_NormalToPointerOver_End    |     0 |   0.0 | 0F           |
    // | PointerOverToNormal_Start  | M_PointerOverToNormal_Start  |     0 |   0.0 | 0F           |
    // | PointerOverToNormal_End    | M_PointerOverToNormal_End    |     0 |   0.0 | 0F           |
    // | NormalToPressed_Start      | M_NormalToPressed_Start      |     0 |   0.0 | 0F           |
    // | PointerOverToPressed_Start | M_PointerOverToPressed_Start |     0 |   0.0 | 0F           |
    // | NormalToPlaying_Start      | M_NormalToPlaying_Start      |     0 |   0.0 | 0F           |
    // | NormalToPressed_End        | M_NormalToPressed_End        |    10 | 166.7 | 0.502499998F |
    // | PressedToNormal_Start      | M_PressedToNormal_Start      |    10 | 166.7 | 0.502499998F |
    // | PointerOverToPressed_End   | M_PointerOverToPressed_End   |    10 | 166.7 | 0.502499998F |
    // | PressedToPointerOver_Start | M_PressedToPointerOver_Start |    10 | 166.7 | 0.502499998F |
    // | PressedToNormal_End        | M_PressedToNormal_End        |    20 | 333.3 | 1F           |
    // | PressedToPointerOver_End   | M_PressedToPointerOver_End   |    20 | 333.3 | 1F           |
    // | NormalToPlaying_End        | M_NormalToPlaying_End        |    20 | 333.3 | 1F           |
    // | PlayingToNormal_Start      | M_PlayingToNormal_Start      |    20 | 333.3 | 1F           |
    // | PlayingToNormal_End        | M_PlayingToNormal_End        |    20 | 333.3 | 1F           |
    // --------------------------------------------------------------------------------------------
    public sealed partial class DetailPanelToggleIcon
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 0.333 seconds.
        internal const long c_durationTicks = 3333333;

        // Marker: NormalToPointerOver_Start.
        internal const float M_NormalToPointerOver_Start = 0F;

        // Marker: NormalToPointerOver_End.
        internal const float M_NormalToPointerOver_End = 0F;

        // Marker: PointerOverToNormal_Start.
        internal const float M_PointerOverToNormal_Start = 0F;

        // Marker: PointerOverToNormal_End.
        internal const float M_PointerOverToNormal_End = 0F;

        // Marker: NormalToPressed_Start.
        internal const float M_NormalToPressed_Start = 0F;

        // Marker: PointerOverToPressed_Start.
        internal const float M_PointerOverToPressed_Start = 0F;

        // Marker: NormalToPlaying_Start.
        internal const float M_NormalToPlaying_Start = 0F;

        // Marker: NormalToPressed_End.
        internal const float M_NormalToPressed_End = 0.502499998F;

        // Marker: PressedToNormal_Start.
        internal const float M_PressedToNormal_Start = 0.502499998F;

        // Marker: PointerOverToPressed_End.
        internal const float M_PointerOverToPressed_End = 0.502499998F;

        // Marker: PressedToPointerOver_Start.
        internal const float M_PressedToPointerOver_Start = 0.502499998F;

        // Marker: PressedToNormal_End.
        internal const float M_PressedToNormal_End = 1F;

        // Marker: PressedToPointerOver_End.
        internal const float M_PressedToPointerOver_End = 1F;

        // Marker: NormalToPlaying_End.
        internal const float M_NormalToPlaying_End = 1F;

        // Marker: PlayingToNormal_Start.
        internal const float M_PlayingToNormal_Start = 1F;

        // Marker: PlayingToNormal_End.
        internal const float M_PlayingToNormal_End = 1F;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new DetailPanelToggleIcon_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 20d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(3333333);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 20d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "NormalToPointerOver_Start", 0d },
                { "NormalToPointerOver_End", 0d },
                { "PointerOverToNormal_Start", 0d },
                { "PointerOverToNormal_End", 0d },
                { "NormalToPressed_Start", 0d },
                { "PointerOverToPressed_Start", 0d },
                { "NormalToPlaying_Start", 0d },
                { "NormalToPressed_End", 0.5025 },
                { "PressedToNormal_Start", 0.5025 },
                { "PointerOverToPressed_End", 0.5025 },
                { "PressedToPointerOver_Start", 0.5025 },
                { "PressedToNormal_End", 1d },
                { "PressedToPointerOver_End", 1d },
                { "NormalToPlaying_End", 1d },
                { "PlayingToNormal_Start", 1d },
                { "PlayingToNormal_End", 1d },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed partial class DetailPanelToggleIcon_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 3333333;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionColorBrush _colorBrush_AlmostLavender_FFEBEBEB;
            CompositionSpriteShape _spriteShape_1;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                return result;
            }

            // - Layer aggregator
            // 路径 1
            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - Layer aggregator
            // - - 路径 1
            CanvasGeometry Geometry()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(80.2580032F, -159.490005F));
                    builder.AddLine(new Vector2(80.0319977F, 160.244995F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostLavender_FFEBEBEB()
            {
                return (_colorBrush_AlmostLavender_FFEBEBEB == null)
                    ? _colorBrush_AlmostLavender_FFEBEBEB = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xEB, 0xEB, 0xEB))
                    : _colorBrush_AlmostLavender_FFEBEBEB;
            }

            // - Layer aggregator
            // 路径 1
            CompositionPathGeometry PathGeometry()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry()));
            }

            // - Layer aggregator
            // Offset:<256, 256>
            // 矩形路径 1.RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_481x352()
            {
                var result = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(81F, 81F);
                result.Offset = new Vector2(-240.5F, -176F);
                result.Size = new Vector2(481F, 352F);
                return result;
            }

            // Layer aggregator
            // 矩形路径 1
            CompositionSpriteShape SpriteShape_0()
            {
                // Offset:<256, 256>
                var result = CreateSpriteShape(RoundedRectangle_481x352(), new Matrix3x2(1F, 0F, 0F, 1F, 256F, 256F));;
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // Layer aggregator
            // 路径 1
            CompositionSpriteShape SpriteShape_1()
            {
                if (_spriteShape_1 != null) { return _spriteShape_1; }
                var result = _spriteShape_1 = _c.CreateSpriteShape(PathGeometry());
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(512F, 512F);
                var shapes = result.Shapes;
                // Offset:<256, 256>
                shapes.Add(SpriteShape_0());
                // 路径 1
                shapes.Add(SpriteShape_1());
                return result;
            }

            // - - Layer aggregator
            // - 路径 1
            // Offset
            StepEasingFunction HoldThenStepEasingFunction()
            {
                var result = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            // - Layer aggregator
            // 路径 1
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(256F, 256F), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.5F, new Vector2(380F, 256F), CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(1F, new Vector2(256F, 256F), CubicBezierEasingFunction_0());
                return result;
            }

            internal DetailPanelToggleIcon_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(512F, 512F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _spriteShape_1.StartAnimation("Offset", OffsetVector2Animation(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _spriteShape_1.StopAnimation("Offset");
            }

        }
    }
}
