//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace WE_Tool.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile InstalledComponentsIcon.json
//       
//       Input file:
//           InstalledComponentsIcon.json (10521 bytes created 10:58+08:00 Sep 16 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    32 |
// |--------------------------+-------|
// | Expression animators     |     1 |
// | KeyFrame animators       |     4 |
// | Reference parameters     |     1 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     - |
// | CompositionSpriteShapes  |     2 |
// |--------------------------+-------|
// | Brushes                  |     1 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace WE_Tool.AnimatedVisuals
{
    // Name:        InstalledComponents
    // Frame rate:  60 fps
    // Frame count: 20
    // Duration:    333.3 mS
    // ____________________________________________________________________________________________________________________________
    // |                   Marker                   |                   Constant                   | Frame |  mS   |   Progress   |
    // |____________________________________________|______________________________________________|_______|_______|______________|
    // | NormalToPointerOver_Start                  | M_NormalToPointerOver_Start                  |     0 |   0.0 | 0F           |
    // | NormalToPointerOver_End                    | M_NormalToPointerOver_End                    |     0 |   0.0 | 0F           |
    // | NormalToPressed_Start                      | M_NormalToPressed_Start                      |     0 |   0.0 | 0F           |
    // | NormalToSelected_Start                     | M_NormalToSelected_Start                     |     0 |   0.0 | 0F           |
    // | NormalToSelected_End                       | M_NormalToSelected_End                       |     0 |   0.0 | 0F           |
    // | NormalToPressedSelected_Start              | M_NormalToPressedSelected_Start              |     0 |   0.0 | 0F           |
    // | NormalToPointerOverSelected_Start          | M_NormalToPointerOverSelected_Start          |     0 |   0.0 | 0F           |
    // | NormalToPointerOverSelected_End            | M_NormalToPointerOverSelected_End            |     0 |   0.0 | 0F           |
    // | PointerOverToNormal_Start                  | M_PointerOverToNormal_Start                  |     0 |   0.0 | 0F           |
    // | PointerOverToNormal_End                    | M_PointerOverToNormal_End                    |     0 |   0.0 | 0F           |
    // | PointerOverToPressed_Start                 | M_PointerOverToPressed_Start                 |     0 |   0.0 | 0F           |
    // | PointerOverToSelected_Start                | M_PointerOverToSelected_Start                |     0 |   0.0 | 0F           |
    // | PointerOverToSelected_End                  | M_PointerOverToSelected_End                  |     0 |   0.0 | 0F           |
    // | PointerOverToPressedSelected_Start         | M_PointerOverToPressedSelected_Start         |     0 |   0.0 | 0F           |
    // | PointerOverToPointerOverSelected_Start     | M_PointerOverToPointerOverSelected_Start     |     0 |   0.0 | 0F           |
    // | PointerOverToPointerOverSelected_End       | M_PointerOverToPointerOverSelected_End       |     0 |   0.0 | 0F           |
    // | PressedToPressedSelected_Start             | M_PressedToPressedSelected_Start             |     0 |   0.0 | 0F           |
    // | SelectedToNormal_Start                     | M_SelectedToNormal_Start                     |     0 |   0.0 | 0F           |
    // | SelectedToNormal_End                       | M_SelectedToNormal_End                       |     0 |   0.0 | 0F           |
    // | SelectedToPointerOver_Start                | M_SelectedToPointerOver_Start                |     0 |   0.0 | 0F           |
    // | SelectedToPointerOver_End                  | M_SelectedToPointerOver_End                  |     0 |   0.0 | 0F           |
    // | SelectedToPressed_Start                    | M_SelectedToPressed_Start                    |     0 |   0.0 | 0F           |
    // | SelectedToPressedSelected_Start            | M_SelectedToPressedSelected_Start            |     0 |   0.0 | 0F           |
    // | SelectedToPointerOverSelected_Start        | M_SelectedToPointerOverSelected_Start        |     0 |   0.0 | 0F           |
    // | SelectedToPointerOverSelected_End          | M_SelectedToPointerOverSelected_End          |     0 |   0.0 | 0F           |
    // | PressedSelectedToPressed_Start             | M_PressedSelectedToPressed_Start             |     0 |   0.0 | 0F           |
    // | PointerOverSelectedToNormal_Start          | M_PointerOverSelectedToNormal_Start          |     0 |   0.0 | 0F           |
    // | PointerOverSelectedToNormal_End            | M_PointerOverSelectedToNormal_End            |     0 |   0.0 | 0F           |
    // | PointerOverSelectedToPointerOver_Start     | M_PointerOverSelectedToPointerOver_Start     |     0 |   0.0 | 0F           |
    // | PointerOverSelectedToPointerOver_End       | M_PointerOverSelectedToPointerOver_End       |     0 |   0.0 | 0F           |
    // | PointerOverSelectedToPressed_Start         | M_PointerOverSelectedToPressed_Start         |     0 |   0.0 | 0F           |
    // | PointerOverSelectedToSelected_Start        | M_PointerOverSelectedToSelected_Start        |     0 |   0.0 | 0F           |
    // | PointerOverSelectedToSelected_End          | M_PointerOverSelectedToSelected_End          |     0 |   0.0 | 0F           |
    // | PointerOverSelectedToPressedSelected_Start | M_PointerOverSelectedToPressedSelected_Start |     0 |   0.0 | 0F           |
    // | NormalToPressed_End                        | M_NormalToPressed_End                        |    10 | 166.7 | 0.502499998F |
    // | NormalToPressedSelected_End                | M_NormalToPressedSelected_End                |    10 | 166.7 | 0.502499998F |
    // | PointerOverToPressed_End                   | M_PointerOverToPressed_End                   |    10 | 166.7 | 0.502499998F |
    // | PointerOverToPressedSelected_End           | M_PointerOverToPressedSelected_End           |    10 | 166.7 | 0.502499998F |
    // | PressedToNormal_Start                      | M_PressedToNormal_Start                      |    10 | 166.7 | 0.502499998F |
    // | PressedToPointerOver_Start                 | M_PressedToPointerOver_Start                 |    10 | 166.7 | 0.502499998F |
    // | PressedToSelected_Start                    | M_PressedToSelected_Start                    |    10 | 166.7 | 0.502499998F |
    // | PressedToPressedSelected_End               | M_PressedToPressedSelected_End               |    10 | 166.7 | 0.502499998F |
    // | PressedToPointerOverSelected_Start         | M_PressedToPointerOverSelected_Start         |    10 | 166.7 | 0.502499998F |
    // | SelectedToPressed_End                      | M_SelectedToPressed_End                      |    10 | 166.7 | 0.502499998F |
    // | SelectedToPressedSelected_End              | M_SelectedToPressedSelected_End              |    10 | 166.7 | 0.502499998F |
    // | PressedSelectedToNormal_Start              | M_PressedSelectedToNormal_Start              |    10 | 166.7 | 0.502499998F |
    // | PressedSelectedToPointerOver_Start         | M_PressedSelectedToPointerOver_Start         |    10 | 166.7 | 0.502499998F |
    // | PressedSelectedToPressed_End               | M_PressedSelectedToPressed_End               |    10 | 166.7 | 0.502499998F |
    // | PressedSelectedToSelected_Start            | M_PressedSelectedToSelected_Start            |    10 | 166.7 | 0.502499998F |
    // | PressedSelectedToPointerOverSelected_Start | M_PressedSelectedToPointerOverSelected_Start |    10 | 166.7 | 0.502499998F |
    // | PointerOverSelectedToPressed_End           | M_PointerOverSelectedToPressed_End           |    10 | 166.7 | 0.502499998F |
    // | PointerOverSelectedToPressedSelected_End   | M_PointerOverSelectedToPressedSelected_End   |    10 | 166.7 | 0.502499998F |
    // | PressedToNormal_End                        | M_PressedToNormal_End                        |    20 | 333.3 | 1F           |
    // | PressedToPointerOver_End                   | M_PressedToPointerOver_End                   |    20 | 333.3 | 1F           |
    // | PressedToSelected_End                      | M_PressedToSelected_End                      |    20 | 333.3 | 1F           |
    // | PressedToPointerOverSelected_End           | M_PressedToPointerOverSelected_End           |    20 | 333.3 | 1F           |
    // | PressedSelectedToNormal_End                | M_PressedSelectedToNormal_End                |    20 | 333.3 | 1F           |
    // | PressedSelectedToPointerOver_End           | M_PressedSelectedToPointerOver_End           |    20 | 333.3 | 1F           |
    // | PressedSelectedToSelected_End              | M_PressedSelectedToSelected_End              |    20 | 333.3 | 1F           |
    // | PressedSelectedToPointerOverSelected_End   | M_PressedSelectedToPointerOverSelected_End   |    20 | 333.3 | 1F           |
    // ----------------------------------------------------------------------------------------------------------------------------
    public sealed class InstalledComponentsIcon
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 0.333 seconds.
        internal const long c_durationTicks = 3333333;

        // Marker: NormalToPointerOver_Start.
        internal const float M_NormalToPointerOver_Start = 0F;

        // Marker: NormalToPointerOver_End.
        internal const float M_NormalToPointerOver_End = 0F;

        // Marker: NormalToPressed_Start.
        internal const float M_NormalToPressed_Start = 0F;

        // Marker: NormalToSelected_Start.
        internal const float M_NormalToSelected_Start = 0F;

        // Marker: NormalToSelected_End.
        internal const float M_NormalToSelected_End = 0F;

        // Marker: NormalToPressedSelected_Start.
        internal const float M_NormalToPressedSelected_Start = 0F;

        // Marker: NormalToPointerOverSelected_Start.
        internal const float M_NormalToPointerOverSelected_Start = 0F;

        // Marker: NormalToPointerOverSelected_End.
        internal const float M_NormalToPointerOverSelected_End = 0F;

        // Marker: PointerOverToNormal_Start.
        internal const float M_PointerOverToNormal_Start = 0F;

        // Marker: PointerOverToNormal_End.
        internal const float M_PointerOverToNormal_End = 0F;

        // Marker: PointerOverToPressed_Start.
        internal const float M_PointerOverToPressed_Start = 0F;

        // Marker: PointerOverToSelected_Start.
        internal const float M_PointerOverToSelected_Start = 0F;

        // Marker: PointerOverToSelected_End.
        internal const float M_PointerOverToSelected_End = 0F;

        // Marker: PointerOverToPressedSelected_Start.
        internal const float M_PointerOverToPressedSelected_Start = 0F;

        // Marker: PointerOverToPointerOverSelected_Start.
        internal const float M_PointerOverToPointerOverSelected_Start = 0F;

        // Marker: PointerOverToPointerOverSelected_End.
        internal const float M_PointerOverToPointerOverSelected_End = 0F;

        // Marker: PressedToPressedSelected_Start.
        internal const float M_PressedToPressedSelected_Start = 0F;

        // Marker: SelectedToNormal_Start.
        internal const float M_SelectedToNormal_Start = 0F;

        // Marker: SelectedToNormal_End.
        internal const float M_SelectedToNormal_End = 0F;

        // Marker: SelectedToPointerOver_Start.
        internal const float M_SelectedToPointerOver_Start = 0F;

        // Marker: SelectedToPointerOver_End.
        internal const float M_SelectedToPointerOver_End = 0F;

        // Marker: SelectedToPressed_Start.
        internal const float M_SelectedToPressed_Start = 0F;

        // Marker: SelectedToPressedSelected_Start.
        internal const float M_SelectedToPressedSelected_Start = 0F;

        // Marker: SelectedToPointerOverSelected_Start.
        internal const float M_SelectedToPointerOverSelected_Start = 0F;

        // Marker: SelectedToPointerOverSelected_End.
        internal const float M_SelectedToPointerOverSelected_End = 0F;

        // Marker: PressedSelectedToPressed_Start.
        internal const float M_PressedSelectedToPressed_Start = 0F;

        // Marker: PointerOverSelectedToNormal_Start.
        internal const float M_PointerOverSelectedToNormal_Start = 0F;

        // Marker: PointerOverSelectedToNormal_End.
        internal const float M_PointerOverSelectedToNormal_End = 0F;

        // Marker: PointerOverSelectedToPointerOver_Start.
        internal const float M_PointerOverSelectedToPointerOver_Start = 0F;

        // Marker: PointerOverSelectedToPointerOver_End.
        internal const float M_PointerOverSelectedToPointerOver_End = 0F;

        // Marker: PointerOverSelectedToPressed_Start.
        internal const float M_PointerOverSelectedToPressed_Start = 0F;

        // Marker: PointerOverSelectedToSelected_Start.
        internal const float M_PointerOverSelectedToSelected_Start = 0F;

        // Marker: PointerOverSelectedToSelected_End.
        internal const float M_PointerOverSelectedToSelected_End = 0F;

        // Marker: PointerOverSelectedToPressedSelected_Start.
        internal const float M_PointerOverSelectedToPressedSelected_Start = 0F;

        // Marker: NormalToPressed_End.
        internal const float M_NormalToPressed_End = 0.502499998F;

        // Marker: NormalToPressedSelected_End.
        internal const float M_NormalToPressedSelected_End = 0.502499998F;

        // Marker: PointerOverToPressed_End.
        internal const float M_PointerOverToPressed_End = 0.502499998F;

        // Marker: PointerOverToPressedSelected_End.
        internal const float M_PointerOverToPressedSelected_End = 0.502499998F;

        // Marker: PressedToNormal_Start.
        internal const float M_PressedToNormal_Start = 0.502499998F;

        // Marker: PressedToPointerOver_Start.
        internal const float M_PressedToPointerOver_Start = 0.502499998F;

        // Marker: PressedToSelected_Start.
        internal const float M_PressedToSelected_Start = 0.502499998F;

        // Marker: PressedToPressedSelected_End.
        internal const float M_PressedToPressedSelected_End = 0.502499998F;

        // Marker: PressedToPointerOverSelected_Start.
        internal const float M_PressedToPointerOverSelected_Start = 0.502499998F;

        // Marker: SelectedToPressed_End.
        internal const float M_SelectedToPressed_End = 0.502499998F;

        // Marker: SelectedToPressedSelected_End.
        internal const float M_SelectedToPressedSelected_End = 0.502499998F;

        // Marker: PressedSelectedToNormal_Start.
        internal const float M_PressedSelectedToNormal_Start = 0.502499998F;

        // Marker: PressedSelectedToPointerOver_Start.
        internal const float M_PressedSelectedToPointerOver_Start = 0.502499998F;

        // Marker: PressedSelectedToPressed_End.
        internal const float M_PressedSelectedToPressed_End = 0.502499998F;

        // Marker: PressedSelectedToSelected_Start.
        internal const float M_PressedSelectedToSelected_Start = 0.502499998F;

        // Marker: PressedSelectedToPointerOverSelected_Start.
        internal const float M_PressedSelectedToPointerOverSelected_Start = 0.502499998F;

        // Marker: PointerOverSelectedToPressed_End.
        internal const float M_PointerOverSelectedToPressed_End = 0.502499998F;

        // Marker: PointerOverSelectedToPressedSelected_End.
        internal const float M_PointerOverSelectedToPressedSelected_End = 0.502499998F;

        // Marker: PressedToNormal_End.
        internal const float M_PressedToNormal_End = 1F;

        // Marker: PressedToPointerOver_End.
        internal const float M_PressedToPointerOver_End = 1F;

        // Marker: PressedToSelected_End.
        internal const float M_PressedToSelected_End = 1F;

        // Marker: PressedToPointerOverSelected_End.
        internal const float M_PressedToPointerOverSelected_End = 1F;

        // Marker: PressedSelectedToNormal_End.
        internal const float M_PressedSelectedToNormal_End = 1F;

        // Marker: PressedSelectedToPointerOver_End.
        internal const float M_PressedSelectedToPointerOver_End = 1F;

        // Marker: PressedSelectedToSelected_End.
        internal const float M_PressedSelectedToSelected_End = 1F;

        // Marker: PressedSelectedToPointerOverSelected_End.
        internal const float M_PressedSelectedToPointerOverSelected_End = 1F;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new InstalledComponentsIcon_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 20d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(3333333);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 20d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "NormalToPointerOver_Start", 0d },
                { "NormalToPointerOver_End", 0d },
                { "NormalToPressed_Start", 0d },
                { "NormalToSelected_Start", 0d },
                { "NormalToSelected_End", 0d },
                { "NormalToPressedSelected_Start", 0d },
                { "NormalToPointerOverSelected_Start", 0d },
                { "NormalToPointerOverSelected_End", 0d },
                { "PointerOverToNormal_Start", 0d },
                { "PointerOverToNormal_End", 0d },
                { "PointerOverToPressed_Start", 0d },
                { "PointerOverToSelected_Start", 0d },
                { "PointerOverToSelected_End", 0d },
                { "PointerOverToPressedSelected_Start", 0d },
                { "PointerOverToPointerOverSelected_Start", 0d },
                { "PointerOverToPointerOverSelected_End", 0d },
                { "PressedToPressedSelected_Start", 0d },
                { "SelectedToNormal_Start", 0d },
                { "SelectedToNormal_End", 0d },
                { "SelectedToPointerOver_Start", 0d },
                { "SelectedToPointerOver_End", 0d },
                { "SelectedToPressed_Start", 0d },
                { "SelectedToPressedSelected_Start", 0d },
                { "SelectedToPointerOverSelected_Start", 0d },
                { "SelectedToPointerOverSelected_End", 0d },
                { "PressedSelectedToPressed_Start", 0d },
                { "PointerOverSelectedToNormal_Start", 0d },
                { "PointerOverSelectedToNormal_End", 0d },
                { "PointerOverSelectedToPointerOver_Start", 0d },
                { "PointerOverSelectedToPointerOver_End", 0d },
                { "PointerOverSelectedToPressed_Start", 0d },
                { "PointerOverSelectedToSelected_Start", 0d },
                { "PointerOverSelectedToSelected_End", 0d },
                { "PointerOverSelectedToPressedSelected_Start", 0d },
                { "NormalToPressed_End", 0.5025 },
                { "NormalToPressedSelected_End", 0.5025 },
                { "PointerOverToPressed_End", 0.5025 },
                { "PointerOverToPressedSelected_End", 0.5025 },
                { "PressedToNormal_Start", 0.5025 },
                { "PressedToPointerOver_Start", 0.5025 },
                { "PressedToSelected_Start", 0.5025 },
                { "PressedToPressedSelected_End", 0.5025 },
                { "PressedToPointerOverSelected_Start", 0.5025 },
                { "SelectedToPressed_End", 0.5025 },
                { "SelectedToPressedSelected_End", 0.5025 },
                { "PressedSelectedToNormal_Start", 0.5025 },
                { "PressedSelectedToPointerOver_Start", 0.5025 },
                { "PressedSelectedToPressed_End", 0.5025 },
                { "PressedSelectedToSelected_Start", 0.5025 },
                { "PressedSelectedToPointerOverSelected_Start", 0.5025 },
                { "PointerOverSelectedToPressed_End", 0.5025 },
                { "PointerOverSelectedToPressedSelected_End", 0.5025 },
                { "PressedToNormal_End", 1d },
                { "PressedToPointerOver_End", 1d },
                { "PressedToSelected_End", 1d },
                { "PressedToPointerOverSelected_End", 1d },
                { "PressedSelectedToNormal_End", 1d },
                { "PressedSelectedToPointerOver_End", 1d },
                { "PressedSelectedToSelected_End", 1d },
                { "PressedSelectedToPointerOverSelected_End", 1d },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class InstalledComponentsIcon_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 3333333;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionColorBrush _colorBrush_AlmostLavender_FFEBEBEB;
            CompositionSpriteShape _spriteShape_0;
            CompositionSpriteShape _spriteShape_1;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - Shape tree root for layer: “”轮廓
            // - -  Offset:<0, 512>
            // -  4+ 3.PathGeometry
            CanvasGeometry Geometry_0()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_1(), Geometry_2() },
                    CanvasFilledRegionDetermination.Winding);
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  4+ 3.PathGeometry
            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(415.125F, -120F));
                    builder.AddCubicBezier(new Vector2(410.039001F, -117.164001F), new Vector2(405.582001F, -113.832001F), new Vector2(401.75F, -110F));
                    builder.AddCubicBezier(new Vector2(397.914001F, -106.164001F), new Vector2(394.625F, -101.664001F), new Vector2(391.875F, -96.5F));
                    builder.AddCubicBezier(new Vector2(389.125F, -91.3320007F), new Vector2(386.5F, -85.1640015F), new Vector2(384F, -78F));
                    builder.AddCubicBezier(new Vector2(380F, -91.3320007F), new Vector2(374.082001F, -102.039001F), new Vector2(366.25F, -110.125F));
                    builder.AddCubicBezier(new Vector2(358.414001F, -118.207001F), new Vector2(347.75F, -124.164001F), new Vector2(334.25F, -128F));
                    builder.AddCubicBezier(new Vector2(340.914001F, -130.164001F), new Vector2(346.832001F, -132.75F), new Vector2(352F, -135.75F));
                    builder.AddCubicBezier(new Vector2(357.164001F, -138.75F), new Vector2(361.75F, -142.25F), new Vector2(365.75F, -146.25F));
                    builder.AddCubicBezier(new Vector2(369.75F, -150.25F), new Vector2(373.207001F, -154.832001F), new Vector2(376.125F, -160F));
                    builder.AddCubicBezier(new Vector2(379.039001F, -165.164001F), new Vector2(381.5F, -171.164001F), new Vector2(383.5F, -178F));
                    builder.AddCubicBezier(new Vector2(386F, -171F), new Vector2(388.664001F, -164.875F), new Vector2(391.5F, -159.625F));
                    builder.AddCubicBezier(new Vector2(394.332001F, -154.375F), new Vector2(397.664001F, -149.789001F), new Vector2(401.5F, -145.875F));
                    builder.AddCubicBezier(new Vector2(405.332001F, -141.957001F), new Vector2(409.875F, -138.539001F), new Vector2(415.125F, -135.625F));
                    builder.AddCubicBezier(new Vector2(420.375F, -132.707001F), new Vector2(426.582001F, -130.164001F), new Vector2(433.75F, -128F));
                    builder.AddCubicBezier(new Vector2(426.414001F, -125.5F), new Vector2(420.207001F, -122.832001F), new Vector2(415.125F, -120F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  4+ 3.PathGeometry
            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(290.875F, -115.625F));
                    builder.AddCubicBezier(new Vector2(292.789001F, -112.207001F), new Vector2(295.332001F, -109.457001F), new Vector2(298.5F, -107.375F));
                    builder.AddCubicBezier(new Vector2(301.664001F, -105.289001F), new Vector2(305.25F, -103.625F), new Vector2(309.25F, -102.375F));
                    builder.AddCubicBezier(new Vector2(313.25F, -101.125F), new Vector2(317.289001F, -99.875F), new Vector2(321.375F, -98.625F));
                    builder.AddCubicBezier(new Vector2(325.457001F, -97.375F), new Vector2(329.414001F, -95.9140015F), new Vector2(333.25F, -94.25F));
                    builder.AddCubicBezier(new Vector2(337.082001F, -92.5820007F), new Vector2(340.5F, -90.3320007F), new Vector2(343.5F, -87.5F));
                    builder.AddCubicBezier(new Vector2(345.832001F, -85.1640015F), new Vector2(347.832001F, -82.4140015F), new Vector2(349.5F, -79.25F));
                    builder.AddCubicBezier(new Vector2(351.164001F, -76.0820007F), new Vector2(352.582001F, -72.7890015F), new Vector2(353.75F, -69.375F));
                    builder.AddCubicBezier(new Vector2(354.914001F, -65.9570007F), new Vector2(355.957001F, -62.5F), new Vector2(356.875F, -59F));
                    builder.AddCubicBezier(new Vector2(357.789001F, -55.5F), new Vector2(358.75F, -52.25F), new Vector2(359.75F, -49.25F));
                    builder.AddCubicBezier(new Vector2(361.414001F, -44.0820007F), new Vector2(364.539001F, -39.9140015F), new Vector2(369.125F, -36.75F));
                    builder.AddCubicBezier(new Vector2(373.707001F, -33.5820007F), new Vector2(378.664001F, -32F), new Vector2(384F, -32F));
                    builder.AddCubicBezier(new Vector2(391.664001F, -32F), new Vector2(397.332001F, -34.0820007F), new Vector2(401F, -38.25F));
                    builder.AddCubicBezier(new Vector2(404.664001F, -42.4140015F), new Vector2(407.539001F, -47.4570007F), new Vector2(409.625F, -53.375F));
                    builder.AddCubicBezier(new Vector2(411.707001F, -59.2890015F), new Vector2(413.707001F, -65.375F), new Vector2(415.625F, -71.625F));
                    builder.AddCubicBezier(new Vector2(417.539001F, -77.875F), new Vector2(420.5F, -83.0820007F), new Vector2(424.5F, -87.25F));
                    builder.AddCubicBezier(new Vector2(427F, -89.75F), new Vector2(429.789001F, -91.8320007F), new Vector2(432.875F, -93.5F));
                    builder.AddCubicBezier(new Vector2(435.957001F, -95.1640015F), new Vector2(439.207001F, -96.5820007F), new Vector2(442.625F, -97.75F));
                    builder.AddCubicBezier(new Vector2(446.039001F, -98.9140015F), new Vector2(449.457001F, -99.9570007F), new Vector2(452.875F, -100.875F));
                    builder.AddCubicBezier(new Vector2(456.289001F, -101.789001F), new Vector2(459.582001F, -102.75F), new Vector2(462.75F, -103.75F));
                    builder.AddCubicBezier(new Vector2(468.082001F, -105.582001F), new Vector2(472.289001F, -108.75F), new Vector2(475.375F, -113.25F));
                    builder.AddCubicBezier(new Vector2(478.457001F, -117.75F), new Vector2(480F, -122.75F), new Vector2(480F, -128.25F));
                    builder.AddCubicBezier(new Vector2(480F, -133.25F), new Vector2(479F, -137.375F), new Vector2(477F, -140.625F));
                    builder.AddCubicBezier(new Vector2(475F, -143.875F), new Vector2(472.414001F, -146.539001F), new Vector2(469.25F, -148.625F));
                    builder.AddCubicBezier(new Vector2(466.082001F, -150.707001F), new Vector2(462.457001F, -152.414001F), new Vector2(458.375F, -153.75F));
                    builder.AddCubicBezier(new Vector2(454.289001F, -155.082001F), new Vector2(450.164001F, -156.414001F), new Vector2(446F, -157.75F));
                    builder.AddCubicBezier(new Vector2(441.832001F, -159.082001F), new Vector2(437.832001F, -160.539001F), new Vector2(434F, -162.125F));
                    builder.AddCubicBezier(new Vector2(430.164001F, -163.707001F), new Vector2(426.914001F, -165.914001F), new Vector2(424.25F, -168.75F));
                    builder.AddCubicBezier(new Vector2(421.75F, -171.25F), new Vector2(419.664001F, -174.039001F), new Vector2(418F, -177.125F));
                    builder.AddCubicBezier(new Vector2(416.332001F, -180.207001F), new Vector2(414.914001F, -183.375F), new Vector2(413.75F, -186.625F));
                    builder.AddCubicBezier(new Vector2(412.582001F, -189.875F), new Vector2(411.539001F, -193.207001F), new Vector2(410.625F, -196.625F));
                    builder.AddCubicBezier(new Vector2(409.707001F, -200.039001F), new Vector2(408.75F, -203.414001F), new Vector2(407.75F, -206.75F));
                    builder.AddCubicBezier(new Vector2(406.082001F, -211.914001F), new Vector2(402.957001F, -216.082001F), new Vector2(398.375F, -219.25F));
                    builder.AddCubicBezier(new Vector2(393.789001F, -222.414001F), new Vector2(388.832001F, -224F), new Vector2(383.5F, -224F));
                    builder.AddCubicBezier(new Vector2(377.332001F, -224F), new Vector2(372.539001F, -222.664001F), new Vector2(369.125F, -220F));
                    builder.AddCubicBezier(new Vector2(365.707001F, -217.332001F), new Vector2(362.957001F, -213.957001F), new Vector2(360.875F, -209.875F));
                    builder.AddCubicBezier(new Vector2(358.789001F, -205.789001F), new Vector2(357.082001F, -201.25F), new Vector2(355.75F, -196.25F));
                    builder.AddCubicBezier(new Vector2(354.414001F, -191.25F), new Vector2(352.789001F, -186.375F), new Vector2(350.875F, -181.625F));
                    builder.AddCubicBezier(new Vector2(348.957001F, -176.875F), new Vector2(346.414001F, -172.582001F), new Vector2(343.25F, -168.75F));
                    builder.AddCubicBezier(new Vector2(340.082001F, -164.914001F), new Vector2(335.664001F, -162.082001F), new Vector2(330F, -160.25F));
                    builder.AddLine(new Vector2(305.25F, -152.25F));
                    builder.AddCubicBezier(new Vector2(300.414001F, -150.582001F), new Vector2(296.332001F, -147.582001F), new Vector2(293F, -143.25F));
                    builder.AddCubicBezier(new Vector2(289.664001F, -138.914001F), new Vector2(288F, -134.164001F), new Vector2(288F, -129F));
                    builder.AddCubicBezier(new Vector2(288F, -123.5F), new Vector2(288.957001F, -119.039001F), new Vector2(290.875F, -115.625F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - Shape tree root for layer: “”轮廓
            // - -  Offset:<0, 512>
            // -  2+.PathGeometry
            CanvasGeometry Geometry_3()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_4(), Geometry_5() },
                    CanvasFilledRegionDetermination.Winding);
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  2+.PathGeometry
            CanvasGeometry Geometry_4()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(275F, -304.5F));
                    builder.AddCubicBezier(new Vector2(258.164001F, -299.164001F), new Vector2(244.207001F, -290.582001F), new Vector2(233.125F, -278.75F));
                    builder.AddCubicBezier(new Vector2(222.039001F, -266.914001F), new Vector2(213.414001F, -252.914001F), new Vector2(207.25F, -236.75F));
                    builder.AddLine(new Vector2(190.5F, -192.75F));
                    builder.AddLine(new Vector2(176.25F, -236.75F));
                    builder.AddCubicBezier(new Vector2(171.75F, -250.75F), new Vector2(165.707001F, -262.164001F), new Vector2(158.125F, -271F));
                    builder.AddCubicBezier(new Vector2(150.539001F, -279.832001F), new Vector2(141.914001F, -287.207001F), new Vector2(132.25F, -293.125F));
                    builder.AddCubicBezier(new Vector2(122.582001F, -299.039001F), new Vector2(112F, -304.039001F), new Vector2(100.5F, -308.125F));
                    builder.AddCubicBezier(new Vector2(89F, -312.207001F), new Vector2(77F, -316.664001F), new Vector2(64.5F, -321.5F));
                    builder.AddLine(new Vector2(108.75F, -335.75F));
                    builder.AddCubicBezier(new Vector2(116.414001F, -338.25F), new Vector2(123.789001F, -341.789001F), new Vector2(130.875F, -346.375F));
                    builder.AddCubicBezier(new Vector2(137.957001F, -350.957001F), new Vector2(144.332001F, -356.082001F), new Vector2(150F, -361.75F));
                    builder.AddCubicBezier(new Vector2(156F, -367.914001F), new Vector2(161F, -374.414001F), new Vector2(165F, -381.25F));
                    builder.AddCubicBezier(new Vector2(169F, -388.082001F), new Vector2(172.5F, -395.5F), new Vector2(175.5F, -403.5F));
                    builder.AddLine(new Vector2(192.25F, -447.5F));
                    builder.AddLine(new Vector2(206.5F, -403.5F));
                    builder.AddCubicBezier(new Vector2(211F, -389.332001F), new Vector2(217.039001F, -377.875F), new Vector2(224.625F, -369.125F));
                    builder.AddCubicBezier(new Vector2(232.207001F, -360.375F), new Vector2(240.914001F, -353.039001F), new Vector2(250.75F, -347.125F));
                    builder.AddCubicBezier(new Vector2(260.582001F, -341.207001F), new Vector2(271.289001F, -336.207001F), new Vector2(282.875F, -332.125F));
                    builder.AddCubicBezier(new Vector2(294.457001F, -328.039001F), new Vector2(306.582001F, -323.582001F), new Vector2(319.25F, -318.75F));
                    builder.AddLine(new Vector2(275F, -304.5F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  2+.PathGeometry
            CanvasGeometry Geometry_5()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(37.25F, -301.75F));
                    builder.AddCubicBezier(new Vector2(40.75F, -297.25F), new Vector2(45.3320007F, -293.539001F), new Vector2(51F, -290.625F));
                    builder.AddCubicBezier(new Vector2(56.6640015F, -287.707001F), new Vector2(63.1640015F, -285.289001F), new Vector2(70.5F, -283.375F));
                    builder.AddCubicBezier(new Vector2(77.8320007F, -281.457001F), new Vector2(85.25F, -279.164001F), new Vector2(92.75F, -276.5F));
                    builder.AddCubicBezier(new Vector2(100.25F, -273.832001F), new Vector2(107.625F, -270.414001F), new Vector2(114.875F, -266.25F));
                    builder.AddCubicBezier(new Vector2(122.125F, -262.082001F), new Vector2(128.582001F, -256.414001F), new Vector2(134.25F, -249.25F));
                    builder.AddCubicBezier(new Vector2(136.914001F, -245.914001F), new Vector2(139.207001F, -242.375F), new Vector2(141.125F, -238.625F));
                    builder.AddCubicBezier(new Vector2(143.039001F, -234.875F), new Vector2(144.664001F, -230.914001F), new Vector2(146F, -226.75F));
                    builder.AddLine(new Vector2(160.5F, -182.25F));
                    builder.AddCubicBezier(new Vector2(162.664001F, -175.582001F), new Vector2(166.707001F, -170.207001F), new Vector2(172.625F, -166.125F));
                    builder.AddCubicBezier(new Vector2(178.539001F, -162.039001F), new Vector2(185F, -160F), new Vector2(192F, -160F));
                    builder.AddCubicBezier(new Vector2(199.332001F, -160F), new Vector2(205.25F, -161.625F), new Vector2(209.75F, -164.875F));
                    builder.AddCubicBezier(new Vector2(214.25F, -168.125F), new Vector2(218F, -172.414001F), new Vector2(221F, -177.75F));
                    builder.AddCubicBezier(new Vector2(224F, -183.082001F), new Vector2(226.5F, -189.125F), new Vector2(228.5F, -195.875F));
                    builder.AddCubicBezier(new Vector2(230.5F, -202.625F), new Vector2(232.625F, -209.582001F), new Vector2(234.875F, -216.75F));
                    builder.AddCubicBezier(new Vector2(237.125F, -223.914001F), new Vector2(239.875F, -230.914001F), new Vector2(243.125F, -237.75F));
                    builder.AddCubicBezier(new Vector2(246.375F, -244.582001F), new Vector2(250.664001F, -250.664001F), new Vector2(256F, -256F));
                    builder.AddCubicBezier(new Vector2(264.5F, -264.5F), new Vector2(274.25F, -270.5F), new Vector2(285.25F, -274F));
                    builder.AddLine(new Vector2(329.75F, -288.5F));
                    builder.AddCubicBezier(new Vector2(336.25F, -290.664001F), new Vector2(341.582001F, -294.707001F), new Vector2(345.75F, -300.625F));
                    builder.AddCubicBezier(new Vector2(349.914001F, -306.539001F), new Vector2(352F, -312.914001F), new Vector2(352F, -319.75F));
                    builder.AddCubicBezier(new Vector2(352F, -327.414001F), new Vector2(349.832001F, -334.082001F), new Vector2(345.5F, -339.75F));
                    builder.AddCubicBezier(new Vector2(341.164001F, -345.414001F), new Vector2(335.414001F, -349.414001F), new Vector2(328.25F, -351.75F));
                    builder.AddLine(new Vector2(284.25F, -366.25F));
                    builder.AddCubicBezier(new Vector2(272.914001F, -369.914001F), new Vector2(263.164001F, -375.914001F), new Vector2(255F, -384.25F));
                    builder.AddCubicBezier(new Vector2(246.5F, -392.75F), new Vector2(240.5F, -402.5F), new Vector2(237F, -413.5F));
                    builder.AddLine(new Vector2(222.5F, -457.75F));
                    builder.AddCubicBezier(new Vector2(220.164001F, -464.582001F), new Vector2(216.039001F, -470F), new Vector2(210.125F, -474F));
                    builder.AddCubicBezier(new Vector2(204.207001F, -478F), new Vector2(197.75F, -480F), new Vector2(190.75F, -480F));
                    builder.AddCubicBezier(new Vector2(183.75F, -480F), new Vector2(177.289001F, -477.875F), new Vector2(171.375F, -473.625F));
                    builder.AddCubicBezier(new Vector2(165.457001F, -469.375F), new Vector2(161.414001F, -463.914001F), new Vector2(159.25F, -457.25F));
                    builder.AddLine(new Vector2(144.75F, -412.5F));
                    builder.AddCubicBezier(new Vector2(141.25F, -401.832001F), new Vector2(135.332001F, -392.332001F), new Vector2(127F, -384F));
                    builder.AddCubicBezier(new Vector2(123.164001F, -380.164001F), new Vector2(118.832001F, -376.664001F), new Vector2(114F, -373.5F));
                    builder.AddCubicBezier(new Vector2(109.164001F, -370.332001F), new Vector2(104.082001F, -367.832001F), new Vector2(98.75F, -366F));
                    builder.AddLine(new Vector2(54.25F, -351.75F));
                    builder.AddCubicBezier(new Vector2(47.5820007F, -349.582001F), new Vector2(42.2070007F, -345.582001F), new Vector2(38.125F, -339.75F));
                    builder.AddCubicBezier(new Vector2(34.0390015F, -333.914001F), new Vector2(32F, -327.5F), new Vector2(32F, -320.5F));
                    builder.AddCubicBezier(new Vector2(32F, -312.5F), new Vector2(33.75F, -306.25F), new Vector2(37.25F, -301.75F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostLavender_FFEBEBEB()
            {
                return (_colorBrush_AlmostLavender_FFEBEBEB == null)
                    ? _colorBrush_AlmostLavender_FFEBEBEB = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xEB, 0xEB, 0xEB))
                    : _colorBrush_AlmostLavender_FFEBEBEB;
            }

            // - Shape tree root for layer: “”轮廓
            // Offset:<0, 512>
            //  4+ 3.PathGeometry
            CompositionPathGeometry PathGeometry_0()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
            }

            // - Shape tree root for layer: “”轮廓
            // Offset:<0, 512>
            //  2+.PathGeometry
            CompositionPathGeometry PathGeometry_1()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_3()));
            }

            // Shape tree root for layer: “”轮廓
            //  4+ 3
            CompositionSpriteShape SpriteShape_0()
            {
                // Offset:<0, 512>
                var geometry = PathGeometry_0();
                if (_spriteShape_0 != null) { return _spriteShape_0; }
                var result = _spriteShape_0 = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 0F, 512F), ColorBrush_AlmostLavender_FFEBEBEB());;
                result.CenterPoint = new Vector2(384F, -128F);
                return result;
            }

            // Shape tree root for layer: “”轮廓
            //  2+
            CompositionSpriteShape SpriteShape_1()
            {
                // Offset:<0, 512>
                var geometry = PathGeometry_1();
                if (_spriteShape_1 != null) { return _spriteShape_1; }
                var result = _spriteShape_1 = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 0F, 512F), ColorBrush_AlmostLavender_FFEBEBEB());;
                result.CenterPoint = new Vector2(192F, -320F);
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Shape tree root for layer: “”轮廓
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            // Shape tree root for layer: “”轮廓
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(512F, 512F);
                var shapes = result.Shapes;
                // Offset:<0, 512>
                shapes.Add(SpriteShape_0());
                // Offset:<0, 512>
                shapes.Add(SpriteShape_1());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - Shape tree root for layer: “”轮廓
            // Offset:<0, 512>
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), StepThenHoldEasingFunction());
                // Frame 3.
                result.InsertKeyFrame(0.150000006F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.5F, new Vector2(0F, -42F), CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(1F, new Vector2(0F, 0F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Shape tree root for layer: “”轮廓
            // Offset:<0, 512>
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.5F, new Vector2(0F, 30F), CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(1F, new Vector2(0F, 0F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Shape tree root for layer: “”轮廓
            // Offset:<0, 512>
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), StepThenHoldEasingFunction());
                // Frame 3.
                result.InsertKeyFrame(0.150000006F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.5F, new Vector2(1.20000005F, 1.20000005F), CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(1F, new Vector2(1F, 1F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Shape tree root for layer: “”轮廓
            // Offset:<0, 512>
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.5F, new Vector2(0.899999976F, 0.899999976F), CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(1F, new Vector2(1F, 1F), CubicBezierEasingFunction_0());
                return result;
            }

            internal InstalledComponentsIcon_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(512F, 512F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _spriteShape_0.StartAnimation("Scale", ScaleVector2Animation_0(), AnimationController_0());
                _spriteShape_0.StartAnimation("Offset", OffsetVector2Animation_0(), AnimationController_0());
                _spriteShape_1.StartAnimation("Scale", ScaleVector2Animation_1(), AnimationController_0());
                _spriteShape_1.StartAnimation("Offset", OffsetVector2Animation_1(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _spriteShape_0.StopAnimation("Scale");
                _spriteShape_0.StopAnimation("Offset");
                _spriteShape_1.StopAnimation("Scale");
                _spriteShape_1.StopAnimation("Offset");
            }

        }
    }
}
