//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace WE_Tool.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile InvertSelection.json
//       
//       Input file:
//           InvertSelection.json (20127 bytes created 23:08+08:00 Sep 18 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    34 |
// |--------------------------+-------|
// | Expression animators     |     1 |
// | KeyFrame animators       |     3 |
// | Reference parameters     |     1 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     - |
// | CompositionSpriteShapes  |     3 |
// |--------------------------+-------|
// | Brushes                  |     1 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace WE_Tool.AnimatedVisuals
{
    // Name:        InvertSelection
    // Frame rate:  60 fps
    // Frame count: 30
    // Duration:    500.0 mS
    // ____________________________________________________________________________________________
    // |           Marker           |           Constant           | Frame |  mS   |   Progress   |
    // |____________________________|______________________________|_______|_______|______________|
    // | NormalToPointerOver_Start  | M_NormalToPointerOver_Start  |     0 |   0.0 | 0F           |
    // | NormalToPointerOver_End    | M_NormalToPointerOver_End    |     0 |   0.0 | 0F           |
    // | PointerOverToNormal_Start  | M_PointerOverToNormal_Start  |     0 |   0.0 | 0F           |
    // | PointerOverToNormal_End    | M_PointerOverToNormal_End    |     0 |   0.0 | 0F           |
    // | NormalToPressed_Start      | M_NormalToPressed_Start      |     0 |   0.0 | 0F           |
    // | PointerOverToPressed_Start | M_PointerOverToPressed_Start |     0 |   0.0 | 0F           |
    // | PressedToNormal_End        | M_PressedToNormal_End        |     0 |   0.0 | 0F           |
    // | NormalToPlaying_Start      | M_NormalToPlaying_Start      |     0 |   0.0 | 0F           |
    // | PointerOverToPlaying_Start | M_PointerOverToPlaying_Start |     0 |   0.0 | 0F           |
    // | NormalToPressed_End        | M_NormalToPressed_End        |    10 | 166.7 | 0.335000008F |
    // | PointerOverToPressed_End   | M_PointerOverToPressed_End   |    10 | 166.7 | 0.335000008F |
    // | PressedToPointerOver_Start | M_PressedToPointerOver_Start |    10 | 166.7 | 0.335000008F |
    // | PressedToNormal_Start      | M_PressedToNormal_Start      |    10 | 166.7 | 0.335000008F |
    // | PressedToPointerOver_End   | M_PressedToPointerOver_End   |    30 | 500.0 | 1F           |
    // | NormalToPlaying_End        | M_NormalToPlaying_End        |    30 | 500.0 | 1F           |
    // | PointerOverToPlaying_End   | M_PointerOverToPlaying_End   |    30 | 500.0 | 1F           |
    // | PlayingToNormal_Start      | M_PlayingToNormal_Start      |    30 | 500.0 | 1F           |
    // | PlayingToNormal_End        | M_PlayingToNormal_End        |    30 | 500.0 | 1F           |
    // --------------------------------------------------------------------------------------------
    public sealed partial class InvertSelection
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 0.500 seconds.
        internal const long c_durationTicks = 5000000;

        // Marker: NormalToPointerOver_Start.
        internal const float M_NormalToPointerOver_Start = 0F;

        // Marker: NormalToPointerOver_End.
        internal const float M_NormalToPointerOver_End = 0F;

        // Marker: PointerOverToNormal_Start.
        internal const float M_PointerOverToNormal_Start = 0F;

        // Marker: PointerOverToNormal_End.
        internal const float M_PointerOverToNormal_End = 0F;

        // Marker: NormalToPressed_Start.
        internal const float M_NormalToPressed_Start = 0F;

        // Marker: PointerOverToPressed_Start.
        internal const float M_PointerOverToPressed_Start = 0F;

        // Marker: PressedToNormal_End.
        internal const float M_PressedToNormal_End = 0F;

        // Marker: NormalToPlaying_Start.
        internal const float M_NormalToPlaying_Start = 0F;

        // Marker: PointerOverToPlaying_Start.
        internal const float M_PointerOverToPlaying_Start = 0F;

        // Marker: NormalToPressed_End.
        internal const float M_NormalToPressed_End = 0.335000008F;

        // Marker: PointerOverToPressed_End.
        internal const float M_PointerOverToPressed_End = 0.335000008F;

        // Marker: PressedToPointerOver_Start.
        internal const float M_PressedToPointerOver_Start = 0.335000008F;

        // Marker: PressedToNormal_Start.
        internal const float M_PressedToNormal_Start = 0.335000008F;

        // Marker: PressedToPointerOver_End.
        internal const float M_PressedToPointerOver_End = 1F;

        // Marker: NormalToPlaying_End.
        internal const float M_NormalToPlaying_End = 1F;

        // Marker: PointerOverToPlaying_End.
        internal const float M_PointerOverToPlaying_End = 1F;

        // Marker: PlayingToNormal_Start.
        internal const float M_PlayingToNormal_Start = 1F;

        // Marker: PlayingToNormal_End.
        internal const float M_PlayingToNormal_End = 1F;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new InvertSelection_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 30d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(5000000);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 30d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "NormalToPointerOver_Start", 0d },
                { "NormalToPointerOver_End", 0d },
                { "PointerOverToNormal_Start", 0d },
                { "PointerOverToNormal_End", 0d },
                { "NormalToPressed_Start", 0d },
                { "PointerOverToPressed_Start", 0d },
                { "PressedToNormal_End", 0d },
                { "NormalToPlaying_Start", 0d },
                { "PointerOverToPlaying_Start", 0d },
                { "NormalToPressed_End", 0.335 },
                { "PointerOverToPressed_End", 0.335 },
                { "PressedToPointerOver_Start", 0.335 },
                { "PressedToNormal_Start", 0.335 },
                { "PressedToPointerOver_End", 1d },
                { "NormalToPlaying_End", 1d },
                { "PointerOverToPlaying_End", 1d },
                { "PlayingToNormal_Start", 1d },
                { "PlayingToNormal_End", 1d },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed partial class InvertSelection_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 5000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionColorBrush _colorBrush_AlmostLavender_FFEBEBEB;
            CompositionPath _path;
            CompositionPathGeometry _pathGeometry_0;
            CompositionPathGeometry _pathGeometry_1;
            CompositionPathGeometry _pathGeometry_2;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - Layer aggregator
            // - -  Offset:<256, 256>
            // - 路径 2+路径 1.PathGeometry
            CanvasGeometry Geometry_00()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_01(), Geometry_02() },
                    CanvasFilledRegionDetermination.Alternate);
                return result;
            }

            // - - - - Layer aggregator
            // - - -  Offset:<256, 256>
            // - - 路径 2+路径 1.PathGeometry
            CanvasGeometry Geometry_01()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(128.110992F, 80F));
                    builder.AddLine(new Vector2(64.1389999F, 80.1529999F));
                    builder.AddLine(new Vector2(63.8779984F, 15.8249998F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Layer aggregator
            // - - -  Offset:<256, 256>
            // - - 路径 2+路径 1.PathGeometry
            CanvasGeometry Geometry_02()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(106.474998F, 224.076996F));
                    builder.AddLine(new Vector2(210.222F, 120F));
                    builder.AddCubicBezier(new Vector2(210.222F, 120F), new Vector2(245.968994F, 77.0619965F), new Vector2(203.647003F, 33.1780014F));
                    builder.AddCubicBezier(new Vector2(185.875F, 14.75F), new Vector2(152.375F, 12.125F), new Vector2(136.153F, 20.4309998F));
                    builder.AddCubicBezier(new Vector2(110.884003F, 33.3699989F), new Vector2(108.333F, 41.4440002F), new Vector2(97.8339996F, 51.7789993F));
                    builder.AddCubicBezier(new Vector2(86.9300003F, 62.5130005F), new Vector2(64.2959976F, 80.2279968F), new Vector2(64.2959976F, 80.2279968F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_03()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_04(), Geometry_05(), Geometry_06(), Geometry_07(), Geometry_08(), Geometry_09(), Geometry_10(), Geometry_11() },
                    CanvasFilledRegionDetermination.Alternate);
                return result;
            }

            CanvasGeometry Geometry_04()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(160.25F, -64.25F));
                    builder.AddLine(new Vector2(160.222F, -28.2220001F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_05()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(95.9759979F, -223.901993F));
                    builder.AddCubicBezier(new Vector2(95.9759979F, -223.901993F), new Vector2(130.457993F, -225.535995F), new Vector2(138.889008F, -222.069F));
                    builder.AddCubicBezier(new Vector2(156.363007F, -214.882996F), new Vector2(159.645996F, -199.207993F), new Vector2(159.645996F, -199.207993F));
                    builder.AddLine(new Vector2(159.949997F, -159.901001F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_06()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-64.197998F, -224F));
                    builder.AddLine(new Vector2(0F, -224.197998F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_07()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(0F, 0F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_08()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-223.932007F, -159.837006F));
                    builder.AddLine(new Vector2(-223.587997F, -198.813995F));
                    builder.AddCubicBezier(new Vector2(-223.587997F, -198.813995F), new Vector2(-223.860992F, -203.925995F), new Vector2(-216.104996F, -213.214005F));
                    builder.AddCubicBezier(new Vector2(-210.125F, -220.375F), new Vector2(-203.016006F, -223.731003F), new Vector2(-203.016006F, -223.731003F));
                    builder.AddLine(new Vector2(-159.996994F, -224.091995F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_09()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-223.856995F, 0.402999997F));
                    builder.AddLine(new Vector2(-223.850006F, -63.8240013F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_10()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-159.444F, 159.945007F));
                    builder.AddCubicBezier(new Vector2(-159.444F, 159.945007F), new Vector2(-170.998993F, 160.501999F), new Vector2(-189.830994F, 159.763F));
                    builder.AddCubicBezier(new Vector2(-197.339996F, 159.468002F), new Vector2(-206.444F, 158.847F), new Vector2(-211.046005F, 154.514999F));
                    builder.AddCubicBezier(new Vector2(-220.274994F, 145.826004F), new Vector2(-224.125F, 139.75F), new Vector2(-224.156998F, 125.332001F));
                    builder.AddCubicBezier(new Vector2(-224.184006F, 113.371002F), new Vector2(-223.869003F, 95.9240036F), new Vector2(-223.869003F, 95.9240036F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_11()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(0.231000006F, 159.837997F));
                    builder.AddLine(new Vector2(-63.9749985F, 160.052994F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostLavender_FFEBEBEB()
            {
                return (_colorBrush_AlmostLavender_FFEBEBEB == null)
                    ? _colorBrush_AlmostLavender_FFEBEBEB = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xEB, 0xEB, 0xEB))
                    : _colorBrush_AlmostLavender_FFEBEBEB;
            }

            CompositionPath Path()
            {
                if (_path != null) { return _path; }
                var result = _path = new CompositionPath(Geometry_03());
                return result;
            }

            // - Layer aggregator
            // Offset:<256, 256>
            // 路径 2+路径 1.PathGeometry
            CompositionPathGeometry PathGeometry_0()
            {
                if (_pathGeometry_0 != null) { return _pathGeometry_0; }
                var result = _pathGeometry_0 = _c.CreatePathGeometry(new CompositionPath(Geometry_00()));
                return result;
            }

            // - Layer aggregator
            // Offset:<256, 256>
            // 路径 8+路径 7+路径 6+路径 5+路径 4+路径 3+路径 2+路径 1.PathGeometry
            CompositionPathGeometry PathGeometry_1()
            {
                if (_pathGeometry_1 != null) { return _pathGeometry_1; }
                var result = _pathGeometry_1 = _c.CreatePathGeometry(Path());
                return result;
            }

            // - Layer aggregator
            // Offset:<256, 256>
            // 路径 8+路径 7+路径 6+路径 5+路径 4+路径 3+路径 2+路径 1.PathGeometry
            CompositionPathGeometry PathGeometry_2()
            {
                if (_pathGeometry_2 != null) { return _pathGeometry_2; }
                var result = _pathGeometry_2 = _c.CreatePathGeometry(Path());
                return result;
            }

            // Layer aggregator
            // 路径 2+路径 1
            CompositionSpriteShape SpriteShape_0()
            {
                // Offset:<256, 256>
                var result = CreateSpriteShape(PathGeometry_0(), new Matrix3x2(1F, 0F, 0F, 1F, 256F, 256F));;
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // Layer aggregator
            // 路径 8+路径 7+路径 6+路径 5+路径 4+路径 3+路径 2+路径 1
            CompositionSpriteShape SpriteShape_1()
            {
                // Offset:<256, 256>
                var result = CreateSpriteShape(PathGeometry_1(), new Matrix3x2(1F, 0F, 0F, 1F, 256F, 256F));;
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // Layer aggregator
            // 路径 8+路径 7+路径 6+路径 5+路径 4+路径 3+路径 2+路径 1
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<256, 256>
                var result = CreateSpriteShape(PathGeometry_2(), new Matrix3x2(1F, 0F, 0F, 1F, 256F, 256F));;
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            // - - Layer aggregator
            // -  Offset:<256, 256>
            // 路径 8+路径 7+路径 6+路径 5+路径 4+路径 3+路径 2+路径 1.PathGeometry
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_0_to_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 20.
                result.InsertKeyFrame(0.666666687F, 0F, HoldThenStepEasingFunction());
                // Frame 30.
                result.InsertKeyFrame(1F, 1F, CubicBezierEasingFunction_0());
                return result;
            }

            // - - Layer aggregator
            // -  Offset:<256, 256>
            // 路径 2+路径 1.PathGeometry
            // TrimStart
            ScalarKeyFrameAnimation TrimStartScalarAnimation_0_to_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.333333343F, 0.620000005F, CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(1F, 0F, CubicBezierEasingFunction_0());
                return result;
            }

            // - - Layer aggregator
            // -  Offset:<256, 256>
            // 路径 8+路径 7+路径 6+路径 5+路径 4+路径 3+路径 2+路径 1.PathGeometry
            // TrimStart
            ScalarKeyFrameAnimation TrimStartScalarAnimation_0_to_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.333333343F, 0F, HoldThenStepEasingFunction());
                // Frame 20.
                result.InsertKeyFrame(0.666666687F, 1F, CubicBezierEasingFunction_0());
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(512F, 512F);
                var shapes = result.Shapes;
                // Offset:<256, 256>
                shapes.Add(SpriteShape_0());
                // Offset:<256, 256>
                shapes.Add(SpriteShape_1());
                // Offset:<256, 256>
                shapes.Add(SpriteShape_2());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            internal InvertSelection_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(512F, 512F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _pathGeometry_0.StartAnimation("TrimStart", TrimStartScalarAnimation_0_to_0(), AnimationController_0());
                _pathGeometry_1.StartAnimation("TrimStart", TrimStartScalarAnimation_0_to_1(), AnimationController_0());
                _pathGeometry_2.StartAnimation("TrimEnd", TrimEndScalarAnimation_0_to_1(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _pathGeometry_0.StopAnimation("TrimStart");
                _pathGeometry_1.StopAnimation("TrimStart");
                _pathGeometry_2.StopAnimation("TrimEnd");
            }

        }
    }
}
