//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace WE_Tool.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile OpenDirectoryIcon.json
//       
//       Input file:
//           OpenDirectoryIcon.json (10055 bytes created 22:23+08:00 Sep 18 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    26 |
// |--------------------------+-------|
// | Expression animators     |     1 |
// | KeyFrame animators       |     2 |
// | Reference parameters     |     1 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     - |
// | CompositionSpriteShapes  |     2 |
// |--------------------------+-------|
// | Brushes                  |     1 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace WE_Tool.AnimatedVisuals
{
    // Name:        OpenDirectory
    // Frame rate:  60 fps
    // Frame count: 20
    // Duration:    333.3 mS
    // ____________________________________________________________________________________________
    // |           Marker           |           Constant           | Frame |  mS   |   Progress   |
    // |____________________________|______________________________|_______|_______|______________|
    // | NormalToPointerOver_Start  | M_NormalToPointerOver_Start  |     0 |   0.0 | 0F           |
    // | NormalToPointerOver_End    | M_NormalToPointerOver_End    |     0 |   0.0 | 0F           |
    // | PointerOverToNormal_Start  | M_PointerOverToNormal_Start  |     0 |   0.0 | 0F           |
    // | PointerOverToNormal_End    | M_PointerOverToNormal_End    |     0 |   0.0 | 0F           |
    // | NormalToPressed_Start      | M_NormalToPressed_Start      |     0 |   0.0 | 0F           |
    // | PressedToNormal_End        | M_PressedToNormal_End        |     0 |   0.0 | 0F           |
    // | PointerOverToPressed_Start | M_PointerOverToPressed_Start |     0 |   0.0 | 0F           |
    // | NormalToPlaying_Start      | M_NormalToPlaying_Start      |     0 |   0.0 | 0F           |
    // | NormalToPressed_End        | M_NormalToPressed_End        |    10 | 166.7 | 0.502499998F |
    // | PressedToNormal_Start      | M_PressedToNormal_Start      |    10 | 166.7 | 0.502499998F |
    // | PointerOverToPressed_End   | M_PointerOverToPressed_End   |    10 | 166.7 | 0.502499998F |
    // | PressedToPointerOver_Start | M_PressedToPointerOver_Start |    10 | 166.7 | 0.502499998F |
    // | PressedToPointerOver_End   | M_PressedToPointerOver_End   |    20 | 333.3 | 1F           |
    // | NormalToPlaying_End        | M_NormalToPlaying_End        |    20 | 333.3 | 1F           |
    // | PlayingToNormal_Start      | M_PlayingToNormal_Start      |    20 | 333.3 | 1F           |
    // | PlayingToNormal_End        | M_PlayingToNormal_End        |    20 | 333.3 | 1F           |
    // --------------------------------------------------------------------------------------------
    public sealed class OpenDirectoryIcon
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 0.333 seconds.
        internal const long c_durationTicks = 3333333;

        // Marker: NormalToPointerOver_Start.
        internal const float M_NormalToPointerOver_Start = 0F;

        // Marker: NormalToPointerOver_End.
        internal const float M_NormalToPointerOver_End = 0F;

        // Marker: PointerOverToNormal_Start.
        internal const float M_PointerOverToNormal_Start = 0F;

        // Marker: PointerOverToNormal_End.
        internal const float M_PointerOverToNormal_End = 0F;

        // Marker: NormalToPressed_Start.
        internal const float M_NormalToPressed_Start = 0F;

        // Marker: PressedToNormal_End.
        internal const float M_PressedToNormal_End = 0F;

        // Marker: PointerOverToPressed_Start.
        internal const float M_PointerOverToPressed_Start = 0F;

        // Marker: NormalToPlaying_Start.
        internal const float M_NormalToPlaying_Start = 0F;

        // Marker: NormalToPressed_End.
        internal const float M_NormalToPressed_End = 0.502499998F;

        // Marker: PressedToNormal_Start.
        internal const float M_PressedToNormal_Start = 0.502499998F;

        // Marker: PointerOverToPressed_End.
        internal const float M_PointerOverToPressed_End = 0.502499998F;

        // Marker: PressedToPointerOver_Start.
        internal const float M_PressedToPointerOver_Start = 0.502499998F;

        // Marker: PressedToPointerOver_End.
        internal const float M_PressedToPointerOver_End = 1F;

        // Marker: NormalToPlaying_End.
        internal const float M_NormalToPlaying_End = 1F;

        // Marker: PlayingToNormal_Start.
        internal const float M_PlayingToNormal_Start = 1F;

        // Marker: PlayingToNormal_End.
        internal const float M_PlayingToNormal_End = 1F;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new OpenDirectoryIcon_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 20d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(3333333);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 20d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "NormalToPointerOver_Start", 0d },
                { "NormalToPointerOver_End", 0d },
                { "PointerOverToNormal_Start", 0d },
                { "PointerOverToNormal_End", 0d },
                { "NormalToPressed_Start", 0d },
                { "PressedToNormal_End", 0d },
                { "PointerOverToPressed_Start", 0d },
                { "NormalToPlaying_Start", 0d },
                { "NormalToPressed_End", 0.5025 },
                { "PressedToNormal_Start", 0.5025 },
                { "PointerOverToPressed_End", 0.5025 },
                { "PressedToPointerOver_Start", 0.5025 },
                { "PressedToPointerOver_End", 1d },
                { "NormalToPlaying_End", 1d },
                { "PlayingToNormal_Start", 1d },
                { "PlayingToNormal_End", 1d },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class OpenDirectoryIcon_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 3333333;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionColorBrush _colorBrush_AlmostLavender_FFEBEBEB;
            CompositionPathGeometry _pathGeometry_0;
            CompositionSpriteShape _spriteShape_1;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            StepEasingFunction _holdThenStepEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - Layer aggregator
            // - -  Offset:<256, 256>
            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-186.832993F, -206.738998F));
                    builder.AddCubicBezier(new Vector2(-196.498001F, -205.953995F), new Vector2(-216.013F, -192.796997F), new Vector2(-222.707001F, -183.619003F));
                    builder.AddCubicBezier(new Vector2(-231F, -172.25F), new Vector2(-235.25F, -159.375F), new Vector2(-235.675995F, -154.033997F));
                    builder.AddCubicBezier(new Vector2(-236.016998F, -149.759995F), new Vector2(-235.705994F, 154.220001F), new Vector2(-235.705994F, 154.220001F));
                    builder.AddCubicBezier(new Vector2(-235.705994F, 154.220001F), new Vector2(-232.873993F, 172.003006F), new Vector2(-221.959F, 184.686996F));
                    builder.AddCubicBezier(new Vector2(-204.113998F, 205.423996F), new Vector2(-179.725998F, 208.065994F), new Vector2(-179.725998F, 208.065994F));
                    builder.AddLine(new Vector2(156.921997F, 208.171997F));
                    builder.AddCubicBezier(new Vector2(156.921997F, 208.171997F), new Vector2(182.690002F, 200.878006F), new Vector2(192.238998F, 190.584F));
                    builder.AddCubicBezier(new Vector2(198.916F, 183.386993F), new Vector2(205.481995F, 173.964996F), new Vector2(206F, 164F));
                    builder.AddCubicBezier(new Vector2(210.587997F, 75.7440033F), new Vector2(211.753006F, -82.5240021F), new Vector2(211.619003F, -88.4800034F));
                    builder.AddCubicBezier(new Vector2(211.300995F, -102.591003F), new Vector2(198.735001F, -121.027F), new Vector2(187.727997F, -129.863998F));
                    builder.AddCubicBezier(new Vector2(180.082993F, -136.001999F), new Vector2(164.078003F, -143.494995F), new Vector2(154.276993F, -143.723007F));
                    builder.AddCubicBezier(new Vector2(106.261002F, -144.839996F), new Vector2(3.58100009F, -144.074005F), new Vector2(3.58100009F, -144.074005F));
                    builder.AddCubicBezier(new Vector2(3.58100009F, -144.074005F), new Vector2(-14.1110001F, -167.496002F), new Vector2(-21.5930004F, -177.988007F));
                    builder.AddCubicBezier(new Vector2(-36.9389992F, -199.507004F), new Vector2(-56.1640015F, -207.903F), new Vector2(-68.1790009F, -207.878998F));
                    builder.AddCubicBezier(new Vector2(-77.8669968F, -207.858994F), new Vector2(-155.973999F, -209.246994F), new Vector2(-186.832993F, -206.738998F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - Layer aggregator
            // - - 路径 1
            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-122.863998F, -79.802002F));
                    builder.AddCubicBezier(new Vector2(-122.863998F, -79.802002F), new Vector2(-138.003006F, -77.5329971F), new Vector2(-147.608994F, -69.6969986F));
                    builder.AddCubicBezier(new Vector2(-158.766006F, -60.5960007F), new Vector2(-162.567993F, -47.012001F), new Vector2(-162.962997F, -46.6170006F));
                    builder.AddCubicBezier(new Vector2(-163.276993F, -46.3030014F), new Vector2(-196.009003F, 114.315002F), new Vector2(-209.725998F, 180.462006F));
                    builder.AddCubicBezier(new Vector2(-213.285004F, 197.623001F), new Vector2(-211.042007F, 196.578003F), new Vector2(-205.160004F, 199.906006F));
                    builder.AddCubicBezier(new Vector2(-199.25F, 203.25F), new Vector2(-184.410004F, 207.660004F), new Vector2(-184.410004F, 207.660004F));
                    builder.AddLine(new Vector2(156.598999F, 207.888F));
                    builder.AddCubicBezier(new Vector2(156.598999F, 207.888F), new Vector2(172.889008F, 208.888F), new Vector2(194.908005F, 186.949997F));
                    builder.AddCubicBezier(new Vector2(212.214005F, 169.707001F), new Vector2(211.781998F, 149.432007F), new Vector2(211.781998F, 149.432007F));
                    builder.AddLine(new Vector2(236.873993F, -33.0359993F));
                    builder.AddCubicBezier(new Vector2(236.873993F, -33.0359993F), new Vector2(235.186996F, -51.2900009F), new Vector2(227.020996F, -60.9710007F));
                    builder.AddCubicBezier(new Vector2(213.5F, -77F), new Vector2(197.404999F, -79.5879974F), new Vector2(197.404999F, -79.5879974F));
                    builder.AddLine(new Vector2(-122.863998F, -79.802002F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostLavender_FFEBEBEB()
            {
                return (_colorBrush_AlmostLavender_FFEBEBEB == null)
                    ? _colorBrush_AlmostLavender_FFEBEBEB = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xEB, 0xEB, 0xEB))
                    : _colorBrush_AlmostLavender_FFEBEBEB;
            }

            // - Layer aggregator
            // Offset:<256, 256>
            CompositionPathGeometry PathGeometry_0()
            {
                if (_pathGeometry_0 != null) { return _pathGeometry_0; }
                var result = _pathGeometry_0 = _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
                result.TrimEnd = 0.930000007F;
                result.TrimOffset = -0.375F;
                return result;
            }

            // - Layer aggregator
            // 路径 1
            CompositionPathGeometry PathGeometry_1()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_1()));
            }

            // Layer aggregator
            // 路径 1
            CompositionSpriteShape SpriteShape_0()
            {
                // Offset:<256, 256>
                var result = CreateSpriteShape(PathGeometry_0(), new Matrix3x2(1F, 0F, 0F, 1F, 256F, 256F));;
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // Layer aggregator
            // 路径 1
            CompositionSpriteShape SpriteShape_1()
            {
                if (_spriteShape_1 != null) { return _spriteShape_1; }
                var result = _spriteShape_1 = _c.CreateSpriteShape(PathGeometry_1());
                result.CenterPoint = new Vector2(-200F, 196.046005F);
                result.Offset = new Vector2(257.721008F, 255.999985F);
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            // - - Layer aggregator
            // -  Offset:<256, 256>
            // TrimStart
            ScalarKeyFrameAnimation TrimStartScalarAnimation_0p08_to_0p08()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0.0799999982F, HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.5F, 0F, CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(1F, 0.0799999982F, CubicBezierEasingFunction_0());
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(512F, 512F);
                var shapes = result.Shapes;
                // Offset:<256, 256>
                shapes.Add(SpriteShape_0());
                // 路径 1
                shapes.Add(SpriteShape_1());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            // - Layer aggregator
            // 路径 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.5F, new Vector2(0.980000019F, 0.529999971F), CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(1F, new Vector2(1F, 1F), CubicBezierEasingFunction_0());
                return result;
            }

            internal OpenDirectoryIcon_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(512F, 512F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _pathGeometry_0.StartAnimation("TrimStart", TrimStartScalarAnimation_0p08_to_0p08(), AnimationController_0());
                _spriteShape_1.StartAnimation("Scale", ScaleVector2Animation(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _pathGeometry_0.StopAnimation("TrimStart");
                _spriteShape_1.StopAnimation("Scale");
            }

        }
    }
}
