//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace WE_Tool.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile PropertiesIcon.json
//       
//       Input file:
//           PropertiesIcon.json (8035 bytes created 22:23+08:00 Sep 18 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    24 |
// |--------------------------+-------|
// | Expression animators     |     1 |
// | KeyFrame animators       |     2 |
// | Reference parameters     |     1 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     - |
// | CompositionSpriteShapes  |     1 |
// |--------------------------+-------|
// | Brushes                  |     1 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace WE_Tool.AnimatedVisuals
{
    // Name:        Properties
    // Frame rate:  60 fps
    // Frame count: 20
    // Duration:    333.3 mS
    // ____________________________________________________________________________________________
    // |           Marker           |           Constant           | Frame |  mS   |   Progress   |
    // |____________________________|______________________________|_______|_______|______________|
    // | NormalToPointerOver_Start  | M_NormalToPointerOver_Start  |     0 |   0.0 | 0F           |
    // | NormalToPointerOver_End    | M_NormalToPointerOver_End    |     0 |   0.0 | 0F           |
    // | PointerOverToNormal_Start  | M_PointerOverToNormal_Start  |     0 |   0.0 | 0F           |
    // | PointerOverToNormal_End    | M_PointerOverToNormal_End    |     0 |   0.0 | 0F           |
    // | NormalToPressed_Start      | M_NormalToPressed_Start      |     0 |   0.0 | 0F           |
    // | PressedToNormal_End        | M_PressedToNormal_End        |     0 |   0.0 | 0F           |
    // | PointerOverToPressed_Start | M_PointerOverToPressed_Start |     0 |   0.0 | 0F           |
    // | NormalToPlaying_Start      | M_NormalToPlaying_Start      |     0 |   0.0 | 0F           |
    // | NormalToPressed_End        | M_NormalToPressed_End        |    10 | 166.7 | 0.502499998F |
    // | PressedToNormal_Start      | M_PressedToNormal_Start      |    10 | 166.7 | 0.502499998F |
    // | PointerOverToPressed_End   | M_PointerOverToPressed_End   |    10 | 166.7 | 0.502499998F |
    // | PressedToPointerOver_Start | M_PressedToPointerOver_Start |    10 | 166.7 | 0.502499998F |
    // | PressedToPointerOver_End   | M_PressedToPointerOver_End   |    20 | 333.3 | 1F           |
    // | NormalToPlaying_End        | M_NormalToPlaying_End        |    20 | 333.3 | 1F           |
    // | PlayingToNormal_Start      | M_PlayingToNormal_Start      |    20 | 333.3 | 1F           |
    // | PlayingToNormal_End        | M_PlayingToNormal_End        |    20 | 333.3 | 1F           |
    // --------------------------------------------------------------------------------------------
    public sealed partial class PropertiesIcon
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 0.333 seconds.
        internal const long c_durationTicks = 3333333;

        // Marker: NormalToPointerOver_Start.
        internal const float M_NormalToPointerOver_Start = 0F;

        // Marker: NormalToPointerOver_End.
        internal const float M_NormalToPointerOver_End = 0F;

        // Marker: PointerOverToNormal_Start.
        internal const float M_PointerOverToNormal_Start = 0F;

        // Marker: PointerOverToNormal_End.
        internal const float M_PointerOverToNormal_End = 0F;

        // Marker: NormalToPressed_Start.
        internal const float M_NormalToPressed_Start = 0F;

        // Marker: PressedToNormal_End.
        internal const float M_PressedToNormal_End = 0F;

        // Marker: PointerOverToPressed_Start.
        internal const float M_PointerOverToPressed_Start = 0F;

        // Marker: NormalToPlaying_Start.
        internal const float M_NormalToPlaying_Start = 0F;

        // Marker: NormalToPressed_End.
        internal const float M_NormalToPressed_End = 0.502499998F;

        // Marker: PressedToNormal_Start.
        internal const float M_PressedToNormal_Start = 0.502499998F;

        // Marker: PointerOverToPressed_End.
        internal const float M_PointerOverToPressed_End = 0.502499998F;

        // Marker: PressedToPointerOver_Start.
        internal const float M_PressedToPointerOver_Start = 0.502499998F;

        // Marker: PressedToPointerOver_End.
        internal const float M_PressedToPointerOver_End = 1F;

        // Marker: NormalToPlaying_End.
        internal const float M_NormalToPlaying_End = 1F;

        // Marker: PlayingToNormal_Start.
        internal const float M_PlayingToNormal_Start = 1F;

        // Marker: PlayingToNormal_End.
        internal const float M_PlayingToNormal_End = 1F;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new PropertiesIcon_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 20d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(3333333);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 20d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "NormalToPointerOver_Start", 0d },
                { "NormalToPointerOver_End", 0d },
                { "PointerOverToNormal_Start", 0d },
                { "PointerOverToNormal_End", 0d },
                { "NormalToPressed_Start", 0d },
                { "PressedToNormal_End", 0d },
                { "PointerOverToPressed_Start", 0d },
                { "NormalToPlaying_Start", 0d },
                { "NormalToPressed_End", 0.5025 },
                { "PressedToNormal_Start", 0.5025 },
                { "PointerOverToPressed_End", 0.5025 },
                { "PressedToPointerOver_Start", 0.5025 },
                { "PressedToPointerOver_End", 1d },
                { "NormalToPlaying_End", 1d },
                { "PlayingToNormal_Start", 1d },
                { "PlayingToNormal_End", 1d },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed partial class PropertiesIcon_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 3333333;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionSpriteShape _spriteShape;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            StepEasingFunction _holdThenStepEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - Shape tree root for layer: 形状图层 1
            // - - 路径 2+路径 1
            // - 路径 2+路径 1.PathGeometry
            CanvasGeometry Geometry_0()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_1(), Geometry_2() },
                    CanvasFilledRegionDetermination.Alternate);
                return result;
            }

            // - - - - Shape tree root for layer: 形状图层 1
            // - - - 路径 2+路径 1
            // - - 路径 2+路径 1.PathGeometry
            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(160.093002F, -223.848999F));
                    builder.AddCubicBezier(new Vector2(160.093002F, -223.848999F), new Vector2(64.6849976F, -129.498001F), new Vector2(64.2630005F, -128.020004F));
                    builder.AddCubicBezier(new Vector2(64.1070023F, -127.084F), new Vector2(128.565002F, -64.9649963F), new Vector2(127.628998F, -64.0289993F));
                    builder.AddCubicBezier(new Vector2(126.693001F, -63.0929985F), new Vector2(223.770996F, -159.858994F), new Vector2(223.770996F, -159.858994F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: 形状图层 1
            // - - - 路径 2+路径 1
            // - - 路径 2+路径 1.PathGeometry
            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(160.304993F, -223.701004F));
                    builder.AddCubicBezier(new Vector2(133.556F, -242F), new Vector2(78.9749985F, -246.720993F), new Vector2(37.9259987F, -228.257996F));
                    builder.AddCubicBezier(new Vector2(-3.16100001F, -209.778F), new Vector2(-18.7630005F, -184.449005F), new Vector2(-33.4440002F, -158.828995F));
                    builder.AddCubicBezier(new Vector2(-43.0050011F, -142.145996F), new Vector2(-55.7779999F, -93.9410019F), new Vector2(-41.5999985F, -58.2669983F));
                    builder.AddCubicBezier(new Vector2(-39.5349998F, -53.0699997F), new Vector2(-46.1769981F, -50.2919998F), new Vector2(-46.1769981F, -50.2919998F));
                    builder.AddLine(new Vector2(-224.992996F, 128.843002F));
                    builder.AddCubicBezier(new Vector2(-224.992996F, 128.843002F), new Vector2(-240.309998F, 146.867004F), new Vector2(-239.837997F, 171.365005F));
                    builder.AddCubicBezier(new Vector2(-239.352005F, 196.544998F), new Vector2(-230.875F, 207.959F), new Vector2(-219.444F, 220.684006F));
                    builder.AddCubicBezier(new Vector2(-207.591003F, 233.878998F), new Vector2(-188.119995F, 238.287994F), new Vector2(-172.621994F, 239.828995F));
                    builder.AddCubicBezier(new Vector2(-147.511002F, 242.326004F), new Vector2(-123.441002F, 219.574005F), new Vector2(-123.441002F, 219.574005F));
                    builder.AddLine(new Vector2(54.5369987F, 41.7369995F));
                    builder.AddCubicBezier(new Vector2(54.5369987F, 41.7369995F), new Vector2(56.75F, 41F), new Vector2(65.2649994F, 43.6860008F));
                    builder.AddCubicBezier(new Vector2(75.9710007F, 47.0629997F), new Vector2(90.5910034F, 48.6609993F), new Vector2(100.238998F, 48.007F));
                    builder.AddCubicBezier(new Vector2(127.873001F, 46.1329994F), new Vector2(159.078003F, 38.2770004F), new Vector2(188.186005F, 14.5539999F));
                    builder.AddCubicBezier(new Vector2(208.522995F, -2.02099991F), new Vector2(225.018997F, -22.2019997F), new Vector2(235.671005F, -61.1030006F));
                    builder.AddCubicBezier(new Vector2(242.309998F, -85.3499985F), new Vector2(242F, -131.776993F), new Vector2(224.421997F, -159.897995F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - Shape tree root for layer: 形状图层 1
            // 路径 2+路径 1
            CompositionColorBrush ColorBrush_AlmostLavender_FFEBEBEB()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0xEB, 0xEB, 0xEB));
            }

            // - Shape tree root for layer: 形状图层 1
            // 路径 2+路径 1
            // 路径 2+路径 1.PathGeometry
            CompositionPathGeometry PathGeometry()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
            }

            // Shape tree root for layer: 形状图层 1
            // 路径 2+路径 1
            CompositionSpriteShape SpriteShape()
            {
                if (_spriteShape != null) { return _spriteShape; }
                var result = _spriteShape = _c.CreateSpriteShape(PathGeometry());
                result.Offset = new Vector2(256F, 256F);
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Shape tree root for layer: 形状图层 1
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F))
                    : _cubicBezierEasingFunction_0;
            }

            // - Shape tree root for layer: 形状图层 1
            // 路径 2+路径 1
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 5.
                result.InsertKeyFrame(0.25F, 0F, HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.5F, -110F, CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(1F, 0F, CubicBezierEasingFunction_0());
                return result;
            }

            // Shape tree root for layer: 形状图层 1
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(512F, 512F);
                // 路径 2+路径 1
                result.Shapes.Add(SpriteShape());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            // - - Shape tree root for layer: 形状图层 1
            // - 路径 2+路径 1
            // RotationAngleInDegrees
            StepEasingFunction StepThenHoldEasingFunction()
            {
                var result = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - Shape tree root for layer: 形状图层 1
            // 路径 2+路径 1
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                // Frame 5.
                result.InsertKeyFrame(0.25F, new Vector2(0.75F, 0.75F), CubicBezierEasingFunction_0());
                // Frame 16.
                result.InsertKeyFrame(0.800000012F, new Vector2(0.75F, 0.75F), CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(1F, new Vector2(1F, 1F), CubicBezierEasingFunction_0());
                return result;
            }

            internal PropertiesIcon_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(512F, 512F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _spriteShape.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_0(), AnimationController_0());
                _spriteShape.StartAnimation("Scale", ScaleVector2Animation(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _spriteShape.StopAnimation("RotationAngleInDegrees");
                _spriteShape.StopAnimation("Scale");
            }

        }
    }
}
