//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace WE_Tool.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile RefreshIcon.json
//       
//       Input file:
//           RefreshIcon.json (4135 bytes created 22:56+08:00 Sep 14 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    22 |
// |--------------------------+-------|
// | Expression animators     |     1 |
// | KeyFrame animators       |     1 |
// | Reference parameters     |     1 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     - |
// | CompositionSpriteShapes  |     1 |
// |--------------------------+-------|
// | Brushes                  |     2 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace WE_Tool.AnimatedVisuals
{
    // Name:        Refresh
    // Frame rate:  60 fps
    // Frame count: 60
    // Duration:    1000.0 mS
    // _______________________________________________________________________________
    // |        Marker         |        Constant         | Frame |   mS   | Progress |
    // |_______________________|_________________________|_______|________|__________|
    // | NormalToPlaying_Start | M_NormalToPlaying_Start |     0 |    0.0 | 0F       |
    // | NormalToPlaying_End   | M_NormalToPlaying_End   |    60 | 1000.0 | 1F       |
    // | PlayingToNormal_Start | M_PlayingToNormal_Start |    60 | 1000.0 | 1F       |
    // | PlayingToNormal_End   | M_PlayingToNormal_End   |    60 | 1000.0 | 1F       |
    // -------------------------------------------------------------------------------
    public sealed class RefreshIcon
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 1.000 seconds.
        internal const long c_durationTicks = 10000000;

        // Marker: NormalToPlaying_Start.
        internal const float M_NormalToPlaying_Start = 0F;

        // Marker: NormalToPlaying_End.
        internal const float M_NormalToPlaying_End = 1F;

        // Marker: PlayingToNormal_Start.
        internal const float M_PlayingToNormal_Start = 1F;

        // Marker: PlayingToNormal_End.
        internal const float M_PlayingToNormal_End = 1F;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new RefreshIcon_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 60d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(10000000);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 60d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "NormalToPlaying_Start", 0d },
                { "NormalToPlaying_End", 1d },
                { "PlayingToNormal_Start", 1d },
                { "PlayingToNormal_End", 1d },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class RefreshIcon_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 10000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionSpriteShape _spriteShape;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            // - Shape tree root for layer: “”轮廓
            // 
            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - Shape tree root for layer: “”轮廓
            // - - 
            CanvasGeometry Geometry()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(502.875F, -324F));
                    builder.AddCubicBezier(new Vector2(496.789001F, -345.832001F), new Vector2(488.207001F, -366.25F), new Vector2(477.125F, -385.25F));
                    builder.AddCubicBezier(new Vector2(466.039001F, -404.25F), new Vector2(452.707001F, -421.539001F), new Vector2(437.125F, -437.125F));
                    builder.AddCubicBezier(new Vector2(421.539001F, -452.707001F), new Vector2(404.25F, -466.039001F), new Vector2(385.25F, -477.125F));
                    builder.AddCubicBezier(new Vector2(366.25F, -488.207001F), new Vector2(345.832001F, -496.789001F), new Vector2(324F, -502.875F));
                    builder.AddCubicBezier(new Vector2(302.164001F, -508.957001F), new Vector2(279.5F, -512F), new Vector2(256F, -512F));
                    builder.AddCubicBezier(new Vector2(237.5F, -512F), new Vector2(219.414001F, -510.039001F), new Vector2(201.75F, -506.125F));
                    builder.AddCubicBezier(new Vector2(184.082001F, -502.207001F), new Vector2(167.082001F, -496.582001F), new Vector2(150.75F, -489.25F));
                    builder.AddCubicBezier(new Vector2(134.414001F, -481.914001F), new Vector2(118.914001F, -472.832001F), new Vector2(104.25F, -462F));
                    builder.AddCubicBezier(new Vector2(89.5820007F, -451.164001F), new Vector2(76.1640015F, -438.914001F), new Vector2(64F, -425.25F));
                    builder.AddLine(new Vector2(64F, -496F));
                    builder.AddCubicBezier(new Vector2(64F, -500.332001F), new Vector2(62.4140015F, -504.082001F), new Vector2(59.25F, -507.25F));
                    builder.AddCubicBezier(new Vector2(56.0820007F, -510.414001F), new Vector2(52.3320007F, -512F), new Vector2(48F, -512F));
                    builder.AddCubicBezier(new Vector2(43.6640015F, -512F), new Vector2(39.9140015F, -510.414001F), new Vector2(36.75F, -507.25F));
                    builder.AddCubicBezier(new Vector2(33.5820007F, -504.082001F), new Vector2(32F, -500.332001F), new Vector2(32F, -496F));
                    builder.AddLine(new Vector2(32F, -465.75F));
                    builder.AddLine(new Vector2(31.75F, -405.75F));
                    builder.AddLine(new Vector2(31.75F, -375.5F));
                    builder.AddCubicBezier(new Vector2(31.75F, -372.664001F), new Vector2(31.9139996F, -369.875F), new Vector2(32.25F, -367.125F));
                    builder.AddCubicBezier(new Vector2(32.5820007F, -364.375F), new Vector2(33.3320007F, -361.875F), new Vector2(34.5F, -359.625F));
                    builder.AddCubicBezier(new Vector2(35.6640015F, -357.375F), new Vector2(37.3320007F, -355.539001F), new Vector2(39.5F, -354.125F));
                    builder.AddCubicBezier(new Vector2(41.6640015F, -352.707001F), new Vector2(44.5F, -352F), new Vector2(48F, -352F));
                    builder.AddLine(new Vector2(176F, -352F));
                    builder.AddCubicBezier(new Vector2(180.332001F, -352F), new Vector2(184.082001F, -353.582001F), new Vector2(187.25F, -356.75F));
                    builder.AddCubicBezier(new Vector2(190.414001F, -359.914001F), new Vector2(192F, -363.664001F), new Vector2(192F, -368F));
                    builder.AddCubicBezier(new Vector2(192F, -372.332001F), new Vector2(190.414001F, -376.082001F), new Vector2(187.25F, -379.25F));
                    builder.AddCubicBezier(new Vector2(184.082001F, -382.414001F), new Vector2(180.332001F, -384F), new Vector2(176F, -384F));
                    builder.AddLine(new Vector2(72.25F, -384F));
                    builder.AddCubicBezier(new Vector2(82.75F, -399F), new Vector2(94.7890015F, -412.414001F), new Vector2(108.375F, -424.25F));
                    builder.AddCubicBezier(new Vector2(121.957001F, -436.082001F), new Vector2(136.625F, -446.125F), new Vector2(152.375F, -454.375F));
                    builder.AddCubicBezier(new Vector2(168.125F, -462.625F), new Vector2(184.75F, -468.957001F), new Vector2(202.25F, -473.375F));
                    builder.AddCubicBezier(new Vector2(219.75F, -477.789001F), new Vector2(237.664001F, -480F), new Vector2(256F, -480F));
                    builder.AddCubicBezier(new Vector2(276.5F, -480F), new Vector2(296.289001F, -477.332001F), new Vector2(315.375F, -472F));
                    builder.AddCubicBezier(new Vector2(334.457001F, -466.664001F), new Vector2(352.289001F, -459.125F), new Vector2(368.875F, -449.375F));
                    builder.AddCubicBezier(new Vector2(385.457001F, -439.625F), new Vector2(400.582001F, -427.914001F), new Vector2(414.25F, -414.25F));
                    builder.AddCubicBezier(new Vector2(427.914001F, -400.582001F), new Vector2(439.625F, -385.457001F), new Vector2(449.375F, -368.875F));
                    builder.AddCubicBezier(new Vector2(459.125F, -352.289001F), new Vector2(466.664001F, -334.457001F), new Vector2(472F, -315.375F));
                    builder.AddCubicBezier(new Vector2(477.332001F, -296.289001F), new Vector2(480F, -276.5F), new Vector2(480F, -256F));
                    builder.AddCubicBezier(new Vector2(480F, -235.332001F), new Vector2(477.332001F, -215.457001F), new Vector2(472F, -196.375F));
                    builder.AddCubicBezier(new Vector2(466.664001F, -177.289001F), new Vector2(459.125F, -159.457001F), new Vector2(449.375F, -142.875F));
                    builder.AddCubicBezier(new Vector2(439.625F, -126.289001F), new Vector2(427.957001F, -111.207001F), new Vector2(414.375F, -97.625F));
                    builder.AddCubicBezier(new Vector2(400.789001F, -84.0390015F), new Vector2(385.707001F, -72.375F), new Vector2(369.125F, -62.625F));
                    builder.AddCubicBezier(new Vector2(352.539001F, -52.875F), new Vector2(334.707001F, -45.3320007F), new Vector2(315.625F, -40F));
                    builder.AddCubicBezier(new Vector2(296.539001F, -34.6640015F), new Vector2(276.664001F, -32F), new Vector2(256F, -32F));
                    builder.AddCubicBezier(new Vector2(236F, -32F), new Vector2(216.539001F, -34.5390015F), new Vector2(197.625F, -39.625F));
                    builder.AddCubicBezier(new Vector2(178.707001F, -44.7070007F), new Vector2(160.914001F, -52.0820007F), new Vector2(144.25F, -61.75F));
                    builder.AddCubicBezier(new Vector2(127.582001F, -71.4140015F), new Vector2(112.25F, -83.125F), new Vector2(98.25F, -96.875F));
                    builder.AddCubicBezier(new Vector2(84.25F, -110.625F), new Vector2(72.1640015F, -126.164001F), new Vector2(62F, -143.5F));
                    builder.AddCubicBezier(new Vector2(51.8320007F, -160.664001F), new Vector2(44.2890015F, -178.707001F), new Vector2(39.375F, -197.625F));
                    builder.AddCubicBezier(new Vector2(34.4570007F, -216.539001F), new Vector2(32F, -236F), new Vector2(32F, -256F));
                    builder.AddCubicBezier(new Vector2(32F, -260.332001F), new Vector2(30.4139996F, -264.082001F), new Vector2(27.25F, -267.25F));
                    builder.AddCubicBezier(new Vector2(24.0820007F, -270.414001F), new Vector2(20.3320007F, -272F), new Vector2(16F, -272F));
                    builder.AddCubicBezier(new Vector2(11.6639996F, -272F), new Vector2(7.91400003F, -270.414001F), new Vector2(4.75F, -267.25F));
                    builder.AddCubicBezier(new Vector2(1.58200002F, -264.082001F), new Vector2(0F, -260.332001F), new Vector2(0F, -256F));
                    builder.AddCubicBezier(new Vector2(0F, -232.332001F), new Vector2(3.03900003F, -209.582001F), new Vector2(9.125F, -187.75F));
                    builder.AddCubicBezier(new Vector2(15.2069998F, -165.914001F), new Vector2(23.7889996F, -145.5F), new Vector2(34.875F, -126.5F));
                    builder.AddCubicBezier(new Vector2(45.9570007F, -107.5F), new Vector2(59.25F, -90.25F), new Vector2(74.75F, -74.75F));
                    builder.AddCubicBezier(new Vector2(90.25F, -59.25F), new Vector2(107.5F, -45.9570007F), new Vector2(126.5F, -34.875F));
                    builder.AddCubicBezier(new Vector2(145.5F, -23.7889996F), new Vector2(165.914001F, -15.2069998F), new Vector2(187.75F, -9.125F));
                    builder.AddCubicBezier(new Vector2(209.582001F, -3.03900003F), new Vector2(232.332001F, 0F), new Vector2(256F, 0F));
                    builder.AddCubicBezier(new Vector2(279.664001F, 0F), new Vector2(302.414001F, -3.03900003F), new Vector2(324.25F, -9.125F));
                    builder.AddCubicBezier(new Vector2(346.082001F, -15.2069998F), new Vector2(366.457001F, -23.7889996F), new Vector2(385.375F, -34.875F));
                    builder.AddCubicBezier(new Vector2(404.289001F, -45.9570007F), new Vector2(421.539001F, -59.2890015F), new Vector2(437.125F, -74.875F));
                    builder.AddCubicBezier(new Vector2(452.707001F, -90.4570007F), new Vector2(466.039001F, -107.707001F), new Vector2(477.125F, -126.625F));
                    builder.AddCubicBezier(new Vector2(488.207001F, -145.539001F), new Vector2(496.789001F, -165.914001F), new Vector2(502.875F, -187.75F));
                    builder.AddCubicBezier(new Vector2(508.957001F, -209.582001F), new Vector2(512F, -232.332001F), new Vector2(512F, -256F));
                    builder.AddCubicBezier(new Vector2(512F, -279.5F), new Vector2(508.957001F, -302.164001F), new Vector2(502.875F, -324F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - Shape tree root for layer: “”轮廓
            // 
            CompositionColorBrush ColorBrush_AlmostLavender_FFEBEBEB()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0xEB, 0xEB, 0xEB));
            }

            // - Shape tree root for layer: “”轮廓
            // 
            CompositionColorBrush ColorBrush_Black()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x00, 0x00, 0x00));
            }

            // - Shape tree root for layer: “”轮廓
            // 
            CompositionPathGeometry PathGeometry()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry()));
            }

            // Shape tree root for layer: “”轮廓
            // 
            CompositionSpriteShape SpriteShape()
            {
                if (_spriteShape != null) { return _spriteShape; }
                var result = _spriteShape = _c.CreateSpriteShape(PathGeometry());
                result.CenterPoint = new Vector2(256F, -256F);
                result.Offset = new Vector2(0F, 512F);
                result.FillBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeBrush = ColorBrush_Black();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 2F;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Shape tree root for layer: “”轮廓
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F))
                    : _cubicBezierEasingFunction_0;
            }

            // - Shape tree root for layer: “”轮廓
            // 
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_360()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 27.
                result.InsertKeyFrame(0.449999988F, 95.7409973F, CubicBezierEasingFunction_0());
                // Frame 40.
                result.InsertKeyFrame(0.666666687F, 274.375F, CubicBezierEasingFunction_0());
                // Frame 59.
                result.InsertKeyFrame(0.983333349F, 360F, CubicBezierEasingFunction_0());
                return result;
            }

            // Shape tree root for layer: “”轮廓
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(512F, 512F);
                // 
                result.Shapes.Add(SpriteShape());
                return result;
            }

            // - - Shape tree root for layer: “”轮廓
            // - 
            // RotationAngleInDegrees
            StepEasingFunction HoldThenStepEasingFunction()
            {
                var result = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            internal RefreshIcon_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(512F, 512F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _spriteShape.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_360(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _spriteShape.StopAnimation("RotationAngleInDegrees");
            }

        }
    }
}
