//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace WE_Tool.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile SelectAllIcon.json
//       
//       Input file:
//           SelectAllIcon.json (16332 bytes created 17:19+08:00 Sep 14 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    60 |
// |--------------------------+-------|
// | Expression animators     |     9 |
// | KeyFrame animators       |     4 |
// | Reference parameters     |     9 |
// | Expression operations    |    16 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     9 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     - |
// | CompositionSpriteShapes  |     5 |
// |--------------------------+-------|
// | Brushes                  |     1 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace WE_Tool.AnimatedVisuals
{
    // Name:        SelectAll
    // Frame rate:  60 fps
    // Frame count: 60
    // Duration:    1000.0 mS
    // ___________________________________________________________________________________
    // |        Marker         |        Constant         | Frame |   mS   |   Progress   |
    // |_______________________|_________________________|_______|________|______________|
    // | NormalToPressed_Start | M_NormalToPressed_Start |     0 |    0.0 | 0F           |
    // | NormalToPlaying_Start | M_NormalToPlaying_Start |     0 |    0.0 | 0F           |
    // | NormalToPressed_End   | M_NormalToPressed_End   |    30 |  500.0 | 0.500833333F |
    // | PressedToNormal_Start | M_PressedToNormal_Start |    30 |  500.0 | 0.500833333F |
    // | PressedToNormal_End   | M_PressedToNormal_End   |    60 | 1000.0 | 1F           |
    // | NormalToPlaying_End   | M_NormalToPlaying_End   |    60 | 1000.0 | 1F           |
    // | PlayingToNormal_Start | M_PlayingToNormal_Start |    60 | 1000.0 | 1F           |
    // | PlayingToNormal_End   | M_PlayingToNormal_End   |    60 | 1000.0 | 1F           |
    // -----------------------------------------------------------------------------------
    public sealed class SelectAllIcon
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 1.000 seconds.
        internal const long c_durationTicks = 10000000;

        // Marker: NormalToPressed_Start.
        internal const float M_NormalToPressed_Start = 0F;

        // Marker: NormalToPlaying_Start.
        internal const float M_NormalToPlaying_Start = 0F;

        // Marker: NormalToPressed_End.
        internal const float M_NormalToPressed_End = 0.500833333F;

        // Marker: PressedToNormal_Start.
        internal const float M_PressedToNormal_Start = 0.500833333F;

        // Marker: PressedToNormal_End.
        internal const float M_PressedToNormal_End = 1F;

        // Marker: NormalToPlaying_End.
        internal const float M_NormalToPlaying_End = 1F;

        // Marker: PlayingToNormal_Start.
        internal const float M_PlayingToNormal_Start = 1F;

        // Marker: PlayingToNormal_End.
        internal const float M_PlayingToNormal_End = 1F;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new SelectAllIcon_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 60d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(10000000);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 60d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "NormalToPressed_Start", 0d },
                { "NormalToPlaying_Start", 0d },
                { "NormalToPressed_End", 0.500833333333333 },
                { "PressedToNormal_Start", 0.500833333333333 },
                { "PressedToNormal_End", 1d },
                { "NormalToPlaying_End", 1d },
                { "PlayingToNormal_Start", 1d },
                { "PlayingToNormal_End", 1d },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class SelectAllIcon_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 10000000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionColorBrush _colorBrush_AlmostLavender_FFEBEBEB;
            CompositionRoundedRectangleGeometry _roundedRectangle_0;
            CompositionRoundedRectangleGeometry _roundedRectangle_1;
            CompositionRoundedRectangleGeometry _roundedRectangle_2;
            CompositionRoundedRectangleGeometry _roundedRectangle_3;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - Shape tree root for layer: “”轮廓
            // - -  Offset:<0, 512>
            // -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+ 4+
            // 3+ 2+.PathGeometry
            CanvasGeometry Geometry_00()
            {
                var result = CanvasGeometry.CreateGroup(
                    null,
                    new CanvasGeometry[] { Geometry_01(), Geometry_02(), Geometry_03(), Geometry_04(), Geometry_05(), Geometry_06(), Geometry_07(), Geometry_08(), Geometry_09(), Geometry_10(), Geometry_11(), Geometry_12(), Geometry_13(), Geometry_14(), Geometry_15(), Geometry_16(), Geometry_17(), Geometry_18(), Geometry_19(), Geometry_20() },
                    CanvasFilledRegionDetermination.Winding);
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_01()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(368F, 0F));
                    builder.AddCubicBezier(new Vector2(372.332001F, 0F), new Vector2(376.082001F, -1.58200002F), new Vector2(379.25F, -4.75F));
                    builder.AddCubicBezier(new Vector2(382.414001F, -7.91400003F), new Vector2(384F, -11.6639996F), new Vector2(384F, -16F));
                    builder.AddCubicBezier(new Vector2(384F, -20.3320007F), new Vector2(382.414001F, -24.0820007F), new Vector2(379.25F, -27.25F));
                    builder.AddCubicBezier(new Vector2(376.082001F, -30.4139996F), new Vector2(372.332001F, -32F), new Vector2(368F, -32F));
                    builder.AddLine(new Vector2(304F, -32F));
                    builder.AddCubicBezier(new Vector2(299.664001F, -32F), new Vector2(295.914001F, -30.4139996F), new Vector2(292.75F, -27.25F));
                    builder.AddCubicBezier(new Vector2(289.582001F, -24.0820007F), new Vector2(288F, -20.3320007F), new Vector2(288F, -16F));
                    builder.AddCubicBezier(new Vector2(288F, -11.6639996F), new Vector2(289.582001F, -7.91400003F), new Vector2(292.75F, -4.75F));
                    builder.AddCubicBezier(new Vector2(295.914001F, -1.58200002F), new Vector2(299.664001F, 0F), new Vector2(304F, 0F));
                    builder.AddLine(new Vector2(368F, 0F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_02()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(224F, 0F));
                    builder.AddCubicBezier(new Vector2(228.332001F, 0F), new Vector2(232.082001F, -1.58200002F), new Vector2(235.25F, -4.75F));
                    builder.AddCubicBezier(new Vector2(238.414001F, -7.91400003F), new Vector2(240F, -11.6639996F), new Vector2(240F, -16F));
                    builder.AddCubicBezier(new Vector2(240F, -20.3320007F), new Vector2(238.414001F, -24.0820007F), new Vector2(235.25F, -27.25F));
                    builder.AddCubicBezier(new Vector2(232.082001F, -30.4139996F), new Vector2(228.332001F, -32F), new Vector2(224F, -32F));
                    builder.AddLine(new Vector2(160F, -32F));
                    builder.AddCubicBezier(new Vector2(155.664001F, -32F), new Vector2(151.914001F, -30.4139996F), new Vector2(148.75F, -27.25F));
                    builder.AddCubicBezier(new Vector2(145.582001F, -24.0820007F), new Vector2(144F, -20.3320007F), new Vector2(144F, -16F));
                    builder.AddCubicBezier(new Vector2(144F, -11.6639996F), new Vector2(145.582001F, -7.91400003F), new Vector2(148.75F, -4.75F));
                    builder.AddCubicBezier(new Vector2(151.914001F, -1.58200002F), new Vector2(155.664001F, 0F), new Vector2(160F, 0F));
                    builder.AddLine(new Vector2(224F, 0F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_03()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(418.125F, -7.25F));
                    builder.AddCubicBezier(new Vector2(419.539001F, -5.08199978F), new Vector2(421.375F, -3.45700002F), new Vector2(423.625F, -2.375F));
                    builder.AddCubicBezier(new Vector2(425.875F, -1.28900003F), new Vector2(428.414001F, -0.582000017F), new Vector2(431.25F, -0.25F));
                    builder.AddCubicBezier(new Vector2(434.082001F, 0.0820000023F), new Vector2(436.914001F, 0.25F), new Vector2(439.75F, 0.25F));
                    builder.AddLine(new Vector2(449.25F, 0F));
                    builder.AddCubicBezier(new Vector2(457.582001F, 0F), new Vector2(465.539001F, -1.70700002F), new Vector2(473.125F, -5.125F));
                    builder.AddCubicBezier(new Vector2(480.707001F, -8.53899956F), new Vector2(487.375F, -13.125F), new Vector2(493.125F, -18.875F));
                    builder.AddCubicBezier(new Vector2(498.875F, -24.625F), new Vector2(503.457001F, -31.2889996F), new Vector2(506.875F, -38.875F));
                    builder.AddCubicBezier(new Vector2(510.289001F, -46.4570007F), new Vector2(512F, -54.4140015F), new Vector2(512F, -62.75F));
                    builder.AddLine(new Vector2(512F, -80F));
                    builder.AddCubicBezier(new Vector2(512F, -84.3320007F), new Vector2(510.414001F, -88.0820007F), new Vector2(507.25F, -91.25F));
                    builder.AddCubicBezier(new Vector2(504.082001F, -94.4140015F), new Vector2(500.332001F, -96F), new Vector2(496F, -96F));
                    builder.AddCubicBezier(new Vector2(491.664001F, -96F), new Vector2(487.914001F, -94.4140015F), new Vector2(484.75F, -91.25F));
                    builder.AddCubicBezier(new Vector2(481.582001F, -88.0820007F), new Vector2(480F, -84.3320007F), new Vector2(480F, -80F));
                    builder.AddLine(new Vector2(480.25F, -68.75F));
                    builder.AddCubicBezier(new Vector2(480.25F, -44.0820007F), new Vector2(467.914001F, -31.75F), new Vector2(443.25F, -31.75F));
                    builder.AddLine(new Vector2(439.5F, -31.75F));
                    builder.AddCubicBezier(new Vector2(436.664001F, -31.75F), new Vector2(433.875F, -31.625F), new Vector2(431.125F, -31.375F));
                    builder.AddCubicBezier(new Vector2(428.375F, -31.125F), new Vector2(425.875F, -30.5F), new Vector2(423.625F, -29.5F));
                    builder.AddCubicBezier(new Vector2(421.375F, -28.5F), new Vector2(419.539001F, -26.9139996F), new Vector2(418.125F, -24.75F));
                    builder.AddCubicBezier(new Vector2(416.707001F, -22.5820007F), new Vector2(416F, -19.6639996F), new Vector2(416F, -16F));
                    builder.AddCubicBezier(new Vector2(416F, -12.3319998F), new Vector2(416.707001F, -9.41399956F), new Vector2(418.125F, -7.25F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_04()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(80F, 0F));
                    builder.AddCubicBezier(new Vector2(84.3320007F, 0F), new Vector2(88.0820007F, -1.58200002F), new Vector2(91.25F, -4.75F));
                    builder.AddCubicBezier(new Vector2(94.4140015F, -7.91400003F), new Vector2(96F, -11.6639996F), new Vector2(96F, -16F));
                    builder.AddCubicBezier(new Vector2(96F, -20.3320007F), new Vector2(94.4140015F, -24.0820007F), new Vector2(91.25F, -27.25F));
                    builder.AddCubicBezier(new Vector2(88.0820007F, -30.4139996F), new Vector2(84.3320007F, -32F), new Vector2(80F, -32F));
                    builder.AddLine(new Vector2(68.75F, -31.75F));
                    builder.AddCubicBezier(new Vector2(44.0820007F, -31.75F), new Vector2(31.75F, -44.0820007F), new Vector2(31.75F, -68.75F));
                    builder.AddLine(new Vector2(31.75F, -72.5F));
                    builder.AddCubicBezier(new Vector2(31.75F, -75.1640015F), new Vector2(31.625F, -77.9140015F), new Vector2(31.375F, -80.75F));
                    builder.AddCubicBezier(new Vector2(31.125F, -83.5820007F), new Vector2(30.5F, -86.125F), new Vector2(29.5F, -88.375F));
                    builder.AddCubicBezier(new Vector2(28.5F, -90.625F), new Vector2(26.9139996F, -92.4570007F), new Vector2(24.75F, -93.875F));
                    builder.AddCubicBezier(new Vector2(22.5820007F, -95.2890015F), new Vector2(19.6639996F, -96F), new Vector2(16F, -96F));
                    builder.AddCubicBezier(new Vector2(12.3319998F, -96F), new Vector2(9.41399956F, -95.2890015F), new Vector2(7.25F, -93.875F));
                    builder.AddCubicBezier(new Vector2(5.08199978F, -92.4570007F), new Vector2(3.45700002F, -90.625F), new Vector2(2.375F, -88.375F));
                    builder.AddCubicBezier(new Vector2(1.28900003F, -86.125F), new Vector2(0.582000017F, -83.5820007F), new Vector2(0.25F, -80.75F));
                    builder.AddCubicBezier(new Vector2(-0.0820000023F, -77.9140015F), new Vector2(-0.25F, -75.0820007F), new Vector2(-0.25F, -72.25F));
                    builder.AddLine(new Vector2(0F, -62.75F));
                    builder.AddCubicBezier(new Vector2(0F, -54.4140015F), new Vector2(1.70700002F, -46.4570007F), new Vector2(5.125F, -38.875F));
                    builder.AddCubicBezier(new Vector2(8.53899956F, -31.2889996F), new Vector2(13.125F, -24.625F), new Vector2(18.875F, -18.875F));
                    builder.AddCubicBezier(new Vector2(24.625F, -13.125F), new Vector2(31.2889996F, -8.53899956F), new Vector2(38.875F, -5.125F));
                    builder.AddCubicBezier(new Vector2(46.4570007F, -1.70700002F), new Vector2(54.4140015F, 0F), new Vector2(62.75F, 0F));
                    builder.AddLine(new Vector2(80F, 0F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_05()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(336F, -96F));
                    builder.AddCubicBezier(new Vector2(331.664001F, -96F), new Vector2(327.914001F, -97.5820007F), new Vector2(324.75F, -100.75F));
                    builder.AddCubicBezier(new Vector2(321.582001F, -103.914001F), new Vector2(320F, -107.664001F), new Vector2(320F, -112F));
                    builder.AddLine(new Vector2(320F, -176F));
                    builder.AddCubicBezier(new Vector2(320F, -180.332001F), new Vector2(321.582001F, -184.082001F), new Vector2(324.75F, -187.25F));
                    builder.AddCubicBezier(new Vector2(327.914001F, -190.414001F), new Vector2(331.664001F, -192F), new Vector2(336F, -192F));
                    builder.AddLine(new Vector2(400F, -192F));
                    builder.AddCubicBezier(new Vector2(404.332001F, -192F), new Vector2(408.082001F, -190.414001F), new Vector2(411.25F, -187.25F));
                    builder.AddCubicBezier(new Vector2(414.414001F, -184.082001F), new Vector2(416F, -180.332001F), new Vector2(416F, -176F));
                    builder.AddLine(new Vector2(416F, -112F));
                    builder.AddCubicBezier(new Vector2(416F, -107.664001F), new Vector2(414.414001F, -103.914001F), new Vector2(411.25F, -100.75F));
                    builder.AddCubicBezier(new Vector2(408.082001F, -97.5820007F), new Vector2(404.332001F, -96F), new Vector2(400F, -96F));
                    builder.AddLine(new Vector2(336F, -96F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_06()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(112F, -96F));
                    builder.AddCubicBezier(new Vector2(107.664001F, -96F), new Vector2(103.914001F, -97.5820007F), new Vector2(100.75F, -100.75F));
                    builder.AddCubicBezier(new Vector2(97.5820007F, -103.914001F), new Vector2(96F, -107.664001F), new Vector2(96F, -112F));
                    builder.AddLine(new Vector2(96F, -176F));
                    builder.AddCubicBezier(new Vector2(96F, -180.332001F), new Vector2(97.5820007F, -184.082001F), new Vector2(100.75F, -187.25F));
                    builder.AddCubicBezier(new Vector2(103.914001F, -190.414001F), new Vector2(107.664001F, -192F), new Vector2(112F, -192F));
                    builder.AddLine(new Vector2(176F, -192F));
                    builder.AddCubicBezier(new Vector2(180.332001F, -192F), new Vector2(184.082001F, -190.414001F), new Vector2(187.25F, -187.25F));
                    builder.AddCubicBezier(new Vector2(190.414001F, -184.082001F), new Vector2(192F, -180.332001F), new Vector2(192F, -176F));
                    builder.AddLine(new Vector2(192F, -112F));
                    builder.AddCubicBezier(new Vector2(192F, -107.664001F), new Vector2(190.414001F, -103.914001F), new Vector2(187.25F, -100.75F));
                    builder.AddCubicBezier(new Vector2(184.082001F, -97.5820007F), new Vector2(180.332001F, -96F), new Vector2(176F, -96F));
                    builder.AddLine(new Vector2(112F, -96F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_07()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(400F, -64F));
                    builder.AddCubicBezier(new Vector2(406.5F, -64F), new Vector2(412.664001F, -65.25F), new Vector2(418.5F, -67.75F));
                    builder.AddCubicBezier(new Vector2(424.332001F, -70.25F), new Vector2(429.457001F, -73.7070007F), new Vector2(433.875F, -78.125F));
                    builder.AddCubicBezier(new Vector2(438.289001F, -82.5390015F), new Vector2(441.75F, -87.6640015F), new Vector2(444.25F, -93.5F));
                    builder.AddCubicBezier(new Vector2(446.75F, -99.3320007F), new Vector2(448F, -105.5F), new Vector2(448F, -112F));
                    builder.AddLine(new Vector2(448F, -176F));
                    builder.AddCubicBezier(new Vector2(448F, -182.5F), new Vector2(446.75F, -188.664001F), new Vector2(444.25F, -194.5F));
                    builder.AddCubicBezier(new Vector2(441.75F, -200.332001F), new Vector2(438.289001F, -205.457001F), new Vector2(433.875F, -209.875F));
                    builder.AddCubicBezier(new Vector2(429.457001F, -214.289001F), new Vector2(424.332001F, -217.75F), new Vector2(418.5F, -220.25F));
                    builder.AddCubicBezier(new Vector2(412.664001F, -222.75F), new Vector2(406.5F, -224F), new Vector2(400F, -224F));
                    builder.AddLine(new Vector2(336F, -224F));
                    builder.AddCubicBezier(new Vector2(329.5F, -224F), new Vector2(323.332001F, -222.75F), new Vector2(317.5F, -220.25F));
                    builder.AddCubicBezier(new Vector2(311.664001F, -217.75F), new Vector2(306.539001F, -214.289001F), new Vector2(302.125F, -209.875F));
                    builder.AddCubicBezier(new Vector2(297.707001F, -205.457001F), new Vector2(294.25F, -200.332001F), new Vector2(291.75F, -194.5F));
                    builder.AddCubicBezier(new Vector2(289.25F, -188.664001F), new Vector2(288F, -182.5F), new Vector2(288F, -176F));
                    builder.AddLine(new Vector2(288F, -112F));
                    builder.AddCubicBezier(new Vector2(288F, -105.5F), new Vector2(289.25F, -99.3320007F), new Vector2(291.75F, -93.5F));
                    builder.AddCubicBezier(new Vector2(294.25F, -87.6640015F), new Vector2(297.707001F, -82.5390015F), new Vector2(302.125F, -78.125F));
                    builder.AddCubicBezier(new Vector2(306.539001F, -73.7070007F), new Vector2(311.664001F, -70.25F), new Vector2(317.5F, -67.75F));
                    builder.AddCubicBezier(new Vector2(323.332001F, -65.25F), new Vector2(329.5F, -64F), new Vector2(336F, -64F));
                    builder.AddLine(new Vector2(400F, -64F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_08()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(176F, -64F));
                    builder.AddCubicBezier(new Vector2(182.5F, -64F), new Vector2(188.664001F, -65.25F), new Vector2(194.5F, -67.75F));
                    builder.AddCubicBezier(new Vector2(200.332001F, -70.25F), new Vector2(205.457001F, -73.7070007F), new Vector2(209.875F, -78.125F));
                    builder.AddCubicBezier(new Vector2(214.289001F, -82.5390015F), new Vector2(217.75F, -87.6640015F), new Vector2(220.25F, -93.5F));
                    builder.AddCubicBezier(new Vector2(222.75F, -99.3320007F), new Vector2(224F, -105.5F), new Vector2(224F, -112F));
                    builder.AddLine(new Vector2(224F, -176F));
                    builder.AddCubicBezier(new Vector2(224F, -182.5F), new Vector2(222.75F, -188.664001F), new Vector2(220.25F, -194.5F));
                    builder.AddCubicBezier(new Vector2(217.75F, -200.332001F), new Vector2(214.289001F, -205.457001F), new Vector2(209.875F, -209.875F));
                    builder.AddCubicBezier(new Vector2(205.457001F, -214.289001F), new Vector2(200.332001F, -217.75F), new Vector2(194.5F, -220.25F));
                    builder.AddCubicBezier(new Vector2(188.664001F, -222.75F), new Vector2(182.5F, -224F), new Vector2(176F, -224F));
                    builder.AddLine(new Vector2(112F, -224F));
                    builder.AddCubicBezier(new Vector2(105.5F, -224F), new Vector2(99.3320007F, -222.75F), new Vector2(93.5F, -220.25F));
                    builder.AddCubicBezier(new Vector2(87.6640015F, -217.75F), new Vector2(82.5390015F, -214.289001F), new Vector2(78.125F, -209.875F));
                    builder.AddCubicBezier(new Vector2(73.7070007F, -205.457001F), new Vector2(70.25F, -200.332001F), new Vector2(67.75F, -194.5F));
                    builder.AddCubicBezier(new Vector2(65.25F, -188.664001F), new Vector2(64F, -182.5F), new Vector2(64F, -176F));
                    builder.AddLine(new Vector2(64F, -112F));
                    builder.AddCubicBezier(new Vector2(64F, -105.5F), new Vector2(65.25F, -99.3320007F), new Vector2(67.75F, -93.5F));
                    builder.AddCubicBezier(new Vector2(70.25F, -87.6640015F), new Vector2(73.7070007F, -82.5390015F), new Vector2(78.125F, -78.125F));
                    builder.AddCubicBezier(new Vector2(82.5390015F, -73.7070007F), new Vector2(87.6640015F, -70.25F), new Vector2(93.5F, -67.75F));
                    builder.AddCubicBezier(new Vector2(99.3320007F, -65.25F), new Vector2(105.5F, -64F), new Vector2(112F, -64F));
                    builder.AddLine(new Vector2(176F, -64F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_09()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(484.75F, -148.75F));
                    builder.AddCubicBezier(new Vector2(487.914001F, -145.582001F), new Vector2(491.664001F, -144F), new Vector2(496F, -144F));
                    builder.AddCubicBezier(new Vector2(500.332001F, -144F), new Vector2(504.082001F, -145.582001F), new Vector2(507.25F, -148.75F));
                    builder.AddCubicBezier(new Vector2(510.414001F, -151.914001F), new Vector2(512F, -155.664001F), new Vector2(512F, -160F));
                    builder.AddLine(new Vector2(512F, -224F));
                    builder.AddCubicBezier(new Vector2(512F, -228.332001F), new Vector2(510.414001F, -232.082001F), new Vector2(507.25F, -235.25F));
                    builder.AddCubicBezier(new Vector2(504.082001F, -238.414001F), new Vector2(500.332001F, -240F), new Vector2(496F, -240F));
                    builder.AddCubicBezier(new Vector2(491.664001F, -240F), new Vector2(487.914001F, -238.414001F), new Vector2(484.75F, -235.25F));
                    builder.AddCubicBezier(new Vector2(481.582001F, -232.082001F), new Vector2(480F, -228.332001F), new Vector2(480F, -224F));
                    builder.AddLine(new Vector2(480F, -160F));
                    builder.AddCubicBezier(new Vector2(480F, -155.664001F), new Vector2(481.582001F, -151.914001F), new Vector2(484.75F, -148.75F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_10()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(4.75F, -148.75F));
                    builder.AddCubicBezier(new Vector2(7.91400003F, -145.582001F), new Vector2(11.6639996F, -144F), new Vector2(16F, -144F));
                    builder.AddCubicBezier(new Vector2(20.3320007F, -144F), new Vector2(24.0820007F, -145.582001F), new Vector2(27.25F, -148.75F));
                    builder.AddCubicBezier(new Vector2(30.4139996F, -151.914001F), new Vector2(32F, -155.664001F), new Vector2(32F, -160F));
                    builder.AddLine(new Vector2(32F, -224F));
                    builder.AddCubicBezier(new Vector2(32F, -228.332001F), new Vector2(30.4139996F, -232.082001F), new Vector2(27.25F, -235.25F));
                    builder.AddCubicBezier(new Vector2(24.0820007F, -238.414001F), new Vector2(20.3320007F, -240F), new Vector2(16F, -240F));
                    builder.AddCubicBezier(new Vector2(11.6639996F, -240F), new Vector2(7.91400003F, -238.414001F), new Vector2(4.75F, -235.25F));
                    builder.AddCubicBezier(new Vector2(1.58200002F, -232.082001F), new Vector2(0F, -228.332001F), new Vector2(0F, -224F));
                    builder.AddLine(new Vector2(0F, -160F));
                    builder.AddCubicBezier(new Vector2(0F, -155.664001F), new Vector2(1.58200002F, -151.914001F), new Vector2(4.75F, -148.75F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_11()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(484.75F, -292.75F));
                    builder.AddCubicBezier(new Vector2(487.914001F, -289.582001F), new Vector2(491.664001F, -288F), new Vector2(496F, -288F));
                    builder.AddCubicBezier(new Vector2(500.332001F, -288F), new Vector2(504.082001F, -289.582001F), new Vector2(507.25F, -292.75F));
                    builder.AddCubicBezier(new Vector2(510.414001F, -295.914001F), new Vector2(512F, -299.664001F), new Vector2(512F, -304F));
                    builder.AddLine(new Vector2(512F, -368F));
                    builder.AddCubicBezier(new Vector2(512F, -372.332001F), new Vector2(510.414001F, -376.082001F), new Vector2(507.25F, -379.25F));
                    builder.AddCubicBezier(new Vector2(504.082001F, -382.414001F), new Vector2(500.332001F, -384F), new Vector2(496F, -384F));
                    builder.AddCubicBezier(new Vector2(491.664001F, -384F), new Vector2(487.914001F, -382.414001F), new Vector2(484.75F, -379.25F));
                    builder.AddCubicBezier(new Vector2(481.582001F, -376.082001F), new Vector2(480F, -372.332001F), new Vector2(480F, -368F));
                    builder.AddLine(new Vector2(480F, -304F));
                    builder.AddCubicBezier(new Vector2(480F, -299.664001F), new Vector2(481.582001F, -295.914001F), new Vector2(484.75F, -292.75F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_12()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(4.75F, -292.75F));
                    builder.AddCubicBezier(new Vector2(7.91400003F, -289.582001F), new Vector2(11.6639996F, -288F), new Vector2(16F, -288F));
                    builder.AddCubicBezier(new Vector2(20.3320007F, -288F), new Vector2(24.0820007F, -289.582001F), new Vector2(27.25F, -292.75F));
                    builder.AddCubicBezier(new Vector2(30.4139996F, -295.914001F), new Vector2(32F, -299.664001F), new Vector2(32F, -304F));
                    builder.AddLine(new Vector2(32F, -368F));
                    builder.AddCubicBezier(new Vector2(32F, -372.332001F), new Vector2(30.4139996F, -376.082001F), new Vector2(27.25F, -379.25F));
                    builder.AddCubicBezier(new Vector2(24.0820007F, -382.414001F), new Vector2(20.3320007F, -384F), new Vector2(16F, -384F));
                    builder.AddCubicBezier(new Vector2(11.6639996F, -384F), new Vector2(7.91400003F, -382.414001F), new Vector2(4.75F, -379.25F));
                    builder.AddCubicBezier(new Vector2(1.58200002F, -376.082001F), new Vector2(0F, -372.332001F), new Vector2(0F, -368F));
                    builder.AddLine(new Vector2(0F, -304F));
                    builder.AddCubicBezier(new Vector2(0F, -299.664001F), new Vector2(1.58200002F, -295.914001F), new Vector2(4.75F, -292.75F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_13()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(336F, -320F));
                    builder.AddCubicBezier(new Vector2(331.664001F, -320F), new Vector2(327.914001F, -321.582001F), new Vector2(324.75F, -324.75F));
                    builder.AddCubicBezier(new Vector2(321.582001F, -327.914001F), new Vector2(320F, -331.664001F), new Vector2(320F, -336F));
                    builder.AddLine(new Vector2(320F, -400F));
                    builder.AddCubicBezier(new Vector2(320F, -404.332001F), new Vector2(321.582001F, -408.082001F), new Vector2(324.75F, -411.25F));
                    builder.AddCubicBezier(new Vector2(327.914001F, -414.414001F), new Vector2(331.664001F, -416F), new Vector2(336F, -416F));
                    builder.AddLine(new Vector2(400F, -416F));
                    builder.AddCubicBezier(new Vector2(404.332001F, -416F), new Vector2(408.082001F, -414.414001F), new Vector2(411.25F, -411.25F));
                    builder.AddCubicBezier(new Vector2(414.414001F, -408.082001F), new Vector2(416F, -404.332001F), new Vector2(416F, -400F));
                    builder.AddLine(new Vector2(416F, -336F));
                    builder.AddCubicBezier(new Vector2(416F, -331.664001F), new Vector2(414.414001F, -327.914001F), new Vector2(411.25F, -324.75F));
                    builder.AddCubicBezier(new Vector2(408.082001F, -321.582001F), new Vector2(404.332001F, -320F), new Vector2(400F, -320F));
                    builder.AddLine(new Vector2(336F, -320F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_14()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(112F, -320F));
                    builder.AddCubicBezier(new Vector2(107.664001F, -320F), new Vector2(103.914001F, -321.582001F), new Vector2(100.75F, -324.75F));
                    builder.AddCubicBezier(new Vector2(97.5820007F, -327.914001F), new Vector2(96F, -331.664001F), new Vector2(96F, -336F));
                    builder.AddLine(new Vector2(96F, -400F));
                    builder.AddCubicBezier(new Vector2(96F, -404.332001F), new Vector2(97.5820007F, -408.082001F), new Vector2(100.75F, -411.25F));
                    builder.AddCubicBezier(new Vector2(103.914001F, -414.414001F), new Vector2(107.664001F, -416F), new Vector2(112F, -416F));
                    builder.AddLine(new Vector2(176F, -416F));
                    builder.AddCubicBezier(new Vector2(180.332001F, -416F), new Vector2(184.082001F, -414.414001F), new Vector2(187.25F, -411.25F));
                    builder.AddCubicBezier(new Vector2(190.414001F, -408.082001F), new Vector2(192F, -404.332001F), new Vector2(192F, -400F));
                    builder.AddLine(new Vector2(192F, -336F));
                    builder.AddCubicBezier(new Vector2(192F, -331.664001F), new Vector2(190.414001F, -327.914001F), new Vector2(187.25F, -324.75F));
                    builder.AddCubicBezier(new Vector2(184.082001F, -321.582001F), new Vector2(180.332001F, -320F), new Vector2(176F, -320F));
                    builder.AddLine(new Vector2(112F, -320F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_15()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(400F, -288F));
                    builder.AddCubicBezier(new Vector2(406.5F, -288F), new Vector2(412.664001F, -289.25F), new Vector2(418.5F, -291.75F));
                    builder.AddCubicBezier(new Vector2(424.332001F, -294.25F), new Vector2(429.457001F, -297.707001F), new Vector2(433.875F, -302.125F));
                    builder.AddCubicBezier(new Vector2(438.289001F, -306.539001F), new Vector2(441.75F, -311.664001F), new Vector2(444.25F, -317.5F));
                    builder.AddCubicBezier(new Vector2(446.75F, -323.332001F), new Vector2(448F, -329.5F), new Vector2(448F, -336F));
                    builder.AddLine(new Vector2(448F, -400F));
                    builder.AddCubicBezier(new Vector2(448F, -406.5F), new Vector2(446.75F, -412.664001F), new Vector2(444.25F, -418.5F));
                    builder.AddCubicBezier(new Vector2(441.75F, -424.332001F), new Vector2(438.289001F, -429.457001F), new Vector2(433.875F, -433.875F));
                    builder.AddCubicBezier(new Vector2(429.457001F, -438.289001F), new Vector2(424.332001F, -441.75F), new Vector2(418.5F, -444.25F));
                    builder.AddCubicBezier(new Vector2(412.664001F, -446.75F), new Vector2(406.5F, -448F), new Vector2(400F, -448F));
                    builder.AddLine(new Vector2(336F, -448F));
                    builder.AddCubicBezier(new Vector2(329.5F, -448F), new Vector2(323.332001F, -446.75F), new Vector2(317.5F, -444.25F));
                    builder.AddCubicBezier(new Vector2(311.664001F, -441.75F), new Vector2(306.539001F, -438.289001F), new Vector2(302.125F, -433.875F));
                    builder.AddCubicBezier(new Vector2(297.707001F, -429.457001F), new Vector2(294.25F, -424.332001F), new Vector2(291.75F, -418.5F));
                    builder.AddCubicBezier(new Vector2(289.25F, -412.664001F), new Vector2(288F, -406.5F), new Vector2(288F, -400F));
                    builder.AddLine(new Vector2(288F, -336F));
                    builder.AddCubicBezier(new Vector2(288F, -329.5F), new Vector2(289.25F, -323.332001F), new Vector2(291.75F, -317.5F));
                    builder.AddCubicBezier(new Vector2(294.25F, -311.664001F), new Vector2(297.707001F, -306.539001F), new Vector2(302.125F, -302.125F));
                    builder.AddCubicBezier(new Vector2(306.539001F, -297.707001F), new Vector2(311.664001F, -294.25F), new Vector2(317.5F, -291.75F));
                    builder.AddCubicBezier(new Vector2(323.332001F, -289.25F), new Vector2(329.5F, -288F), new Vector2(336F, -288F));
                    builder.AddLine(new Vector2(400F, -288F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_16()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(176F, -288F));
                    builder.AddCubicBezier(new Vector2(182.5F, -288F), new Vector2(188.664001F, -289.25F), new Vector2(194.5F, -291.75F));
                    builder.AddCubicBezier(new Vector2(200.332001F, -294.25F), new Vector2(205.457001F, -297.707001F), new Vector2(209.875F, -302.125F));
                    builder.AddCubicBezier(new Vector2(214.289001F, -306.539001F), new Vector2(217.75F, -311.664001F), new Vector2(220.25F, -317.5F));
                    builder.AddCubicBezier(new Vector2(222.75F, -323.332001F), new Vector2(224F, -329.5F), new Vector2(224F, -336F));
                    builder.AddLine(new Vector2(224F, -400F));
                    builder.AddCubicBezier(new Vector2(224F, -406.5F), new Vector2(222.75F, -412.664001F), new Vector2(220.25F, -418.5F));
                    builder.AddCubicBezier(new Vector2(217.75F, -424.332001F), new Vector2(214.289001F, -429.457001F), new Vector2(209.875F, -433.875F));
                    builder.AddCubicBezier(new Vector2(205.457001F, -438.289001F), new Vector2(200.332001F, -441.75F), new Vector2(194.5F, -444.25F));
                    builder.AddCubicBezier(new Vector2(188.664001F, -446.75F), new Vector2(182.5F, -448F), new Vector2(176F, -448F));
                    builder.AddLine(new Vector2(112F, -448F));
                    builder.AddCubicBezier(new Vector2(105.5F, -448F), new Vector2(99.3320007F, -446.75F), new Vector2(93.5F, -444.25F));
                    builder.AddCubicBezier(new Vector2(87.6640015F, -441.75F), new Vector2(82.5390015F, -438.289001F), new Vector2(78.125F, -433.875F));
                    builder.AddCubicBezier(new Vector2(73.7070007F, -429.457001F), new Vector2(70.25F, -424.332001F), new Vector2(67.75F, -418.5F));
                    builder.AddCubicBezier(new Vector2(65.25F, -412.664001F), new Vector2(64F, -406.5F), new Vector2(64F, -400F));
                    builder.AddLine(new Vector2(64F, -336F));
                    builder.AddCubicBezier(new Vector2(64F, -329.5F), new Vector2(65.25F, -323.332001F), new Vector2(67.75F, -317.5F));
                    builder.AddCubicBezier(new Vector2(70.25F, -311.664001F), new Vector2(73.7070007F, -306.539001F), new Vector2(78.125F, -302.125F));
                    builder.AddCubicBezier(new Vector2(82.5390015F, -297.707001F), new Vector2(87.6640015F, -294.25F), new Vector2(93.5F, -291.75F));
                    builder.AddCubicBezier(new Vector2(99.3320007F, -289.25F), new Vector2(105.5F, -288F), new Vector2(112F, -288F));
                    builder.AddLine(new Vector2(176F, -288F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_17()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(420.75F, -484.75F));
                    builder.AddCubicBezier(new Vector2(423.914001F, -481.582001F), new Vector2(427.664001F, -480F), new Vector2(432F, -480F));
                    builder.AddLine(new Vector2(443.25F, -480.25F));
                    builder.AddCubicBezier(new Vector2(455.25F, -480.25F), new Vector2(464.414001F, -477.082001F), new Vector2(470.75F, -470.75F));
                    builder.AddCubicBezier(new Vector2(477.082001F, -464.414001F), new Vector2(480.25F, -455.25F), new Vector2(480.25F, -443.25F));
                    builder.AddLine(new Vector2(480.25F, -439.25F));
                    builder.AddCubicBezier(new Vector2(480.25F, -436.414001F), new Vector2(480.375F, -433.625F), new Vector2(480.625F, -430.875F));
                    builder.AddCubicBezier(new Vector2(480.875F, -428.125F), new Vector2(481.5F, -425.664001F), new Vector2(482.5F, -423.5F));
                    builder.AddCubicBezier(new Vector2(483.5F, -421.332001F), new Vector2(485.039001F, -419.539001F), new Vector2(487.125F, -418.125F));
                    builder.AddCubicBezier(new Vector2(489.207001F, -416.707001F), new Vector2(492.164001F, -416F), new Vector2(496F, -416F));
                    builder.AddCubicBezier(new Vector2(499.664001F, -416F), new Vector2(502.539001F, -416.707001F), new Vector2(504.625F, -418.125F));
                    builder.AddCubicBezier(new Vector2(506.707001F, -419.539001F), new Vector2(508.332001F, -421.375F), new Vector2(509.5F, -423.625F));
                    builder.AddCubicBezier(new Vector2(510.664001F, -425.875F), new Vector2(511.414001F, -428.414001F), new Vector2(511.75F, -431.25F));
                    builder.AddCubicBezier(new Vector2(512.08197F, -434.082001F), new Vector2(512.25F, -436.914001F), new Vector2(512.25F, -439.75F));
                    builder.AddLine(new Vector2(512F, -449.25F));
                    builder.AddCubicBezier(new Vector2(512F, -457.582001F), new Vector2(510.289001F, -465.539001F), new Vector2(506.875F, -473.125F));
                    builder.AddCubicBezier(new Vector2(503.457001F, -480.707001F), new Vector2(498.875F, -487.375F), new Vector2(493.125F, -493.125F));
                    builder.AddCubicBezier(new Vector2(487.375F, -498.875F), new Vector2(480.707001F, -503.457001F), new Vector2(473.125F, -506.875F));
                    builder.AddCubicBezier(new Vector2(465.539001F, -510.289001F), new Vector2(457.582001F, -512F), new Vector2(449.25F, -512F));
                    builder.AddLine(new Vector2(432F, -512F));
                    builder.AddCubicBezier(new Vector2(427.664001F, -512F), new Vector2(423.914001F, -510.414001F), new Vector2(420.75F, -507.25F));
                    builder.AddCubicBezier(new Vector2(417.582001F, -504.082001F), new Vector2(416F, -500.332001F), new Vector2(416F, -496F));
                    builder.AddCubicBezier(new Vector2(416F, -491.664001F), new Vector2(417.582001F, -487.914001F), new Vector2(420.75F, -484.75F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_18()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(368F, -480F));
                    builder.AddCubicBezier(new Vector2(372.332001F, -480F), new Vector2(376.082001F, -481.582001F), new Vector2(379.25F, -484.75F));
                    builder.AddCubicBezier(new Vector2(382.414001F, -487.914001F), new Vector2(384F, -491.664001F), new Vector2(384F, -496F));
                    builder.AddCubicBezier(new Vector2(384F, -500.332001F), new Vector2(382.414001F, -504.082001F), new Vector2(379.25F, -507.25F));
                    builder.AddCubicBezier(new Vector2(376.082001F, -510.414001F), new Vector2(372.332001F, -512F), new Vector2(368F, -512F));
                    builder.AddLine(new Vector2(304F, -512F));
                    builder.AddCubicBezier(new Vector2(299.664001F, -512F), new Vector2(295.914001F, -510.414001F), new Vector2(292.75F, -507.25F));
                    builder.AddCubicBezier(new Vector2(289.582001F, -504.082001F), new Vector2(288F, -500.332001F), new Vector2(288F, -496F));
                    builder.AddCubicBezier(new Vector2(288F, -491.664001F), new Vector2(289.582001F, -487.914001F), new Vector2(292.75F, -484.75F));
                    builder.AddCubicBezier(new Vector2(295.914001F, -481.582001F), new Vector2(299.664001F, -480F), new Vector2(304F, -480F));
                    builder.AddLine(new Vector2(368F, -480F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_19()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(224F, -480F));
                    builder.AddCubicBezier(new Vector2(228.332001F, -480F), new Vector2(232.082001F, -481.582001F), new Vector2(235.25F, -484.75F));
                    builder.AddCubicBezier(new Vector2(238.414001F, -487.914001F), new Vector2(240F, -491.664001F), new Vector2(240F, -496F));
                    builder.AddCubicBezier(new Vector2(240F, -500.332001F), new Vector2(238.414001F, -504.082001F), new Vector2(235.25F, -507.25F));
                    builder.AddCubicBezier(new Vector2(232.082001F, -510.414001F), new Vector2(228.332001F, -512F), new Vector2(224F, -512F));
                    builder.AddLine(new Vector2(160F, -512F));
                    builder.AddCubicBezier(new Vector2(155.664001F, -512F), new Vector2(151.914001F, -510.414001F), new Vector2(148.75F, -507.25F));
                    builder.AddCubicBezier(new Vector2(145.582001F, -504.082001F), new Vector2(144F, -500.332001F), new Vector2(144F, -496F));
                    builder.AddCubicBezier(new Vector2(144F, -491.664001F), new Vector2(145.582001F, -487.914001F), new Vector2(148.75F, -484.75F));
                    builder.AddCubicBezier(new Vector2(151.914001F, -481.582001F), new Vector2(155.664001F, -480F), new Vector2(160F, -480F));
                    builder.AddLine(new Vector2(224F, -480F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: “”轮廓
            // - - -  Offset:<0, 512>
            // - -  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+
            // 4+ 3+ 2+.PathGeometry
            CanvasGeometry Geometry_20()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(4.75F, -420.75F));
                    builder.AddCubicBezier(new Vector2(7.91400003F, -417.582001F), new Vector2(11.6639996F, -416F), new Vector2(16F, -416F));
                    builder.AddCubicBezier(new Vector2(20.3320007F, -416F), new Vector2(24.0820007F, -417.582001F), new Vector2(27.25F, -420.75F));
                    builder.AddCubicBezier(new Vector2(30.4139996F, -423.914001F), new Vector2(32F, -427.664001F), new Vector2(32F, -432F));
                    builder.AddLine(new Vector2(31.75F, -443.25F));
                    builder.AddCubicBezier(new Vector2(31.75F, -467.914001F), new Vector2(44.0820007F, -480.25F), new Vector2(68.75F, -480.25F));
                    builder.AddLine(new Vector2(72.5F, -480.25F));
                    builder.AddCubicBezier(new Vector2(75.1640015F, -480.25F), new Vector2(77.9140015F, -480.375F), new Vector2(80.75F, -480.625F));
                    builder.AddCubicBezier(new Vector2(83.5820007F, -480.875F), new Vector2(86.125F, -481.5F), new Vector2(88.375F, -482.5F));
                    builder.AddCubicBezier(new Vector2(90.625F, -483.5F), new Vector2(92.4570007F, -485.039001F), new Vector2(93.875F, -487.125F));
                    builder.AddCubicBezier(new Vector2(95.2890015F, -489.207001F), new Vector2(96F, -492.164001F), new Vector2(96F, -496F));
                    builder.AddCubicBezier(new Vector2(96F, -499.664001F), new Vector2(95.2890015F, -502.539001F), new Vector2(93.875F, -504.625F));
                    builder.AddCubicBezier(new Vector2(92.4570007F, -506.707001F), new Vector2(90.625F, -508.332001F), new Vector2(88.375F, -509.5F));
                    builder.AddCubicBezier(new Vector2(86.125F, -510.664001F), new Vector2(83.5820007F, -511.414001F), new Vector2(80.75F, -511.75F));
                    builder.AddCubicBezier(new Vector2(77.9140015F, -512.08197F), new Vector2(75.0820007F, -512.25F), new Vector2(72.25F, -512.25F));
                    builder.AddLine(new Vector2(62.75F, -512F));
                    builder.AddCubicBezier(new Vector2(54.4140015F, -512F), new Vector2(46.4570007F, -510.289001F), new Vector2(38.875F, -506.875F));
                    builder.AddCubicBezier(new Vector2(31.2889996F, -503.457001F), new Vector2(24.625F, -498.875F), new Vector2(18.875F, -493.125F));
                    builder.AddCubicBezier(new Vector2(13.125F, -487.375F), new Vector2(8.53899956F, -480.707001F), new Vector2(5.125F, -473.125F));
                    builder.AddCubicBezier(new Vector2(1.70700002F, -465.539001F), new Vector2(0F, -457.582001F), new Vector2(0F, -449.25F));
                    builder.AddLine(new Vector2(0F, -432F));
                    builder.AddCubicBezier(new Vector2(0F, -427.664001F), new Vector2(1.58200002F, -423.914001F), new Vector2(4.75F, -420.75F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostLavender_FFEBEBEB()
            {
                return (_colorBrush_AlmostLavender_FFEBEBEB == null)
                    ? _colorBrush_AlmostLavender_FFEBEBEB = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xEB, 0xEB, 0xEB))
                    : _colorBrush_AlmostLavender_FFEBEBEB;
            }

            // - Shape tree root for layer: “”轮廓
            // Offset:<0, 512>
            //  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+ 4+
            // 3+ 2+.PathGeometry
            CompositionPathGeometry PathGeometry()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry_00()));
            }

            // 矩形路径 4.RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_0()
            {
                if (_roundedRectangle_0 != null) { return _roundedRectangle_0; }
                var result = _roundedRectangle_0 = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(0F, 0F);
                result.Offset = new Vector2(368F, -144F);
                BindProperty(_roundedRectangle_0, "CornerRadius", "Vector2(Min(16,(Min(my.Size.X,my.Size.Y)/2)),Min(16,(Min(my.Size.X,my.Size.Y)/2)))", "my", _roundedRectangle_0);
                BindProperty(_roundedRectangle_0, "Offset", "Vector2(368,-144)-(my.Size/Vector2(2,2))", "my", _roundedRectangle_0);
                return result;
            }

            // 矩形路径 3.RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_1()
            {
                if (_roundedRectangle_1 != null) { return _roundedRectangle_1; }
                var result = _roundedRectangle_1 = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(0F, 0F);
                result.Offset = new Vector2(144F, -144F);
                BindProperty(_roundedRectangle_1, "CornerRadius", "Vector2(Min(16,(Min(my.Size.X,my.Size.Y)/2)),Min(16,(Min(my.Size.X,my.Size.Y)/2)))", "my", _roundedRectangle_1);
                BindProperty(_roundedRectangle_1, "Offset", "Vector2(144,-144)-(my.Size/Vector2(2,2))", "my", _roundedRectangle_1);
                return result;
            }

            // 矩形路径 2.RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_2()
            {
                if (_roundedRectangle_2 != null) { return _roundedRectangle_2; }
                var result = _roundedRectangle_2 = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(0F, 0F);
                result.Offset = new Vector2(368F, -368F);
                BindProperty(_roundedRectangle_2, "CornerRadius", "Vector2(Min(16,(Min(my.Size.X,my.Size.Y)/2)),Min(16,(Min(my.Size.X,my.Size.Y)/2)))", "my", _roundedRectangle_2);
                BindProperty(_roundedRectangle_2, "Offset", "Vector2(368,-368)-(my.Size/Vector2(2,2))", "my", _roundedRectangle_2);
                return result;
            }

            // 矩形路径 1.RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_3()
            {
                if (_roundedRectangle_3 != null) { return _roundedRectangle_3; }
                var result = _roundedRectangle_3 = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(0F, 0F);
                result.Offset = new Vector2(144F, -368F);
                BindProperty(_roundedRectangle_3, "CornerRadius", "Vector2(Min(16,(Min(my.Size.X,my.Size.Y)/2)),Min(16,(Min(my.Size.X,my.Size.Y)/2)))", "my", _roundedRectangle_3);
                BindProperty(_roundedRectangle_3, "Offset", "Vector2(144,-368)-(my.Size/Vector2(2,2))", "my", _roundedRectangle_3);
                return result;
            }

            // Shape tree root for layer: “”轮廓
            // 矩形路径 4
            CompositionSpriteShape SpriteShape_0()
            {
                // Offset:<0, 512>
                var geometry = RoundedRectangle_0();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 0F, 512F), ColorBrush_AlmostLavender_FFEBEBEB());;
                return result;
            }

            // Shape tree root for layer: “”轮廓
            // 矩形路径 3
            CompositionSpriteShape SpriteShape_1()
            {
                // Offset:<0, 512>
                var geometry = RoundedRectangle_1();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 0F, 512F), ColorBrush_AlmostLavender_FFEBEBEB());;
                return result;
            }

            // Shape tree root for layer: “”轮廓
            // 矩形路径 2
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<0, 512>
                var geometry = RoundedRectangle_2();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 0F, 512F), ColorBrush_AlmostLavender_FFEBEBEB());;
                return result;
            }

            // Shape tree root for layer: “”轮廓
            // 矩形路径 1
            CompositionSpriteShape SpriteShape_3()
            {
                // Offset:<0, 512>
                var geometry = RoundedRectangle_3();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 0F, 512F), ColorBrush_AlmostLavender_FFEBEBEB());;
                return result;
            }

            // Shape tree root for layer: “”轮廓
            //  20+ 19+ 18+ 17+ 16+ 15+ 14+ 13+ 12+ 11+ 10+ 9+ 8+ 7+ 6+ 5+ 4+
            // 3+ 2+
            CompositionSpriteShape SpriteShape_4()
            {
                // Offset:<0, 512>
                var geometry = PathGeometry();
                var result = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 0F, 512F), ColorBrush_AlmostLavender_FFEBEBEB());;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Shape tree root for layer: “”轮廓
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F))
                    : _cubicBezierEasingFunction_0;
            }

            // Shape tree root for layer: “”轮廓
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(512F, 512F);
                var shapes = result.Shapes;
                // Offset:<0, 512>
                shapes.Add(SpriteShape_0());
                // Offset:<0, 512>
                shapes.Add(SpriteShape_1());
                // Offset:<0, 512>
                shapes.Add(SpriteShape_2());
                // Offset:<0, 512>
                shapes.Add(SpriteShape_3());
                // Offset:<0, 512>
                shapes.Add(SpriteShape_4());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // 矩形路径 4.RectangleGeometry
            // Size
            Vector2KeyFrameAnimation SizeVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), StepThenHoldEasingFunction());
                // Frame 9.
                result.InsertKeyFrame(0.150000006F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 19.
                result.InsertKeyFrame(0.316666663F, new Vector2(96F, 96F), CubicBezierEasingFunction_0());
                // Frame 40.
                result.InsertKeyFrame(0.666666687F, new Vector2(96F, 96F), CubicBezierEasingFunction_0());
                // Frame 50.
                result.InsertKeyFrame(0.833333313F, new Vector2(0F, 0F), CubicBezierEasingFunction_0());
                return result;
            }

            // 矩形路径 3.RectangleGeometry
            // Size
            Vector2KeyFrameAnimation SizeVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), StepThenHoldEasingFunction());
                // Frame 6.
                result.InsertKeyFrame(0.100000001F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 16.
                result.InsertKeyFrame(0.266666681F, new Vector2(96F, 96F), CubicBezierEasingFunction_0());
                // Frame 40.
                result.InsertKeyFrame(0.666666687F, new Vector2(96F, 96F), CubicBezierEasingFunction_0());
                // Frame 50.
                result.InsertKeyFrame(0.833333313F, new Vector2(0F, 0F), CubicBezierEasingFunction_0());
                return result;
            }

            // 矩形路径 2.RectangleGeometry
            // Size
            Vector2KeyFrameAnimation SizeVector2Animation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), StepThenHoldEasingFunction());
                // Frame 3.
                result.InsertKeyFrame(0.0500000007F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 13.
                result.InsertKeyFrame(0.216666669F, new Vector2(96F, 96F), CubicBezierEasingFunction_0());
                // Frame 40.
                result.InsertKeyFrame(0.666666687F, new Vector2(96F, 96F), CubicBezierEasingFunction_0());
                // Frame 50.
                result.InsertKeyFrame(0.833333313F, new Vector2(0F, 0F), CubicBezierEasingFunction_0());
                return result;
            }

            // 矩形路径 1.RectangleGeometry
            // Size
            Vector2KeyFrameAnimation SizeVector2Animation_3()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.166666672F, new Vector2(96F, 96F), CubicBezierEasingFunction_0());
                // Frame 40.
                result.InsertKeyFrame(0.666666687F, new Vector2(96F, 96F), CubicBezierEasingFunction_0());
                // Frame 50.
                result.InsertKeyFrame(0.833333313F, new Vector2(0F, 0F), CubicBezierEasingFunction_0());
                return result;
            }

            internal SelectAllIcon_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(512F, 512F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _roundedRectangle_0.StartAnimation("Size", SizeVector2Animation_0(), AnimationController_0());
                _roundedRectangle_1.StartAnimation("Size", SizeVector2Animation_1(), AnimationController_0());
                _roundedRectangle_2.StartAnimation("Size", SizeVector2Animation_2(), AnimationController_0());
                _roundedRectangle_3.StartAnimation("Size", SizeVector2Animation_3(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _roundedRectangle_0.StopAnimation("Size");
                _roundedRectangle_1.StopAnimation("Size");
                _roundedRectangle_2.StopAnimation("Size");
                _roundedRectangle_3.StopAnimation("Size");
            }

        }
    }
}
