//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace WE_Tool.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile SortIcon.json
//       
//       Input file:
//           SortIcon.json (7060 bytes created 23:08+08:00 Sep 16 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    36 |
// |--------------------------+-------|
// | Expression animators     |     1 |
// | KeyFrame animators       |     4 |
// | Reference parameters     |     1 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     - |
// | CompositionSpriteShapes  |     4 |
// |--------------------------+-------|
// | Brushes                  |     1 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace WE_Tool.AnimatedVisuals
{
    // Name:        SortToolbarButton
    // Frame rate:  60 fps
    // Frame count: 20
    // Duration:    333.3 mS
    // __________________________________________________________________________________
    // |        Marker         |        Constant         | Frame |  mS   |   Progress   |
    // |_______________________|_________________________|_______|_______|______________|
    // | NormalToPressed_Start | M_NormalToPressed_Start |     0 |   0.0 | 0F           |
    // | NormalToPlaying_Start | M_NormalToPlaying_Start |     0 |   0.0 | 0F           |
    // | NormalToPressed_End   | M_NormalToPressed_End   |    10 | 166.7 | 0.502499998F |
    // | PressedToNormal_Start | M_PressedToNormal_Start |    10 | 166.7 | 0.502499998F |
    // | PressedToNormal_End   | M_PressedToNormal_End   |    20 | 333.3 | 1F           |
    // | NormalToPlaying_End   | M_NormalToPlaying_End   |    20 | 333.3 | 1F           |
    // | PlayingToNormal_Start | M_PlayingToNormal_Start |    20 | 333.3 | 1F           |
    // | PlayingToNormal_End   | M_PlayingToNormal_End   |    20 | 333.3 | 1F           |
    // ----------------------------------------------------------------------------------
    public sealed partial class SortIcon
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 0.333 seconds.
        internal const long c_durationTicks = 3333333;

        // Marker: NormalToPressed_Start.
        internal const float M_NormalToPressed_Start = 0F;

        // Marker: NormalToPlaying_Start.
        internal const float M_NormalToPlaying_Start = 0F;

        // Marker: NormalToPressed_End.
        internal const float M_NormalToPressed_End = 0.502499998F;

        // Marker: PressedToNormal_Start.
        internal const float M_PressedToNormal_Start = 0.502499998F;

        // Marker: PressedToNormal_End.
        internal const float M_PressedToNormal_End = 1F;

        // Marker: NormalToPlaying_End.
        internal const float M_NormalToPlaying_End = 1F;

        // Marker: PlayingToNormal_Start.
        internal const float M_PlayingToNormal_Start = 1F;

        // Marker: PlayingToNormal_End.
        internal const float M_PlayingToNormal_End = 1F;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new SortIcon_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 20d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(3333333);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 20d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "NormalToPressed_Start", 0d },
                { "NormalToPlaying_Start", 0d },
                { "NormalToPressed_End", 0.5025 },
                { "PressedToNormal_Start", 0.5025 },
                { "PressedToNormal_End", 1d },
                { "NormalToPlaying_End", 1d },
                { "PlayingToNormal_Start", 1d },
                { "PlayingToNormal_End", 1d },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed partial class SortIcon_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 3333333;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionColorBrush _colorBrush_AlmostLavender_FFEBEBEB;
            CompositionPathGeometry _pathGeometry_0;
            CompositionPathGeometry _pathGeometry_1;
            CompositionSpriteShape _spriteShape_0;
            CompositionSpriteShape _spriteShape_1;
            CompositionSpriteShape _spriteShape_2;
            CompositionSpriteShape _spriteShape_3;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(507.25F, -219.25F));
                    builder.AddCubicBezier(new Vector2(504.082001F, -222.414001F), new Vector2(500.332001F, -224F), new Vector2(496F, -224F));
                    builder.AddCubicBezier(new Vector2(491.664001F, -224F), new Vector2(487.914001F, -222.414001F), new Vector2(484.75F, -219.25F));
                    builder.AddLine(new Vector2(384F, -118.75F));
                    builder.AddLine(new Vector2(384F, -432F));
                    builder.AddCubicBezier(new Vector2(384F, -436.332001F), new Vector2(382.414001F, -440.082001F), new Vector2(379.25F, -443.25F));
                    builder.AddCubicBezier(new Vector2(376.082001F, -446.414001F), new Vector2(372.332001F, -448F), new Vector2(368F, -448F));
                    builder.AddCubicBezier(new Vector2(363.664001F, -448F), new Vector2(359.914001F, -446.414001F), new Vector2(356.75F, -443.25F));
                    builder.AddCubicBezier(new Vector2(353.582001F, -440.082001F), new Vector2(352F, -436.332001F), new Vector2(352F, -432F));
                    builder.AddLine(new Vector2(352F, -118.75F));
                    builder.AddLine(new Vector2(251.25F, -219.25F));
                    builder.AddCubicBezier(new Vector2(248.082001F, -222.414001F), new Vector2(244.332001F, -224F), new Vector2(240F, -224F));
                    builder.AddCubicBezier(new Vector2(235.664001F, -224F), new Vector2(231.914001F, -222.414001F), new Vector2(228.75F, -219.25F));
                    builder.AddCubicBezier(new Vector2(225.582001F, -216.082001F), new Vector2(224F, -212.332001F), new Vector2(224F, -208F));
                    builder.AddCubicBezier(new Vector2(224F, -203.664001F), new Vector2(225.582001F, -199.914001F), new Vector2(228.75F, -196.75F));
                    builder.AddLine(new Vector2(356F, -69.5F));
                    builder.AddCubicBezier(new Vector2(357.832001F, -67.6640015F), new Vector2(359.625F, -66.2890015F), new Vector2(361.375F, -65.375F));
                    builder.AddCubicBezier(new Vector2(363.125F, -64.4570007F), new Vector2(365.332001F, -64F), new Vector2(368F, -64F));
                    builder.AddCubicBezier(new Vector2(370.664001F, -64F), new Vector2(372.875F, -64.4570007F), new Vector2(374.625F, -65.375F));
                    builder.AddCubicBezier(new Vector2(376.375F, -66.2890015F), new Vector2(378.164001F, -67.6640015F), new Vector2(380F, -69.5F));
                    builder.AddLine(new Vector2(507.25F, -196.75F));
                    builder.AddCubicBezier(new Vector2(510.414001F, -199.914001F), new Vector2(512F, -203.664001F), new Vector2(512F, -208F));
                    builder.AddCubicBezier(new Vector2(512F, -212.332001F), new Vector2(510.414001F, -216.082001F), new Vector2(507.25F, -219.25F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(260.75F, -292.75F));
                    builder.AddCubicBezier(new Vector2(263.914001F, -289.582001F), new Vector2(267.664001F, -288F), new Vector2(272F, -288F));
                    builder.AddCubicBezier(new Vector2(276.332001F, -288F), new Vector2(280.082001F, -289.582001F), new Vector2(283.25F, -292.75F));
                    builder.AddCubicBezier(new Vector2(286.414001F, -295.914001F), new Vector2(288F, -299.664001F), new Vector2(288F, -304F));
                    builder.AddCubicBezier(new Vector2(288F, -308.332001F), new Vector2(286.414001F, -312.082001F), new Vector2(283.25F, -315.25F));
                    builder.AddLine(new Vector2(156F, -442.5F));
                    builder.AddCubicBezier(new Vector2(154.164001F, -444.332001F), new Vector2(152.332001F, -445.707001F), new Vector2(150.5F, -446.625F));
                    builder.AddCubicBezier(new Vector2(148.664001F, -447.539001F), new Vector2(146.5F, -448F), new Vector2(144F, -448F));
                    builder.AddCubicBezier(new Vector2(141.5F, -448F), new Vector2(139.332001F, -447.539001F), new Vector2(137.5F, -446.625F));
                    builder.AddCubicBezier(new Vector2(135.664001F, -445.707001F), new Vector2(133.832001F, -444.332001F), new Vector2(132F, -442.5F));
                    builder.AddLine(new Vector2(4.75F, -315.25F));
                    builder.AddCubicBezier(new Vector2(1.58200002F, -312.082001F), new Vector2(0F, -308.332001F), new Vector2(0F, -304F));
                    builder.AddCubicBezier(new Vector2(0F, -299.664001F), new Vector2(1.58200002F, -295.914001F), new Vector2(4.75F, -292.75F));
                    builder.AddCubicBezier(new Vector2(7.91400003F, -289.582001F), new Vector2(11.6639996F, -288F), new Vector2(16F, -288F));
                    builder.AddCubicBezier(new Vector2(20.3320007F, -288F), new Vector2(24.0820007F, -289.582001F), new Vector2(27.25F, -292.75F));
                    builder.AddLine(new Vector2(128F, -393.5F));
                    builder.AddLine(new Vector2(128F, -80F));
                    builder.AddCubicBezier(new Vector2(128F, -75.6640015F), new Vector2(129.582001F, -71.9140015F), new Vector2(132.75F, -68.75F));
                    builder.AddCubicBezier(new Vector2(135.914001F, -65.5820007F), new Vector2(139.664001F, -64F), new Vector2(144F, -64F));
                    builder.AddCubicBezier(new Vector2(148.332001F, -64F), new Vector2(152.082001F, -65.5820007F), new Vector2(155.25F, -68.75F));
                    builder.AddCubicBezier(new Vector2(158.414001F, -71.9140015F), new Vector2(160F, -75.6640015F), new Vector2(160F, -80F));
                    builder.AddLine(new Vector2(160F, -393.5F));
                    builder.AddLine(new Vector2(260.75F, -292.75F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostLavender_FFEBEBEB()
            {
                return (_colorBrush_AlmostLavender_FFEBEBEB == null)
                    ? _colorBrush_AlmostLavender_FFEBEBEB = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xEB, 0xEB, 0xEB))
                    : _colorBrush_AlmostLavender_FFEBEBEB;
            }

            CompositionPathGeometry PathGeometry_0()
            {
                return (_pathGeometry_0 == null)
                    ? _pathGeometry_0 = _c.CreatePathGeometry(new CompositionPath(Geometry_0()))
                    : _pathGeometry_0;
            }

            CompositionPathGeometry PathGeometry_1()
            {
                return (_pathGeometry_1 == null)
                    ? _pathGeometry_1 = _c.CreatePathGeometry(new CompositionPath(Geometry_1()))
                    : _pathGeometry_1;
            }

            // Layer aggregator
            //  2
            CompositionSpriteShape SpriteShape_0()
            {
                // Offset:<0, 512>
                var geometry = PathGeometry_0();
                if (_spriteShape_0 != null) { return _spriteShape_0; }
                var result = _spriteShape_0 = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 0F, 512F), ColorBrush_AlmostLavender_FFEBEBEB());;
                return result;
            }

            // Layer aggregator
            // 
            CompositionSpriteShape SpriteShape_1()
            {
                // Offset:<0, 512>
                var geometry = PathGeometry_1();
                if (_spriteShape_1 != null) { return _spriteShape_1; }
                var result = _spriteShape_1 = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 0F, 512F), ColorBrush_AlmostLavender_FFEBEBEB());;
                return result;
            }

            // Layer aggregator
            //  2
            CompositionSpriteShape SpriteShape_2()
            {
                // Offset:<0, 512>
                var geometry = PathGeometry_0();
                if (_spriteShape_2 != null) { return _spriteShape_2; }
                var result = _spriteShape_2 = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 0F, 512F), ColorBrush_AlmostLavender_FFEBEBEB());;
                return result;
            }

            // Layer aggregator
            // 
            CompositionSpriteShape SpriteShape_3()
            {
                // Offset:<0, 512>
                var geometry = PathGeometry_1();
                if (_spriteShape_3 != null) { return _spriteShape_3; }
                var result = _spriteShape_3 = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 0F, 512F), ColorBrush_AlmostLavender_FFEBEBEB());;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(512F, 512F);
                var shapes = result.Shapes;
                // Offset:<0, 512>
                shapes.Add(SpriteShape_0());
                // Offset:<0, 512>
                shapes.Add(SpriteShape_1());
                // Offset:<0, 512>
                shapes.Add(SpriteShape_2());
                // Offset:<0, 512>
                shapes.Add(SpriteShape_3());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - Layer aggregator
            // Offset:<0, 512>
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.5F, new Vector2(0F, 254F), CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(1F, new Vector2(0F, 454F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Layer aggregator
            // Offset:<0, 512>
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 0F), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.5F, new Vector2(0F, -254F), CubicBezierEasingFunction_0());
                // Frame 20.
                result.InsertKeyFrame(1F, new Vector2(0F, -454F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Layer aggregator
            // Offset:<0, 512>
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, -448F), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.5F, new Vector2(0F, -448F), HoldThenStepEasingFunction());
                // Frame 19.
                result.InsertKeyFrame(0.949999988F, new Vector2(0F, 0F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Layer aggregator
            // Offset:<0, 512>
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_3()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0F, 448F), StepThenHoldEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.5F, new Vector2(0F, 448F), HoldThenStepEasingFunction());
                // Frame 19.
                result.InsertKeyFrame(0.949999988F, new Vector2(0F, 0F), CubicBezierEasingFunction_0());
                return result;
            }

            internal SortIcon_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(512F, 512F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _spriteShape_0.StartAnimation("Offset", OffsetVector2Animation_0(), AnimationController_0());
                _spriteShape_1.StartAnimation("Offset", OffsetVector2Animation_1(), AnimationController_0());
                _spriteShape_2.StartAnimation("Offset", OffsetVector2Animation_2(), AnimationController_0());
                _spriteShape_3.StartAnimation("Offset", OffsetVector2Animation_3(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _spriteShape_0.StopAnimation("Offset");
                _spriteShape_1.StopAnimation("Offset");
                _spriteShape_2.StopAnimation("Offset");
                _spriteShape_3.StopAnimation("Offset");
            }

        }
    }
}
