//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace WE_Tool.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile SortDirectionAscIcon.json
//       
//       Input file:
//           SortDirectionAscIcon.json (1781 bytes created 13:01+08:00 Sep 17 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    20 |
// |--------------------------+-------|
// | Expression animators     |     1 |
// | KeyFrame animators       |     1 |
// | Reference parameters     |     1 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     1 |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     - |
// | CompositionSpriteShapes  |     1 |
// |--------------------------+-------|
// | Brushes                  |     1 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace WE_Tool.AnimatedVisuals
{
    // Name:        SortDirectionAscIcon
    // Frame rate:  60 fps
    // Frame count: 20
    // Duration:    333.3 mS
    // __________________________________________________________________________________
    // |        Marker         |        Constant         | Frame |  mS   |   Progress   |
    // |_______________________|_________________________|_______|_______|______________|
    // | NormalToPressed_Start | M_NormalToPressed_Start |     0 |   0.0 | 0F           |
    // | NormalToPlaying_Start | M_NormalToPlaying_Start |     0 |   0.0 | 0F           |
    // | NormalToReset_Start   | M_NormalToReset_Start   |     0 |   0.0 | 0F           |
    // | NormalToReset_End     | M_NormalToReset_End     |     0 |   0.0 | 0F           |
    // | ResetToNormal_Start   | M_ResetToNormal_Start   |     0 |   0.0 | 0F           |
    // | ResetToNormal_End     | M_ResetToNormal_End     |     0 |   0.0 | 0F           |
    // | NormalToPressed_End   | M_NormalToPressed_End   |    10 | 166.7 | 0.502499998F |
    // | PressedToNormal_Start | M_PressedToNormal_Start |    10 | 166.7 | 0.502499998F |
    // | PressedToNormal_End   | M_PressedToNormal_End   |    20 | 333.3 | 1F           |
    // | NormalToPlaying_End   | M_NormalToPlaying_End   |    20 | 333.3 | 1F           |
    // | PlayingToNormal_Start | M_PlayingToNormal_Start |    20 | 333.3 | 1F           |
    // | PlayingToNormal_End   | M_PlayingToNormal_End   |    20 | 333.3 | 1F           |
    // ----------------------------------------------------------------------------------
    public sealed class SortDirectionAscIcon
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 0.333 seconds.
        internal const long c_durationTicks = 3333333;

        // Marker: NormalToPressed_Start.
        internal const float M_NormalToPressed_Start = 0F;

        // Marker: NormalToPlaying_Start.
        internal const float M_NormalToPlaying_Start = 0F;

        // Marker: NormalToReset_Start.
        internal const float M_NormalToReset_Start = 0F;

        // Marker: NormalToReset_End.
        internal const float M_NormalToReset_End = 0F;

        // Marker: ResetToNormal_Start.
        internal const float M_ResetToNormal_Start = 0F;

        // Marker: ResetToNormal_End.
        internal const float M_ResetToNormal_End = 0F;

        // Marker: NormalToPressed_End.
        internal const float M_NormalToPressed_End = 0.502499998F;

        // Marker: PressedToNormal_Start.
        internal const float M_PressedToNormal_Start = 0.502499998F;

        // Marker: PressedToNormal_End.
        internal const float M_PressedToNormal_End = 1F;

        // Marker: NormalToPlaying_End.
        internal const float M_NormalToPlaying_End = 1F;

        // Marker: PlayingToNormal_Start.
        internal const float M_PlayingToNormal_Start = 1F;

        // Marker: PlayingToNormal_End.
        internal const float M_PlayingToNormal_End = 1F;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new SortDirectionAscIcon_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 20d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(3333333);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 20d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "NormalToPressed_Start", 0d },
                { "NormalToPlaying_Start", 0d },
                { "NormalToReset_Start", 0d },
                { "NormalToReset_End", 0d },
                { "ResetToNormal_Start", 0d },
                { "ResetToNormal_End", 0d },
                { "NormalToPressed_End", 0.5025 },
                { "PressedToNormal_Start", 0.5025 },
                { "PressedToNormal_End", 1d },
                { "NormalToPlaying_End", 1d },
                { "PlayingToNormal_Start", 1d },
                { "PlayingToNormal_End", 1d },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class SortDirectionAscIcon_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 3333333;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionPathGeometry _pathGeometry;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            PathKeyFrameAnimation CreatePathKeyFrameAnimation(float initialProgress, CompositionPath initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreatePathKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                return result;
            }

            // - - Shape tree root for layer: 形状图层 1
            // -  Offset:<256, 258.576>
            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - - Shape tree root for layer: 形状图层 1
            // - - -  Offset:<256, 258.576>
            // - Path
            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-176.307007F, -90.7160034F));
                    builder.AddCubicBezier(new Vector2(-176.307007F, -90.7160034F), new Vector2(-0.0240000002F, 85.5630035F), new Vector2(-0.0240000002F, 85.5630035F));
                    builder.AddCubicBezier(new Vector2(-0.0240000002F, 85.5630035F), new Vector2(176.080002F, -90.4329987F), new Vector2(176.080002F, -90.4329987F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: 形状图层 1
            // - - -  Offset:<256, 258.576>
            // - Path
            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-175.839005F, 85.2570038F));
                    builder.AddCubicBezier(new Vector2(-175.839005F, 85.2570038F), new Vector2(-0.0240000002F, 85.5630035F), new Vector2(-0.0240000002F, 85.5630035F));
                    builder.AddCubicBezier(new Vector2(-0.0240000002F, 85.5630035F), new Vector2(175.451004F, 85.3079987F), new Vector2(175.451004F, 85.3079987F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - - Shape tree root for layer: 形状图层 1
            // - - -  Offset:<256, 258.576>
            // - Path
            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(-175.839005F, 85.2570038F));
                    builder.AddCubicBezier(new Vector2(-175.839005F, 85.2570038F), new Vector2(-0.0240000002F, -89.8119965F), new Vector2(-0.0240000002F, -89.8119965F));
                    builder.AddCubicBezier(new Vector2(-0.0240000002F, -89.8119965F), new Vector2(175.451004F, 85.3079987F), new Vector2(175.451004F, 85.3079987F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - Shape tree root for layer: 形状图层 1
            // Offset:<256, 258.576>
            CompositionColorBrush ColorBrush_AlmostLavender_FFEBEBEB()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0xEB, 0xEB, 0xEB));
            }

            // - Shape tree root for layer: 形状图层 1
            // Offset:<256, 258.576>
            CompositionPathGeometry PathGeometry()
            {
                if (_pathGeometry != null) { return _pathGeometry; }
                var result = _pathGeometry = _c.CreatePathGeometry();
                return result;
            }

            // Shape tree root for layer: 形状图层 1
            // 路径 1
            CompositionSpriteShape SpriteShape()
            {
                // Offset:<256, 258.576>
                var result = CreateSpriteShape(PathGeometry(), new Matrix3x2(1F, 0F, 0F, 1F, 256F, 258.575989F));;
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Shape tree root for layer: 形状图层 1
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            // - - Shape tree root for layer: 形状图层 1
            // -  Offset:<256, 258.576>
            // Path
            PathKeyFrameAnimation PathKeyFrameAnimation_0()
            {
                // Frame 0.
                var result = CreatePathKeyFrameAnimation(0F, new CompositionPath(Geometry_0()), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.5F, new CompositionPath(Geometry_1()), CubicBezierEasingFunction_0());
                // Frame 19.
                result.InsertKeyFrame(0.949999988F, new CompositionPath(Geometry_2()), CubicBezierEasingFunction_0());
                return result;
            }

            // Shape tree root for layer: 形状图层 1
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(512F, 512F);
                // Offset:<256, 258.576>
                result.Shapes.Add(SpriteShape());
                return result;
            }

            // - - - Shape tree root for layer: 形状图层 1
            // - -  Offset:<256, 258.576>
            // Path
            StepEasingFunction HoldThenStepEasingFunction()
            {
                var result = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            internal SortDirectionAscIcon_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(512F, 512F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _pathGeometry.StartAnimation("Path", PathKeyFrameAnimation_0(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _pathGeometry.StopAnimation("Path");
            }

        }
    }
}
