//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace WE_Tool.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile ViewIcon.json
//       
//       Input file:
//           ViewIcon.json (6650 bytes created 10:27+08:00 Sep 19 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    68 |
// |--------------------------+-------|
// | Expression animators     |     1 |
// | KeyFrame animators       |     6 |
// | Reference parameters     |     1 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     6 |
// | CompositionSpriteShapes  |    12 |
// |--------------------------+-------|
// | Brushes                  |     1 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace WE_Tool.AnimatedVisuals
{
    // Name:        Toolbar_View
    // Frame rate:  60 fps
    // Frame count: 20
    // Duration:    333.3 mS
    // __________________________________________________________________________________
    // |        Marker         |        Constant         | Frame |  mS   |   Progress   |
    // |_______________________|_________________________|_______|_______|______________|
    // | NormalToPressed_Start | M_NormalToPressed_Start |     0 |   0.0 | 0F           |
    // | NormalToPlaying_Start | M_NormalToPlaying_Start |     0 |   0.0 | 0F           |
    // | NormalToPressed_End   | M_NormalToPressed_End   |    10 | 166.7 | 0.502499998F |
    // | PressedToNormal_Start | M_PressedToNormal_Start |    10 | 166.7 | 0.502499998F |
    // | PressedToNormal_End   | M_PressedToNormal_End   |    20 | 333.3 | 1F           |
    // | NormalToPlaying_End   | M_NormalToPlaying_End   |    20 | 333.3 | 1F           |
    // | PlayingToNormal_Start | M_PlayingToNormal_Start |    20 | 333.3 | 1F           |
    // | PlayingToNormal_End   | M_PlayingToNormal_End   |    20 | 333.3 | 1F           |
    // ----------------------------------------------------------------------------------
    public sealed class ViewIcon
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 0.333 seconds.
        internal const long c_durationTicks = 3333333;

        // Marker: NormalToPressed_Start.
        internal const float M_NormalToPressed_Start = 0F;

        // Marker: NormalToPlaying_Start.
        internal const float M_NormalToPlaying_Start = 0F;

        // Marker: NormalToPressed_End.
        internal const float M_NormalToPressed_End = 0.502499998F;

        // Marker: PressedToNormal_Start.
        internal const float M_PressedToNormal_Start = 0.502499998F;

        // Marker: PressedToNormal_End.
        internal const float M_PressedToNormal_End = 1F;

        // Marker: NormalToPlaying_End.
        internal const float M_NormalToPlaying_End = 1F;

        // Marker: PlayingToNormal_Start.
        internal const float M_PlayingToNormal_Start = 1F;

        // Marker: PlayingToNormal_End.
        internal const float M_PlayingToNormal_End = 1F;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new ViewIcon_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 20d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(3333333);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 20d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "NormalToPressed_Start", 0d },
                { "NormalToPlaying_Start", 0d },
                { "NormalToPressed_End", 0.5025 },
                { "PressedToNormal_Start", 0.5025 },
                { "PressedToNormal_End", 1d },
                { "NormalToPlaying_End", 1d },
                { "PlayingToNormal_Start", 1d },
                { "PlayingToNormal_End", 1d },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed class ViewIcon_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 3333333;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionColorBrush _colorBrush_AlmostLavender_FFEBEBEB;
            CompositionContainerShape _containerShape_0;
            CompositionContainerShape _containerShape_1;
            CompositionContainerShape _containerShape_2;
            CompositionContainerShape _containerShape_3;
            CompositionContainerShape _containerShape_4;
            CompositionContainerShape _containerShape_5;
            CompositionPathGeometry _pathGeometry;
            CompositionRoundedRectangleGeometry _roundedRectangle_97;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            CanvasGeometry Geometry()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(111.858002F, -16.1140003F));
                    builder.AddLine(new Vector2(367.5F, -16.0359993F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostLavender_FFEBEBEB()
            {
                return (_colorBrush_AlmostLavender_FFEBEBEB == null)
                    ? _colorBrush_AlmostLavender_FFEBEBEB = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xEB, 0xEB, 0xEB))
                    : _colorBrush_AlmostLavender_FFEBEBEB;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_0()
            {
                if (_containerShape_0 != null) { return _containerShape_0; }
                var result = _containerShape_0 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // 路径 1
                shapes.Add(SpriteShape_00());
                // 矩形路径 1
                shapes.Add(SpriteShape_01());
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_1()
            {
                if (_containerShape_1 != null) { return _containerShape_1; }
                var result = _containerShape_1 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // 路径 1
                shapes.Add(SpriteShape_02());
                // 矩形路径 1
                shapes.Add(SpriteShape_03());
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_2()
            {
                if (_containerShape_2 != null) { return _containerShape_2; }
                var result = _containerShape_2 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // 路径 1
                shapes.Add(SpriteShape_04());
                // 矩形路径 1
                shapes.Add(SpriteShape_05());
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_3()
            {
                if (_containerShape_3 != null) { return _containerShape_3; }
                var result = _containerShape_3 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // 路径 1
                shapes.Add(SpriteShape_06());
                // 矩形路径 1
                shapes.Add(SpriteShape_07());
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_4()
            {
                if (_containerShape_4 != null) { return _containerShape_4; }
                var result = _containerShape_4 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // 路径 1
                shapes.Add(SpriteShape_08());
                // 矩形路径 1
                shapes.Add(SpriteShape_09());
                return result;
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape_5()
            {
                if (_containerShape_5 != null) { return _containerShape_5; }
                var result = _containerShape_5 = _c.CreateContainerShape();
                var shapes = result.Shapes;
                // 路径 1
                shapes.Add(SpriteShape_10());
                // 矩形路径 1
                shapes.Add(SpriteShape_11());
                return result;
            }

            CompositionPathGeometry PathGeometry()
            {
                return (_pathGeometry == null)
                    ? _pathGeometry = _c.CreatePathGeometry(new CompositionPath(Geometry()))
                    : _pathGeometry;
            }

            // 矩形路径 1.RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_97()
            {
                if (_roundedRectangle_97 != null) { return _roundedRectangle_97; }
                var result = _roundedRectangle_97 = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(17F, 17F);
                result.Offset = new Vector2(-48.5F, -48.5F);
                result.Size = new Vector2(97F, 97F);
                return result;
            }

            // - Layer aggregator
            // 路径 1
            CompositionSpriteShape SpriteShape_00()
            {
                var result = _c.CreateSpriteShape(PathGeometry());
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // - Layer aggregator
            // 矩形路径 1
            CompositionSpriteShape SpriteShape_01()
            {
                var result = _c.CreateSpriteShape(RoundedRectangle_97());
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // - Layer aggregator
            // 路径 1
            CompositionSpriteShape SpriteShape_02()
            {
                var result = _c.CreateSpriteShape(PathGeometry());
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // - Layer aggregator
            // 矩形路径 1
            CompositionSpriteShape SpriteShape_03()
            {
                var result = _c.CreateSpriteShape(RoundedRectangle_97());
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // - Layer aggregator
            // 路径 1
            CompositionSpriteShape SpriteShape_04()
            {
                var result = _c.CreateSpriteShape(PathGeometry());
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // - Layer aggregator
            // 矩形路径 1
            CompositionSpriteShape SpriteShape_05()
            {
                var result = _c.CreateSpriteShape(RoundedRectangle_97());
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // - Layer aggregator
            // 路径 1
            CompositionSpriteShape SpriteShape_06()
            {
                var result = _c.CreateSpriteShape(PathGeometry());
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // - Layer aggregator
            // 矩形路径 1
            CompositionSpriteShape SpriteShape_07()
            {
                var result = _c.CreateSpriteShape(RoundedRectangle_97());
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // - Layer aggregator
            // 路径 1
            CompositionSpriteShape SpriteShape_08()
            {
                var result = _c.CreateSpriteShape(PathGeometry());
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // - Layer aggregator
            // 矩形路径 1
            CompositionSpriteShape SpriteShape_09()
            {
                var result = _c.CreateSpriteShape(RoundedRectangle_97());
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // - Layer aggregator
            // 路径 1
            CompositionSpriteShape SpriteShape_10()
            {
                var result = _c.CreateSpriteShape(PathGeometry());
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // - Layer aggregator
            // 矩形路径 1
            CompositionSpriteShape SpriteShape_11()
            {
                var result = _c.CreateSpriteShape(RoundedRectangle_97());
                result.StrokeBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 32F;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(512F, 512F);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape_0());
                shapes.Add(ContainerShape_1());
                shapes.Add(ContainerShape_2());
                shapes.Add(ContainerShape_3());
                shapes.Add(ContainerShape_4());
                shapes.Add(ContainerShape_5());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_0()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(96F, 416F), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.5F, new Vector2(96F, 506F), CubicBezierEasingFunction_0());
                // Frame 15.
                result.InsertKeyFrame(0.75F, new Vector2(96F, 626F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_1()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(96F, 256F), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.5F, new Vector2(96F, 296F), CubicBezierEasingFunction_0());
                // Frame 15.
                result.InsertKeyFrame(0.75F, new Vector2(96F, 616F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_2()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(96F, 96F), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.5F, new Vector2(96F, 106F), CubicBezierEasingFunction_0());
                // Frame 15.
                result.InsertKeyFrame(0.75F, new Vector2(96F, 596F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_3()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(96F, -66F), StepThenHoldEasingFunction());
                // Frame 14.
                result.InsertKeyFrame(0.699999988F, new Vector2(96F, -66F), HoldThenStepEasingFunction());
                // Frame 20.
                result.InsertKeyFrame(1F, new Vector2(96F, 416F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_4()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(96F, -226F), StepThenHoldEasingFunction());
                // Frame 14.
                result.InsertKeyFrame(0.699999988F, new Vector2(96F, -226F), HoldThenStepEasingFunction());
                // Frame 20.
                result.InsertKeyFrame(1F, new Vector2(96F, 256F), CubicBezierEasingFunction_0());
                return result;
            }

            // - Layer aggregator
            // Offset
            Vector2KeyFrameAnimation OffsetVector2Animation_5()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(96F, -386F), StepThenHoldEasingFunction());
                // Frame 14.
                result.InsertKeyFrame(0.699999988F, new Vector2(96F, -386F), HoldThenStepEasingFunction());
                // Frame 20.
                result.InsertKeyFrame(1F, new Vector2(96F, 96F), CubicBezierEasingFunction_0());
                return result;
            }

            internal ViewIcon_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(512F, 512F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _containerShape_0.StartAnimation("Offset", OffsetVector2Animation_0(), AnimationController_0());
                _containerShape_1.StartAnimation("Offset", OffsetVector2Animation_1(), AnimationController_0());
                _containerShape_2.StartAnimation("Offset", OffsetVector2Animation_2(), AnimationController_0());
                _containerShape_3.StartAnimation("Offset", OffsetVector2Animation_3(), AnimationController_0());
                _containerShape_4.StartAnimation("Offset", OffsetVector2Animation_4(), AnimationController_0());
                _containerShape_5.StartAnimation("Offset", OffsetVector2Animation_5(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _containerShape_0.StopAnimation("Offset");
                _containerShape_1.StopAnimation("Offset");
                _containerShape_2.StopAnimation("Offset");
                _containerShape_3.StopAnimation("Offset");
                _containerShape_4.StopAnimation("Offset");
                _containerShape_5.StopAnimation("Offset");
            }

        }
    }
}
