//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace WE_Tool.AnimatedVisuals -Public -WinUIVersion 3.0 -InputFile WallpaperBackupIcon.json
//       
//       Input file:
//           WallpaperBackupIcon.json (9358 bytes created 13:19+08:00 Sep 16 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |    38 |
// |--------------------------+-------|
// | Expression animators     |     1 |
// | KeyFrame animators       |     4 |
// | Reference parameters     |     1 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     - |
// | Animated gradient stops  |     - |
// | ExpressionAnimations     |     1 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     - |
// | CompositionSpriteShapes  |     3 |
// |--------------------------+-------|
// | Brushes                  |     2 |
// | Gradient stops           |     - |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace WE_Tool.AnimatedVisuals
{
    // Name:        BackupPage
    // Frame rate:  60 fps
    // Frame count: 40
    // Duration:    666.7 mS
    // ____________________________________________________________________________________________________________________________
    // |                   Marker                   |                   Constant                   | Frame |  mS   |   Progress   |
    // |____________________________________________|______________________________________________|_______|_______|______________|
    // | NormalToPointerOver_Start                  | M_NormalToPointerOver_Start                  |     0 |   0.0 | 0F           |
    // | NormalToPointerOver_End                    | M_NormalToPointerOver_End                    |     0 |   0.0 | 0F           |
    // | NormalToPressed_Start                      | M_NormalToPressed_Start                      |     0 |   0.0 | 0F           |
    // | NormalToSelected_Start                     | M_NormalToSelected_Start                     |     0 |   0.0 | 0F           |
    // | NormalToSelected_End                       | M_NormalToSelected_End                       |     0 |   0.0 | 0F           |
    // | NormalToPressedSelected_Start              | M_NormalToPressedSelected_Start              |     0 |   0.0 | 0F           |
    // | NormalToPointerOverSelected_Start          | M_NormalToPointerOverSelected_Start          |     0 |   0.0 | 0F           |
    // | NormalToPointerOverSelected_End            | M_NormalToPointerOverSelected_End            |     0 |   0.0 | 0F           |
    // | PointerOverToNormal_Start                  | M_PointerOverToNormal_Start                  |     0 |   0.0 | 0F           |
    // | PointerOverToNormal_End                    | M_PointerOverToNormal_End                    |     0 |   0.0 | 0F           |
    // | PointerOverToPressed_Start                 | M_PointerOverToPressed_Start                 |     0 |   0.0 | 0F           |
    // | PointerOverToSelected_Start                | M_PointerOverToSelected_Start                |     0 |   0.0 | 0F           |
    // | PointerOverToSelected_End                  | M_PointerOverToSelected_End                  |     0 |   0.0 | 0F           |
    // | PointerOverToPressedSelected_Start         | M_PointerOverToPressedSelected_Start         |     0 |   0.0 | 0F           |
    // | PointerOverToPointerOverSelected_Start     | M_PointerOverToPointerOverSelected_Start     |     0 |   0.0 | 0F           |
    // | PointerOverToPointerOverSelected_End       | M_PointerOverToPointerOverSelected_End       |     0 |   0.0 | 0F           |
    // | PressedToPressedSelected_Start             | M_PressedToPressedSelected_Start             |     0 |   0.0 | 0F           |
    // | SelectedToNormal_Start                     | M_SelectedToNormal_Start                     |     0 |   0.0 | 0F           |
    // | SelectedToNormal_End                       | M_SelectedToNormal_End                       |     0 |   0.0 | 0F           |
    // | SelectedToPointerOver_Start                | M_SelectedToPointerOver_Start                |     0 |   0.0 | 0F           |
    // | SelectedToPointerOver_End                  | M_SelectedToPointerOver_End                  |     0 |   0.0 | 0F           |
    // | SelectedToPressed_Start                    | M_SelectedToPressed_Start                    |     0 |   0.0 | 0F           |
    // | SelectedToPressedSelected_Start            | M_SelectedToPressedSelected_Start            |     0 |   0.0 | 0F           |
    // | SelectedToPointerOverSelected_Start        | M_SelectedToPointerOverSelected_Start        |     0 |   0.0 | 0F           |
    // | SelectedToPointerOverSelected_End          | M_SelectedToPointerOverSelected_End          |     0 |   0.0 | 0F           |
    // | PressedSelectedToPressed_Start             | M_PressedSelectedToPressed_Start             |     0 |   0.0 | 0F           |
    // | PointerOverSelectedToNormal_Start          | M_PointerOverSelectedToNormal_Start          |     0 |   0.0 | 0F           |
    // | PointerOverSelectedToNormal_End            | M_PointerOverSelectedToNormal_End            |     0 |   0.0 | 0F           |
    // | PointerOverSelectedToPointerOver_Start     | M_PointerOverSelectedToPointerOver_Start     |     0 |   0.0 | 0F           |
    // | PointerOverSelectedToPointerOver_End       | M_PointerOverSelectedToPointerOver_End       |     0 |   0.0 | 0F           |
    // | PointerOverSelectedToPressed_Start         | M_PointerOverSelectedToPressed_Start         |     0 |   0.0 | 0F           |
    // | PointerOverSelectedToSelected_Start        | M_PointerOverSelectedToSelected_Start        |     0 |   0.0 | 0F           |
    // | PointerOverSelectedToSelected_End          | M_PointerOverSelectedToSelected_End          |     0 |   0.0 | 0F           |
    // | PointerOverSelectedToPressedSelected_Start | M_PointerOverSelectedToPressedSelected_Start |     0 |   0.0 | 0F           |
    // | NormalToPressed_End                        | M_NormalToPressed_End                        |    10 | 166.7 | 0.251249999F |
    // | NormalToPressedSelected_End                | M_NormalToPressedSelected_End                |    10 | 166.7 | 0.251249999F |
    // | PointerOverToPressed_End                   | M_PointerOverToPressed_End                   |    10 | 166.7 | 0.251249999F |
    // | PointerOverToPressedSelected_End           | M_PointerOverToPressedSelected_End           |    10 | 166.7 | 0.251249999F |
    // | PressedToNormal_Start                      | M_PressedToNormal_Start                      |    10 | 166.7 | 0.251249999F |
    // | PressedToPointerOver_Start                 | M_PressedToPointerOver_Start                 |    10 | 166.7 | 0.251249999F |
    // | PressedToSelected_Start                    | M_PressedToSelected_Start                    |    10 | 166.7 | 0.251249999F |
    // | PressedToPressedSelected_End               | M_PressedToPressedSelected_End               |    10 | 166.7 | 0.251249999F |
    // | PressedToPointerOverSelected_Start         | M_PressedToPointerOverSelected_Start         |    10 | 166.7 | 0.251249999F |
    // | SelectedToPressed_End                      | M_SelectedToPressed_End                      |    10 | 166.7 | 0.251249999F |
    // | SelectedToPressedSelected_End              | M_SelectedToPressedSelected_End              |    10 | 166.7 | 0.251249999F |
    // | PressedSelectedToNormal_Start              | M_PressedSelectedToNormal_Start              |    10 | 166.7 | 0.251249999F |
    // | PressedSelectedToPointerOver_Start         | M_PressedSelectedToPointerOver_Start         |    10 | 166.7 | 0.251249999F |
    // | PressedSelectedToPressed_End               | M_PressedSelectedToPressed_End               |    10 | 166.7 | 0.251249999F |
    // | PressedSelectedToSelected_Start            | M_PressedSelectedToSelected_Start            |    10 | 166.7 | 0.251249999F |
    // | PressedSelectedToPointerOverSelected_Start | M_PressedSelectedToPointerOverSelected_Start |    10 | 166.7 | 0.251249999F |
    // | PointerOverSelectedToPressed_End           | M_PointerOverSelectedToPressed_End           |    10 | 166.7 | 0.251249999F |
    // | PointerOverSelectedToPressedSelected_End   | M_PointerOverSelectedToPressedSelected_End   |    10 | 166.7 | 0.251249999F |
    // | PressedToNormal_End                        | M_PressedToNormal_End                        |    40 | 666.7 | 1F           |
    // | PressedToPointerOver_End                   | M_PressedToPointerOver_End                   |    40 | 666.7 | 1F           |
    // | PressedToSelected_End                      | M_PressedToSelected_End                      |    40 | 666.7 | 1F           |
    // | PressedToPointerOverSelected_End           | M_PressedToPointerOverSelected_End           |    40 | 666.7 | 1F           |
    // | PressedSelectedToNormal_End                | M_PressedSelectedToNormal_End                |    40 | 666.7 | 1F           |
    // | PressedSelectedToPointerOver_End           | M_PressedSelectedToPointerOver_End           |    40 | 666.7 | 1F           |
    // | PressedSelectedToSelected_End              | M_PressedSelectedToSelected_End              |    40 | 666.7 | 1F           |
    // | PressedSelectedToPointerOverSelected_End   | M_PressedSelectedToPointerOverSelected_End   |    40 | 666.7 | 1F           |
    // ----------------------------------------------------------------------------------------------------------------------------
    public sealed partial class WallpaperBackupIcon
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 0.667 seconds.
        internal const long c_durationTicks = 6666666;

        // Marker: NormalToPointerOver_Start.
        internal const float M_NormalToPointerOver_Start = 0F;

        // Marker: NormalToPointerOver_End.
        internal const float M_NormalToPointerOver_End = 0F;

        // Marker: NormalToPressed_Start.
        internal const float M_NormalToPressed_Start = 0F;

        // Marker: NormalToSelected_Start.
        internal const float M_NormalToSelected_Start = 0F;

        // Marker: NormalToSelected_End.
        internal const float M_NormalToSelected_End = 0F;

        // Marker: NormalToPressedSelected_Start.
        internal const float M_NormalToPressedSelected_Start = 0F;

        // Marker: NormalToPointerOverSelected_Start.
        internal const float M_NormalToPointerOverSelected_Start = 0F;

        // Marker: NormalToPointerOverSelected_End.
        internal const float M_NormalToPointerOverSelected_End = 0F;

        // Marker: PointerOverToNormal_Start.
        internal const float M_PointerOverToNormal_Start = 0F;

        // Marker: PointerOverToNormal_End.
        internal const float M_PointerOverToNormal_End = 0F;

        // Marker: PointerOverToPressed_Start.
        internal const float M_PointerOverToPressed_Start = 0F;

        // Marker: PointerOverToSelected_Start.
        internal const float M_PointerOverToSelected_Start = 0F;

        // Marker: PointerOverToSelected_End.
        internal const float M_PointerOverToSelected_End = 0F;

        // Marker: PointerOverToPressedSelected_Start.
        internal const float M_PointerOverToPressedSelected_Start = 0F;

        // Marker: PointerOverToPointerOverSelected_Start.
        internal const float M_PointerOverToPointerOverSelected_Start = 0F;

        // Marker: PointerOverToPointerOverSelected_End.
        internal const float M_PointerOverToPointerOverSelected_End = 0F;

        // Marker: PressedToPressedSelected_Start.
        internal const float M_PressedToPressedSelected_Start = 0F;

        // Marker: SelectedToNormal_Start.
        internal const float M_SelectedToNormal_Start = 0F;

        // Marker: SelectedToNormal_End.
        internal const float M_SelectedToNormal_End = 0F;

        // Marker: SelectedToPointerOver_Start.
        internal const float M_SelectedToPointerOver_Start = 0F;

        // Marker: SelectedToPointerOver_End.
        internal const float M_SelectedToPointerOver_End = 0F;

        // Marker: SelectedToPressed_Start.
        internal const float M_SelectedToPressed_Start = 0F;

        // Marker: SelectedToPressedSelected_Start.
        internal const float M_SelectedToPressedSelected_Start = 0F;

        // Marker: SelectedToPointerOverSelected_Start.
        internal const float M_SelectedToPointerOverSelected_Start = 0F;

        // Marker: SelectedToPointerOverSelected_End.
        internal const float M_SelectedToPointerOverSelected_End = 0F;

        // Marker: PressedSelectedToPressed_Start.
        internal const float M_PressedSelectedToPressed_Start = 0F;

        // Marker: PointerOverSelectedToNormal_Start.
        internal const float M_PointerOverSelectedToNormal_Start = 0F;

        // Marker: PointerOverSelectedToNormal_End.
        internal const float M_PointerOverSelectedToNormal_End = 0F;

        // Marker: PointerOverSelectedToPointerOver_Start.
        internal const float M_PointerOverSelectedToPointerOver_Start = 0F;

        // Marker: PointerOverSelectedToPointerOver_End.
        internal const float M_PointerOverSelectedToPointerOver_End = 0F;

        // Marker: PointerOverSelectedToPressed_Start.
        internal const float M_PointerOverSelectedToPressed_Start = 0F;

        // Marker: PointerOverSelectedToSelected_Start.
        internal const float M_PointerOverSelectedToSelected_Start = 0F;

        // Marker: PointerOverSelectedToSelected_End.
        internal const float M_PointerOverSelectedToSelected_End = 0F;

        // Marker: PointerOverSelectedToPressedSelected_Start.
        internal const float M_PointerOverSelectedToPressedSelected_Start = 0F;

        // Marker: NormalToPressed_End.
        internal const float M_NormalToPressed_End = 0.251249999F;

        // Marker: NormalToPressedSelected_End.
        internal const float M_NormalToPressedSelected_End = 0.251249999F;

        // Marker: PointerOverToPressed_End.
        internal const float M_PointerOverToPressed_End = 0.251249999F;

        // Marker: PointerOverToPressedSelected_End.
        internal const float M_PointerOverToPressedSelected_End = 0.251249999F;

        // Marker: PressedToNormal_Start.
        internal const float M_PressedToNormal_Start = 0.251249999F;

        // Marker: PressedToPointerOver_Start.
        internal const float M_PressedToPointerOver_Start = 0.251249999F;

        // Marker: PressedToSelected_Start.
        internal const float M_PressedToSelected_Start = 0.251249999F;

        // Marker: PressedToPressedSelected_End.
        internal const float M_PressedToPressedSelected_End = 0.251249999F;

        // Marker: PressedToPointerOverSelected_Start.
        internal const float M_PressedToPointerOverSelected_Start = 0.251249999F;

        // Marker: SelectedToPressed_End.
        internal const float M_SelectedToPressed_End = 0.251249999F;

        // Marker: SelectedToPressedSelected_End.
        internal const float M_SelectedToPressedSelected_End = 0.251249999F;

        // Marker: PressedSelectedToNormal_Start.
        internal const float M_PressedSelectedToNormal_Start = 0.251249999F;

        // Marker: PressedSelectedToPointerOver_Start.
        internal const float M_PressedSelectedToPointerOver_Start = 0.251249999F;

        // Marker: PressedSelectedToPressed_End.
        internal const float M_PressedSelectedToPressed_End = 0.251249999F;

        // Marker: PressedSelectedToSelected_Start.
        internal const float M_PressedSelectedToSelected_Start = 0.251249999F;

        // Marker: PressedSelectedToPointerOverSelected_Start.
        internal const float M_PressedSelectedToPointerOverSelected_Start = 0.251249999F;

        // Marker: PointerOverSelectedToPressed_End.
        internal const float M_PointerOverSelectedToPressed_End = 0.251249999F;

        // Marker: PointerOverSelectedToPressedSelected_End.
        internal const float M_PointerOverSelectedToPressedSelected_End = 0.251249999F;

        // Marker: PressedToNormal_End.
        internal const float M_PressedToNormal_End = 1F;

        // Marker: PressedToPointerOver_End.
        internal const float M_PressedToPointerOver_End = 1F;

        // Marker: PressedToSelected_End.
        internal const float M_PressedToSelected_End = 1F;

        // Marker: PressedToPointerOverSelected_End.
        internal const float M_PressedToPointerOverSelected_End = 1F;

        // Marker: PressedSelectedToNormal_End.
        internal const float M_PressedSelectedToNormal_End = 1F;

        // Marker: PressedSelectedToPointerOver_End.
        internal const float M_PressedSelectedToPointerOver_End = 1F;

        // Marker: PressedSelectedToSelected_End.
        internal const float M_PressedSelectedToSelected_End = 1F;

        // Marker: PressedSelectedToPointerOverSelected_End.
        internal const float M_PressedSelectedToPointerOverSelected_End = 1F;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new WallpaperBackupIcon_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 40d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(6666666);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 40d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "NormalToPointerOver_Start", 0d },
                { "NormalToPointerOver_End", 0d },
                { "NormalToPressed_Start", 0d },
                { "NormalToSelected_Start", 0d },
                { "NormalToSelected_End", 0d },
                { "NormalToPressedSelected_Start", 0d },
                { "NormalToPointerOverSelected_Start", 0d },
                { "NormalToPointerOverSelected_End", 0d },
                { "PointerOverToNormal_Start", 0d },
                { "PointerOverToNormal_End", 0d },
                { "PointerOverToPressed_Start", 0d },
                { "PointerOverToSelected_Start", 0d },
                { "PointerOverToSelected_End", 0d },
                { "PointerOverToPressedSelected_Start", 0d },
                { "PointerOverToPointerOverSelected_Start", 0d },
                { "PointerOverToPointerOverSelected_End", 0d },
                { "PressedToPressedSelected_Start", 0d },
                { "SelectedToNormal_Start", 0d },
                { "SelectedToNormal_End", 0d },
                { "SelectedToPointerOver_Start", 0d },
                { "SelectedToPointerOver_End", 0d },
                { "SelectedToPressed_Start", 0d },
                { "SelectedToPressedSelected_Start", 0d },
                { "SelectedToPointerOverSelected_Start", 0d },
                { "SelectedToPointerOverSelected_End", 0d },
                { "PressedSelectedToPressed_Start", 0d },
                { "PointerOverSelectedToNormal_Start", 0d },
                { "PointerOverSelectedToNormal_End", 0d },
                { "PointerOverSelectedToPointerOver_Start", 0d },
                { "PointerOverSelectedToPointerOver_End", 0d },
                { "PointerOverSelectedToPressed_Start", 0d },
                { "PointerOverSelectedToSelected_Start", 0d },
                { "PointerOverSelectedToSelected_End", 0d },
                { "PointerOverSelectedToPressedSelected_Start", 0d },
                { "NormalToPressed_End", 0.25125 },
                { "NormalToPressedSelected_End", 0.25125 },
                { "PointerOverToPressed_End", 0.25125 },
                { "PointerOverToPressedSelected_End", 0.25125 },
                { "PressedToNormal_Start", 0.25125 },
                { "PressedToPointerOver_Start", 0.25125 },
                { "PressedToSelected_Start", 0.25125 },
                { "PressedToPressedSelected_End", 0.25125 },
                { "PressedToPointerOverSelected_Start", 0.25125 },
                { "SelectedToPressed_End", 0.25125 },
                { "SelectedToPressedSelected_End", 0.25125 },
                { "PressedSelectedToNormal_Start", 0.25125 },
                { "PressedSelectedToPointerOver_Start", 0.25125 },
                { "PressedSelectedToPressed_End", 0.25125 },
                { "PressedSelectedToSelected_Start", 0.25125 },
                { "PressedSelectedToPointerOverSelected_Start", 0.25125 },
                { "PointerOverSelectedToPressed_End", 0.25125 },
                { "PointerOverSelectedToPressedSelected_End", 0.25125 },
                { "PressedToNormal_End", 1d },
                { "PressedToPointerOver_End", 1d },
                { "PressedToSelected_End", 1d },
                { "PressedToPointerOverSelected_End", 1d },
                { "PressedSelectedToNormal_End", 1d },
                { "PressedSelectedToPointerOver_End", 1d },
                { "PressedSelectedToSelected_End", 1d },
                { "PressedSelectedToPointerOverSelected_End", 1d },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed partial class WallpaperBackupIcon_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 6666666;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionColorBrush _colorBrush_AlmostLavender_FFEBEBEB;
            CompositionSpriteShape _spriteShape_0;
            CompositionSpriteShape _spriteShape_1;
            CompositionSpriteShape _spriteShape_2;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            StepEasingFunction _holdThenStepEasingFunction;
            StepEasingFunction _stepThenHoldEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            CompositionSpriteShape CreateSpriteShape(CompositionGeometry geometry, Matrix3x2 transformMatrix, CompositionBrush fillBrush)
            {
                var result = _c.CreateSpriteShape(geometry);
                result.TransformMatrix = transformMatrix;
                result.FillBrush = fillBrush;
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - Layer aggregator
            // - -  Offset:<0.125, 512.125>
            CanvasGeometry Geometry()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(502.625F, -324F));
                    builder.AddCubicBezier(new Vector2(496.539001F, -345.832001F), new Vector2(487.957001F, -366.207001F), new Vector2(476.875F, -385.125F));
                    builder.AddCubicBezier(new Vector2(465.789001F, -404.039001F), new Vector2(452.457001F, -421.289001F), new Vector2(436.875F, -436.875F));
                    builder.AddCubicBezier(new Vector2(421.289001F, -452.457001F), new Vector2(404.039001F, -465.832001F), new Vector2(385.125F, -477F));
                    builder.AddCubicBezier(new Vector2(366.207001F, -488.164001F), new Vector2(345.832001F, -496.789001F), new Vector2(324F, -502.875F));
                    builder.AddCubicBezier(new Vector2(302.164001F, -508.957001F), new Vector2(279.5F, -512F), new Vector2(256F, -512F));
                    builder.AddCubicBezier(new Vector2(237.5F, -512F), new Vector2(219.414001F, -510.082001F), new Vector2(201.75F, -506.25F));
                    builder.AddCubicBezier(new Vector2(184.082001F, -502.414001F), new Vector2(167.082001F, -496.832001F), new Vector2(150.75F, -489.5F));
                    builder.AddCubicBezier(new Vector2(134.414001F, -482.164001F), new Vector2(118.914001F, -473.125F), new Vector2(104.25F, -462.375F));
                    builder.AddCubicBezier(new Vector2(89.5820007F, -451.625F), new Vector2(76.1640015F, -439.332001F), new Vector2(64F, -425.5F));
                    builder.AddLine(new Vector2(64F, -496F));
                    builder.AddCubicBezier(new Vector2(64F, -500.332001F), new Vector2(62.4140015F, -504.082001F), new Vector2(59.25F, -507.25F));
                    builder.AddCubicBezier(new Vector2(56.0820007F, -510.414001F), new Vector2(52.3320007F, -512F), new Vector2(48F, -512F));
                    builder.AddCubicBezier(new Vector2(43.6640015F, -512F), new Vector2(39.9140015F, -510.414001F), new Vector2(36.75F, -507.25F));
                    builder.AddCubicBezier(new Vector2(33.5820007F, -504.082001F), new Vector2(32F, -500.332001F), new Vector2(32F, -496F));
                    builder.AddLine(new Vector2(32F, -465.75F));
                    builder.AddLine(new Vector2(31.75F, -405.75F));
                    builder.AddLine(new Vector2(31.75F, -375.5F));
                    builder.AddCubicBezier(new Vector2(31.75F, -372.664001F), new Vector2(31.9139996F, -369.875F), new Vector2(32.25F, -367.125F));
                    builder.AddCubicBezier(new Vector2(32.5820007F, -364.375F), new Vector2(33.3320007F, -361.875F), new Vector2(34.5F, -359.625F));
                    builder.AddCubicBezier(new Vector2(35.6640015F, -357.375F), new Vector2(37.3320007F, -355.539001F), new Vector2(39.5F, -354.125F));
                    builder.AddCubicBezier(new Vector2(41.6640015F, -352.707001F), new Vector2(44.5F, -352F), new Vector2(48F, -352F));
                    builder.AddLine(new Vector2(176F, -352F));
                    builder.AddCubicBezier(new Vector2(180.332001F, -352F), new Vector2(184.082001F, -353.582001F), new Vector2(187.25F, -356.75F));
                    builder.AddCubicBezier(new Vector2(190.414001F, -359.914001F), new Vector2(192F, -363.664001F), new Vector2(192F, -368F));
                    builder.AddCubicBezier(new Vector2(192F, -372.332001F), new Vector2(190.414001F, -376.082001F), new Vector2(187.25F, -379.25F));
                    builder.AddCubicBezier(new Vector2(184.082001F, -382.414001F), new Vector2(180.332001F, -384F), new Vector2(176F, -384F));
                    builder.AddLine(new Vector2(72.25F, -384F));
                    builder.AddCubicBezier(new Vector2(82.5820007F, -399F), new Vector2(94.5390015F, -412.414001F), new Vector2(108.125F, -424.25F));
                    builder.AddCubicBezier(new Vector2(121.707001F, -436.082001F), new Vector2(136.375F, -446.125F), new Vector2(152.125F, -454.375F));
                    builder.AddCubicBezier(new Vector2(167.875F, -462.625F), new Vector2(184.5F, -468.957001F), new Vector2(202F, -473.375F));
                    builder.AddCubicBezier(new Vector2(219.5F, -477.789001F), new Vector2(237.414001F, -480F), new Vector2(255.75F, -480F));
                    builder.AddCubicBezier(new Vector2(276.414001F, -480F), new Vector2(296.289001F, -477.332001F), new Vector2(315.375F, -472F));
                    builder.AddCubicBezier(new Vector2(334.457001F, -466.664001F), new Vector2(352.289001F, -459.125F), new Vector2(368.875F, -449.375F));
                    builder.AddCubicBezier(new Vector2(385.457001F, -439.625F), new Vector2(400.539001F, -427.957001F), new Vector2(414.125F, -414.375F));
                    builder.AddCubicBezier(new Vector2(427.707001F, -400.789001F), new Vector2(439.375F, -385.707001F), new Vector2(449.125F, -369.125F));
                    builder.AddCubicBezier(new Vector2(458.875F, -352.539001F), new Vector2(466.414001F, -334.707001F), new Vector2(471.75F, -315.625F));
                    builder.AddCubicBezier(new Vector2(477.082001F, -296.539001F), new Vector2(479.75F, -276.664001F), new Vector2(479.75F, -256F));
                    builder.AddCubicBezier(new Vector2(479.75F, -235.332001F), new Vector2(477.082001F, -215.457001F), new Vector2(471.75F, -196.375F));
                    builder.AddCubicBezier(new Vector2(466.414001F, -177.289001F), new Vector2(458.875F, -159.457001F), new Vector2(449.125F, -142.875F));
                    builder.AddCubicBezier(new Vector2(439.375F, -126.289001F), new Vector2(427.707001F, -111.207001F), new Vector2(414.125F, -97.625F));
                    builder.AddCubicBezier(new Vector2(400.539001F, -84.0390015F), new Vector2(385.414001F, -72.4140015F), new Vector2(368.75F, -62.75F));
                    builder.AddCubicBezier(new Vector2(352.082001F, -53.0820007F), new Vector2(334.207001F, -45.5820007F), new Vector2(315.125F, -40.25F));
                    builder.AddCubicBezier(new Vector2(296.039001F, -34.9140015F), new Vector2(276.164001F, -32.25F), new Vector2(255.5F, -32.25F));
                    builder.AddCubicBezier(new Vector2(239.5F, -32.25F), new Vector2(223.75F, -33.9570007F), new Vector2(208.25F, -37.375F));
                    builder.AddCubicBezier(new Vector2(192.75F, -40.7890015F), new Vector2(177.832001F, -45.75F), new Vector2(163.5F, -52.25F));
                    builder.AddCubicBezier(new Vector2(149.164001F, -58.75F), new Vector2(135.582001F, -66.7070007F), new Vector2(122.75F, -76.125F));
                    builder.AddCubicBezier(new Vector2(109.914001F, -85.5390015F), new Vector2(98.25F, -96.25F), new Vector2(87.75F, -108.25F));
                    builder.AddCubicBezier(new Vector2(69.75F, -128.75F), new Vector2(55.9570007F, -151.664001F), new Vector2(46.375F, -177F));
                    builder.AddCubicBezier(new Vector2(36.7890015F, -202.332001F), new Vector2(32F, -228.664001F), new Vector2(32F, -256F));
                    builder.AddCubicBezier(new Vector2(32F, -260.332001F), new Vector2(30.4139996F, -264.082001F), new Vector2(27.25F, -267.25F));
                    builder.AddCubicBezier(new Vector2(24.0820007F, -270.414001F), new Vector2(20.3320007F, -272F), new Vector2(16F, -272F));
                    builder.AddCubicBezier(new Vector2(11.6639996F, -272F), new Vector2(7.91400003F, -270.414001F), new Vector2(4.75F, -267.25F));
                    builder.AddCubicBezier(new Vector2(1.58200002F, -264.082001F), new Vector2(0F, -260.332001F), new Vector2(0F, -256F));
                    builder.AddCubicBezier(new Vector2(0F, -232.5F), new Vector2(3.03900003F, -209.832001F), new Vector2(9.125F, -188F));
                    builder.AddCubicBezier(new Vector2(15.2069998F, -166.164001F), new Vector2(23.8320007F, -145.789001F), new Vector2(35F, -126.875F));
                    builder.AddCubicBezier(new Vector2(46.1640015F, -107.957001F), new Vector2(59.5390015F, -90.7070007F), new Vector2(75.125F, -75.125F));
                    builder.AddCubicBezier(new Vector2(90.7070007F, -59.5390015F), new Vector2(107.957001F, -46.2070007F), new Vector2(126.875F, -35.125F));
                    builder.AddCubicBezier(new Vector2(145.789001F, -24.0389996F), new Vector2(166.164001F, -15.4569998F), new Vector2(188F, -9.375F));
                    builder.AddCubicBezier(new Vector2(209.832001F, -3.28900003F), new Vector2(232.5F, -0.25F), new Vector2(256F, -0.25F));
                    builder.AddCubicBezier(new Vector2(279.5F, -0.25F), new Vector2(302.164001F, -3.28900003F), new Vector2(324F, -9.375F));
                    builder.AddCubicBezier(new Vector2(345.832001F, -15.4569998F), new Vector2(366.207001F, -24.0389996F), new Vector2(385.125F, -35.125F));
                    builder.AddCubicBezier(new Vector2(404.039001F, -46.2070007F), new Vector2(421.289001F, -59.5390015F), new Vector2(436.875F, -75.125F));
                    builder.AddCubicBezier(new Vector2(452.457001F, -90.7070007F), new Vector2(465.789001F, -107.957001F), new Vector2(476.875F, -126.875F));
                    builder.AddCubicBezier(new Vector2(487.957001F, -145.789001F), new Vector2(496.539001F, -166.164001F), new Vector2(502.625F, -188F));
                    builder.AddCubicBezier(new Vector2(508.707001F, -209.832001F), new Vector2(511.75F, -232.5F), new Vector2(511.75F, -256F));
                    builder.AddCubicBezier(new Vector2(511.75F, -279.5F), new Vector2(508.707001F, -302.164001F), new Vector2(502.625F, -324F));
                    builder.EndFigure(CanvasFigureLoop.Closed);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostLavender_FFEBEBEB()
            {
                return (_colorBrush_AlmostLavender_FFEBEBEB == null)
                    ? _colorBrush_AlmostLavender_FFEBEBEB = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xEB, 0xEB, 0xEB))
                    : _colorBrush_AlmostLavender_FFEBEBEB;
            }

            // - Layer aggregator
            // Offset:<0.125, 512.125>
            CompositionColorBrush ColorBrush_Black()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x00, 0x00, 0x00));
            }

            // - Layer aggregator
            // Offset:<0.125, 512.125>
            CompositionPathGeometry PathGeometry()
            {
                return _c.CreatePathGeometry(new CompositionPath(Geometry()));
            }

            // - Layer aggregator
            // 矩形路径 1
            // 矩形路径 1.RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_32x128()
            {
                var result = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(16F, 16F);
                result.Offset = new Vector2(-16F, -64F);
                result.Size = new Vector2(32F, 128F);
                return result;
            }

            // - Layer aggregator
            // 矩形路径 1
            // 矩形路径 1.RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_32x193()
            {
                var result = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(16F, 16F);
                result.Offset = new Vector2(-16F, -96.5F);
                result.Size = new Vector2(32F, 193F);
                return result;
            }

            // Layer aggregator
            // 
            CompositionSpriteShape SpriteShape_0()
            {
                // Offset:<0.125, 512.125>
                var geometry = PathGeometry();
                if (_spriteShape_0 != null) { return _spriteShape_0; }
                var result = _spriteShape_0 = CreateSpriteShape(geometry, new Matrix3x2(1F, 0F, 0F, 1F, 0.125F, 512.125F), ColorBrush_AlmostLavender_FFEBEBEB());;
                result.CenterPoint = new Vector2(255.875F, -256.125F);
                result.StrokeBrush = ColorBrush_Black();
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 2F;
                return result;
            }

            // Layer aggregator
            // 矩形路径 1
            CompositionSpriteShape SpriteShape_1()
            {
                if (_spriteShape_1 != null) { return _spriteShape_1; }
                var result = _spriteShape_1 = _c.CreateSpriteShape(RoundedRectangle_32x193());
                result.CenterPoint = new Vector2(0F, 80F);
                result.Offset = new Vector2(239.981003F, 191.813995F);
                result.FillBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                return result;
            }

            // Layer aggregator
            // 矩形路径 1
            CompositionSpriteShape SpriteShape_2()
            {
                if (_spriteShape_2 != null) { return _spriteShape_2; }
                var result = _spriteShape_2 = _c.CreateSpriteShape(RoundedRectangle_32x128());
                result.CenterPoint = new Vector2(0F, 48F);
                result.Offset = new Vector2(239.981003F, 223.813995F);
                result.FillBrush = ColorBrush_AlmostLavender_FFEBEBEB();
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0F), new Vector2(0.666999996F, 1F))
                    : _cubicBezierEasingFunction_0;
            }

            // - Layer aggregator
            // Offset:<0.125, 512.125>
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_360_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 40.
                result.InsertKeyFrame(1F, 360F, CubicBezierEasingFunction_0());
                return result;
            }

            // - Layer aggregator
            // 矩形路径 1
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_0_to_360_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, StepThenHoldEasingFunction());
                // Frame 2.
                result.InsertKeyFrame(0.0500000007F, 0F, HoldThenStepEasingFunction());
                // Frame 40.
                result.InsertKeyFrame(1F, 360F, CubicBezierEasingFunction_0());
                return result;
            }

            // - Layer aggregator
            // 矩形路径 1
            // Rotation
            ScalarKeyFrameAnimation RotationAngleInDegreesScalarAnimation_90_to_450()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 90F, StepThenHoldEasingFunction());
                // Frame 12.
                result.InsertKeyFrame(0.300000012F, 90F, HoldThenStepEasingFunction());
                // Frame 40.
                result.InsertKeyFrame(1F, 450F, CubicBezierEasingFunction_0());
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(512F, 512F);
                var shapes = result.Shapes;
                // Offset:<0.125, 512.125>
                shapes.Add(SpriteShape_0());
                // 矩形路径 1
                shapes.Add(SpriteShape_1());
                // 矩形路径 1
                shapes.Add(SpriteShape_2());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                if (_stepThenHoldEasingFunction != null) { return _stepThenHoldEasingFunction; }
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // - Layer aggregator
            // Offset:<0.125, 512.125>
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(1F, 1F), HoldThenStepEasingFunction());
                // Frame 10.
                result.InsertKeyFrame(0.25F, new Vector2(0.800000012F, 0.800000012F), CubicBezierEasingFunction_0());
                // Frame 30.
                result.InsertKeyFrame(0.75F, new Vector2(1F, 1F), CubicBezierEasingFunction_0());
                return result;
            }

            internal WallpaperBackupIcon_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(512F, 512F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _spriteShape_0.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_360_0(), AnimationController_0());
                _spriteShape_0.StartAnimation("Scale", ScaleVector2Animation(), AnimationController_0());
                _spriteShape_1.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_0_to_360_1(), AnimationController_0());
                _spriteShape_2.StartAnimation("RotationAngleInDegrees", RotationAngleInDegreesScalarAnimation_90_to_450(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _spriteShape_0.StopAnimation("RotationAngleInDegrees");
                _spriteShape_0.StopAnimation("Scale");
                _spriteShape_1.StopAnimation("RotationAngleInDegrees");
                _spriteShape_2.StopAnimation("RotationAngleInDegrees");
            }

        }
    }
}
